import {writeFile} from 'node:fs/promises';
import {baseDataRateScientific,buyHardwareClass,canAffordScientificCreditCost,creditRateScientific,dataRateScientific,exactEconomyValue,hardwareCostScientific,hardwareIds,newGame,startResearchProject,startTraining,trainingDataCostForLevelScientific,trainingDurationSeconds,type TrainingTrack} from '../src/economy';
import {queueExperiment} from '../src/experiments';
import {advance,simulateBalance} from '../src/simulation';
import {ScientificNumber} from '../src/scientificNumber';

type TrainingPoint={track:TrainingTrack;level:number;startedAt:number;completedAt:number|null;savedSeconds:number};
function run(training:boolean,hours=24,competition=false){let state=newGame(0),track:TrainingTrack='quality',lastCompletion=0;const firstHardware:Record<string,number>={},points:TrainingPoint[]=[];for(let elapsed=0;elapsed<hours*3600;elapsed+=5){state=advance(state,5,true).state;if(training&&!state.activeTraining){const beforeData=exactEconomyValue(state,'data'),started=startTraining(state,track);if(started!==state){const level=(track==='quality'?state.qualityLevel:state.efficiencyLevel)+1;points.push({track,level,startedAt:elapsed+5,completedAt:null,savedSeconds:elapsed+5-lastCompletion});state=started;track=track==='quality'?'efficiency':'quality';}}
 const completed=state.telemetry.recentEvents.filter(e=>e.type==='training-complete');for(const point of points)if(point.completedAt===null){const event=completed.find(e=>e.details.track===point.track&&e.at/1000>=point.startedAt);if(event){point.completedAt=event.at/1000;lastCompletion=point.completedAt;}}
 if(competition){if(!state.researchLabs.some(Boolean))state=startResearchProject(state,'dataGeneration');if(!state.experiments.active)state=queueExperiment(state,'hardware',state.savedAt,'short');}
 const affordable=hardwareIds.map((id,index)=>({id,index,cost:hardwareCostScientific(id,state.hardwareCounts[id],state)})).filter(x=>canAffordScientificCreditCost(state,x.cost)).sort((a,b)=>a.cost.compare(b.cost)||a.index-b.index)[0];if(affordable){const before=state.hardwareCounts[affordable.id];state=buyHardwareClass(state,affordable.id,1);if(before===0)firstHardware[affordable.id]=elapsed+5;}}
 return{hours,training,quality:state.qualityLevel,efficiency:state.efficiencyLevel,creditsPerSecond:creditRateScientific(state.hardware,state.level,state,state.savedAt).toJSON(),dataPerSecond:dataRateScientific(state).toJSON(),firstHardware,trainingPoints:points,finalData:exactEconomyValue(state,'data').toJSON(),researchStarted:state.lifetime.researchStarted,researchCompleted:state.lifetime.researchCompleted,analyses:state.experiments.completedIds.length};}
const userRates=[1,100,10_000,1_000_000].map(users=>({users,dataPerSecond:baseDataRateScientific(ScientificNumber.from(users)).toNumber()}));
const levels=[1,5,10,20,30].map(level=>({level,dataCost:trainingDataCostForLevelScientific(level).toScientificString(8),durationSeconds:trainingDurationSeconds(level)}));
const baseline=run(false),active=run(true),passive=simulateBalance(1,false,1708),control=run(true,24,true);
const value=(x:{m:number;e:number})=>`${x.m.toFixed(4)}e${x.e>=0?'+':''}${x.e}`;
const lines=['# Schicht-2-Balance-Messung','',`Messung mit unveränderter Hardwarekurve aus Schicht 1. Custom-Basis-/Trainingsläufe laufen 24 Stunden in 5-Sekunden-Schritten mit echten Economy- und Kauf-Funktionen. Der passive Lauf nutzt das bestehende realistische Sitzungsprofil; der Kontrolllauf lässt Forschung und Analysen aktiv.`,'','## Data-Grundrate','',...userRates.map(x=>`- ${x.users.toLocaleString('de-DE')} Users: ${x.dataPerSecond.toLocaleString('de-DE')} Data/s ohne Boni`),'','## Trainingsparameter','', '| Level | Datenkosten | Dauer |','|---:|---:|---:|',...levels.map(x=>`| ${x.level} | ${x.dataCost} | ${x.durationSeconds.toFixed(1)} s |`),'','## Tatsächliche Läufe','',`- Basis ohne Training: Creditrate ${value(baseline.creditsPerSecond)} C/s; Data ${value(baseline.dataPerSecond)}/s; Hardware ${JSON.stringify(baseline.firstHardware)}.`,`- Aktiv, abwechselnd Quality/Efficiency: Q${active.quality}/E${active.efficiency}; Creditrate ${value(active.creditsPerSecond)} C/s; Data ${value(active.dataPerSecond)}/s; Hardware ${JSON.stringify(active.firstHardware)}.`,`- Trainingsstarts/-abschlüsse: ${active.trainingPoints.slice(0,12).map((x,index)=>`${x.track} L${x.level}: Start ${x.startedAt}s, Abschluss ${x.completedAt??'nicht erreicht'}s, tatsächliche Anspar-/Wartezeit ${(x.startedAt-(index?active.trainingPoints[index-1].completedAt??x.startedAt:0)).toFixed(1)}s`).join('; ')}.`,`- Passives realistisches Profil: Q${passive.final.qualityLevel}/E${passive.final.efficiencyLevel}, ${Object.keys(passive.milestones.hardware).length} Hardwareklassen, Creditrate ${value(passive.exactFinal!.creditsPerSecond)} C/s.`,`- Kontrolle mit Forschung/Analysen: Q${control.quality}/E${control.efficiency}, Datenbestand ${value(control.finalData)}, Forschung ${control.researchStarted} Starts/${control.researchCompleted} Abschlüsse, Analysen ${control.analyses}; echte Forschungs- und Analysestarts konkurrieren in diesem Lauf mit Training um Data.`,'','Das erste aktive Training startet nach 75 Sekunden und verfehlt damit das Ziel von 3–5 aktiven Minuten nach unten. Außerdem steigen die reinen Ansparpausen im 24-Stunden-Lauf nicht monoton, weil die unveränderte Hardwarekurve die Nutzer- und damit Data-Grundrate schneller erhöht als die frühen Trainingskosten. Beide Konflikte sind Messbefunde; die vorgegebenen Formeln wurden nicht still verändert. Prestige-, Item- und Hardware-Meilenstein-Boni für Training beschleunigen die feste Laufzeit absichtlich nicht mehr; Data-Boni aus Prestige, Items, Forschung und Meilensteinen bleiben erhalten, werden aber gemeinsam auf einen Multiplikator unter 5 abgeflacht.'];
await writeFile('docs/layer-two-balance.json',JSON.stringify({version:1,userRates,levels,baseline,active,passive:{quality:passive.final.qualityLevel,efficiency:passive.final.efficiencyLevel,hardware:passive.milestones.hardware,exactFinal:passive.exactFinal},control},null,2)+'\n');
await writeFile('docs/layer-two-balance.md',lines.join('\n')+'\n');console.log('Wrote docs/layer-two-balance.{json,md}');
