import {BALANCE,GameState,itemCombinationBonus} from './economy';
import {addEvent} from './telemetry';
export type Achievement={id:string;de:string;en:string;descriptionDe:string;descriptionEn:string;thresholds:number[];progress:(s:GameState)=>number};
const family=(id:string,de:string,en:string,descriptionDe:string,descriptionEn:string,thresholds:number[],progress:(s:GameState)=>number):Achievement=>({id,de,en,descriptionDe,descriptionEn,thresholds,progress});
const scale=(...values:number[])=>values;
export const achievements:Achievement[]=[
 family('calculators','Das passt noch auf den Schreibtisch','Still desk-sized','Kaufe Taschenrechner. Die Karte steigt automatisch zur nächsten Stufe auf.','Buy calculators. The card automatically advances to the next tier.',scale(10,100,1e3,1e4,1e5,1e6,1e7,1e8,1e9,1e10),s=>s.lifetime.calculatorsBought),
 family('hardware','Hardware-Imperium','Hardware empire','Kaufe Hardware-Einheiten über alle Klassen.','Buy hardware units across all classes.',scale(25,250,2500,25000,250000,2.5e6,2.5e7,2.5e8,2.5e9,2.5e10),s=>s.lifetime.hardwareBought),
 family('classes','Siliziumzoo','Silicon zoo','Entdecke Hardwareklassen.','Discover hardware classes.',scale(2,3,5,7,9,11,12,13,14,15),s=>s.lifetime.hardwareClasses.length),
 family('milestones','Mastery-Netz','Mastery network','Erreiche Hardware-Meilensteine.','Reach hardware milestones.',scale(3,10,25,50,90,150,300,600,1200,2500),s=>s.lifetime.milestones),
 family('prestiges','Noch ein Neustart','One more reset','Führe Prestige-Neustarts durch.','Perform prestige resets.',scale(1,5,15,35,75,150,300,600,1200,2500),s=>s.lifetime.prestiges),
 family('int','Denken in Großbuchstaben','Thinking in capitals','Verdiene INT insgesamt.','Earn INT in total.',scale(1,100,1e3,1e4,1e5,1e6,1e7,1e8,1e9,1e10),s=>s.lifetime.intEarned),
 family('lab-time','Licht im Labor','Lab lights on','Sammle Laborarbeitszeit; parallele Labore zählen einzeln.','Accumulate lab work; parallel labs count separately.',scale(3600,86400,604800,2.592e6,7.776e6,1.5552e7,3.1104e7,6.2208e7,1.24416e8,2.48832e8),s=>s.lifetime.labSeconds),
 family('research','Peer Review später','Peer review later','Schließe Forschungsprojekte ab.','Complete research projects.',scale(1,10,50,250,1e3,5e3,2.5e4,1e5,5e5,2e6),s=>s.lifetime.researchCompleted),
 family('training','Noch eine Epoche','One more epoch','Schließe Modelltrainings ab.','Complete model trainings.',scale(1,10,50,250,1e3,5e3,2.5e4,1e5,5e5,2e6),s=>s.lifetime.trainingCompleted),
 family('crafting','Mit Absicht gebaut','Built on purpose','Stelle Items gezielt her.','Craft items intentionally.',scale(1,5,25,100,500,2500,1e4,5e4,2.5e5,1e6),s=>s.lifetime.itemsCrafted),
 family('items','Kuriositätenkabinett','Cabinet of curiosities','Entdecke unterschiedliche Itemtypen.','Discover distinct item types.',scale(1,2,3,4,5,6,7,8,9,9),s=>s.lifetime.itemTypes.length),
 family('taps','Finger aus Stahl','Fingers of steel','Führe vergütete aktive Taps aus.','Perform rewarded active taps.',scale(100,1e3,1e4,1e5,1e6,1e7,1e8,1e9,1e10,1e11),s=>s.lifetime.taps),
 family('components','Materialwissenschaft','Material science','Finde Komponenten.','Find components.',scale(10,100,1e3,1e4,1e5,1e6,1e7,1e8,1e9,1e10),s=>s.lifetime.componentsEarned),
 family('credits','Kapitalmaschine','Capital machine','Produziere reguläre Credits.','Produce regular credits.',scale(1e3,1e5,1e7,1e9,1e12,1e15,1e20,1e30,1e50,1e100),s=>s.lifetime.regularCredits),
 family('data','Datensee','Data lake','Produziere reguläre Daten.','Produce regular data.',scale(100,1e3,1e4,1e5,1e6,1e7,1e8,1e9,1e10,1e12),s=>s.lifetime.regularData),
 family('active','Nur noch fünf Minuten','Five more minutes','Sammle aktive Spielzeit.','Accumulate active play time.',scale(600,3600,14400,43200,86400,259200,604800,1.2096e6,2.592e6,5.184e6),s=>s.lifetime.activeSeconds),
 family('overclock','Roter Bereich','Redline','Aktiviere Overclock.','Activate overclock.',scale(1,10,50,250,1e3,5e3,2.5e4,1e5,5e5,2e6),s=>s.lifetime.overclocks),
 family('research-start','Anträge schreiben','Write the grants','Starte Forschung.','Start research.',scale(1,10,100,1e3,1e4,1e5,1e6,1e7,1e8,1e9),s=>s.lifetime.researchStarted),
 family('training-start','Epochenschleife','Epoch loop','Starte Trainingsläufe.','Start training runs.',scale(1,10,100,1e3,1e4,1e5,1e6,1e7,1e8,1e9),s=>s.lifetime.trainingStarted),
];
const singles:[string,string,string,string,string,(s:GameState)=>boolean][]=[
 ['named','Hallo, Welt','Hello, world','Benenne dein KI-Modell.','Name your AI model.',s=>!!s.aiName],['dual-lab','Beide Hände voll','Both hands full','Beschäftige zwei Labore gleichzeitig.','Run two labs simultaneously.',s=>s.researchLabs.filter(Boolean).length>=2],['breakthrough','Heureka-ish','Eureka-ish','Schalte einen Forschungsdurchbruch frei.','Unlock a research breakthrough.',s=>s.breakthroughs.length>0],['rare','Glitzert wissenschaftlich','Scientifically shiny','Finde mindestens ein seltenes Item.','Find at least one rare item.',s=>s.inventory.some(i=>['rare','epic','legendary','mythic'].includes(i.rarity))],['run-mix','Gemischte Signale','Mixed signals','Erreiche in einem Run Meilensteine in drei Klassen.','Reach milestones in three classes in one run.',s=>s.runMilestoneClasses.length>=3],['combo','Stecker passt','It plugs in','Rüste eine wirksame Item-Kombination aus.','Equip an effective item combination.',s=>itemCombinationBonus(s,'credits')>0||itemCombinationBonus(s,'research')>0],['experiment','Keine Kontrollgruppe','No control group','Schließe eine Analyse ab.','Complete an analysis.',s=>s.experiments.completedIds.length>0],['all-classes','Volle Infrastruktur','Full infrastructure','Entdecke alle 15 Hardwareklassen.','Discover all 15 hardware classes.',s=>s.discovered.length>=15],['mastery','Meister aller Maschinen','Master of machines','Erreiche 500 Einheiten einer Hardwareklasse.','Reach 500 units of a hardware class.',s=>Object.values(s.hardwareCounts).some(n=>n>=500)],['automation','Die Maschinen kaufen Maschinen','Machines buying machines','Aktiviere einen Hardware-Autobuyer.','Enable a hardware autobuyer.',s=>Object.values(s.hardwareAutoBuyers).some(Boolean)],
];
for(const [id,de,en,descriptionDe,descriptionEn,test] of singles)achievements.push(family(id,de,en,descriptionDe,descriptionEn,[1],s=>test(s)?1:0));
export const achievementResearchBonus=(s:GameState)=>Math.min(BALANCE.achievementResearchCap,Math.floor(s.achievementPoints/10)*BALANCE.achievementResearchPerTen);
export function currentAchievementTier(s:GameState,a:Achievement){let i=0;while(i<a.thresholds.length&&s.achievementClaims.includes(`${a.id}:${i}`))i++;return Math.min(i,a.thresholds.length-1)}
export function claimAchievement(s:GameState,id:string,tier:number){const a=achievements.find(x=>x.id===id),key=`${id}:${tier}`;if(!a||tier<0||tier>=a.thresholds.length||a.progress(s)<a.thresholds[tier]||s.achievementClaims.includes(key))return s;const rewardIndex=Math.min(tier,BALANCE.achievementTierGems.length-1),gems=BALANCE.achievementTierGems[rewardIndex],points=BALANCE.achievementPointsPerTier[rewardIndex];return addEvent({...s,gems:s.gems+gems,achievementPoints:s.achievementPoints+points,achievementClaims:[...s.achievementClaims,key],gemLedger:[...s.gemLedger,{id:`achievement-${key}`,at:s.savedAt,amount:gems,source:'achievement'}]},'achievement',s.savedAt,{id,tier,gems,points});}
export const achievementReady=(s:GameState)=>achievements.some(a=>a.thresholds.some((t,i)=>a.progress(s)>=t&&!s.achievementClaims.includes(`${a.id}:${i}`)));
