import {describe,expect,it} from 'vitest';import{BALANCE,newGame,bulkCost,computeRate,creditRate,GameState}from'./economy';import{advance}from'./simulation';import{buyNode,prestige}from'./prestige';import{craft,equip,salvage,toggleLock,upgrade,randomItem}from'./inventory';import{queueExperiment,completeExperiment,experimentSpeed}from'./experiments';import{claimMission,rollPeriods}from'./missions';import{buyGemOffer}from'./gemShop';import{rewardAd}from'./ads';import{restore,serialize}from'./storage';
describe('alpha systems',()=>{
 it('keeps long and split simulation equivalent',()=>{const s={...newGame(0),hardware:10};const a=advance(s,1000).state,b=advance(advance(s,400).state,600).state;expect(b.level).toBe(a.level);expect(b.credits).toBeCloseTo(a.credits,6)});
 it('prestiges once and purchases prerequisite nodes',()=>{let s:GameState={...newGame(0),runCreditsEarned:13e9,lifetimeCreditsEarned:13e9,lifetimeEligibleCredits:13e9};s=prestige(s);expect(s.prestigeCount).toBe(1);const total=s.totalINTEarned;expect(prestige(s)).toBe(s);const bought=buyNode(s,'impulseNetwork');expect(bought.nodes).toContain('impulseNetwork');expect(bought.totalINTEarned).toBe(total);expect(buyNode(bought,'impulseNetwork')).toBe(bought)});
 it('offline autobuyer respects reserve and exact summed costs',()=>{const s={...newGame(0),prestigeCount:1,nodes:['shoppingAgent'],credits:1000,automation:{enabled:true,reserve:500,elapsed:0,target:null}};const n=advance(s,10).state;expect(n.credits).toBeGreaterThanOrEqual(500);expect(n.hardware).toBeGreaterThan(1);expect(bulkCost(1,n.hardware-1,s)).toBeLessThanOrEqual(510)});
 it('completes queued experiment once and grants first item',()=>{let s:GameState={...newGame(0),discovered:['calculator','sbc'] as ('calculator'|'sbc')[]};s=queueExperiment(s,'hardware',0,'intro');const end=s.experiments.active!.endsAt;s=completeExperiment(s,end,()=>1);const count=s.components;expect(s.inventory).toHaveLength(1);expect(s.onboarding.completed).toContain('intro-experiment');expect(completeExperiment(s,end,()=>0).components).toBe(count)});
 it('crafts, equips, upgrades, locks and safely salvages',()=>{let s={...newGame(0),components:6000,componentInventory:{circuits:1000,laser:1000,graphene:1000,titaniumBolts:1000,nanotubes:1000,quantumCores:1000},blueprintFragments:100};s=craft(s,'quantum-chip','common');const id=s.inventory[0].id;s=equip(s,id);expect(salvage(s,id)).toBe(s);s=toggleLock(s,id);expect(s.inventory[0].locked).toBe(true);const before=s.components;s=upgrade(s,id);expect(s.inventory[0].level).toBe(1);expect(s.components).toBeLessThan(before)});
 it('applies deterministic pity guarantees',()=>{let s=newGame(0);for(let i=0;i<20;i++)s=randomItem(s,()=>.01);expect(['rare','epic','legendary']).toContain(s.inventory.at(-1)!.rarity)});
 it('claims missions and prevents duplicate gem spending',()=>{let s=rollPeriods(newGame(0),0),task=s.missions.daily.tasks.find(x=>x.metric==='hardwareBought')!;s={...s,lifetime:{...s.lifetime,hardwareBought:task.goal}};s=claimMission(s,'daily',task.id);const gems=s.gems;expect(claimMission(s,'daily',task.id).gems).toBe(gems);const poor={...s,gems:119};expect(buyGemOffer(poor,'components',1)).toBe(poor)});
 it('extends but caps boosts',()=>{let s={...newGame(0),gems:5000};s=buyGemOffer(s,'training-boost',1);expect(s.trainingBoostUntil).toBe(3600001);for(let i=0;i<30;i++)s=buyGemOffer(s,'training-boost',i+2);expect(s.trainingBoostUntil).toBeLessThanOrEqual(BALANCE.gemShop.boostCap*1000+31)});
 it('rewards successful ads once, but not cancellation or duplicate callbacks',()=>{let s=newGame(0);expect(rewardAd(s,'creditDrop','x','cancel',0)).toBe(s);s=rewardAd(s,'creditDrop','x','success',0);const credits=s.credits;expect(rewardAd(s,'creditDrop','x','success',0).credits).toBe(credits)});
 it('migrates v1 and rejects invalid imports without overwriting payload',()=>{const v1=JSON.stringify({version:1,state:{credits:12,hardware:2,level:1,training:3,savedAt:4}});expect(restore(v1).state.credits).toBe(12);expect(restore(serialize(newGame(0))).error).toBeUndefined();expect(restore('{"version":2,"state":{"credits":null}}').error).toMatch(/beschädigt/)});
});

it('finds every named component through reachable experiments and crafts with exact ingredients',()=>{let s:GameState={...newGame(0),discovered:['calculator','sbc']};for(const type of ['hardware','architecture','artifact'] as const){s=queueExperiment(s,type,s.savedAt,'long');s=completeExperiment(s,s.experiments.active!.endsAt,()=>1)}for(const amount of Object.values(s.componentInventory))expect(amount).toBeGreaterThan(0);const rich={...s,componentInventory:{circuits:1000,laser:1000,graphene:1000,titaniumBolts:1000,nanotubes:1000,quantumCores:1000},components:6000,blueprintFragments:100},recipe=BALANCE.itemRecipes['quantum-chip'].ingredients,made=craft(rich,'quantum-chip','rare');for(const id of Object.keys(recipe) as (keyof typeof recipe)[])expect(made.componentInventory[id]).toBe(rich.componentInventory[id]-recipe[id]);expect(made.telemetry.recentEvents.at(-1)?.type).toBe('item-craft')});

it('applies all three blueprint effects to real production or analysis',()=>{const rich={...newGame(0),componentInventory:{circuits:1000,laser:1000,graphene:1000,titaniumBolts:1000,nanotubes:1000,quantumCores:1000},components:6000,blueprintFragments:100};const computeItem=craft(rich,'quantum-chip','common'),computeEquipped=equip(computeItem,computeItem.inventory[0].id);expect(computeRate(computeEquipped.hardware,computeEquipped)).toBeGreaterThan(computeRate(rich.hardware,rich));const scanner=craft(rich,'field-scanner','common'),scannerEquipped=equip(scanner,scanner.inventory[0].id);expect(experimentSpeed(scannerEquipped)).toBeGreaterThan(experimentSpeed(rich));const creditItem=craft(rich,'neural-asic','common'),creditEquipped=equip(creditItem,creditItem.inventory[0].id);expect(creditRate(creditEquipped.hardware,creditEquipped.level,creditEquipped)).toBeGreaterThan(creditRate(rich.hardware,rich.level,rich))});
