import {learnBlueprint} from './blueprints';
import {describe,expect,it} from 'vitest';
import {BALANCE,addData,grantComponents,newGame,exactEconomyValue,type GameState,type ItemTypeId,type ModuleId} from './economy';
import {cancelCrafting,craft,craftAffordability,craftModule,moduleAffordability,runCraftingPlanner,settleCrafting,forgeItem,upgrade,createItem,fuseItems} from './inventory';
import {buyGemOffer} from './gemShop';
import {advance,advanceTo} from './simulation';
import {restore,serialize,persistGame,loadGame,type StorageLike} from './storage';

function supplies(type:keyof typeof BALANCE.itemRecipes='quantum-chip',quantity=5):GameState{
 const recipe=BALANCE.itemRecipes[type],base=addData(newGame(0),recipe.data*quantity);
 let s=grantComponents(base,Object.fromEntries(Object.entries(recipe.ingredients).map(([id,n])=>[id,n*quantity])));
 s={...s,completedResearch:['blueprints'],impulseRelayBlueprint:true,insightArchiveBlueprint:true,blueprintFragments:recipe.blueprints,modules:{...s.modules,...Object.fromEntries(Object.entries(recipe.modules).map(([id,n])=>[id,n*quantity]))}};
 return learnBlueprint(s,type);
}
function moduleSupplies(id:ModuleId,quantity=5){const recipe=BALANCE.modules[id];return grantComponents({...addData(newGame(0),recipe.data*quantity),completedResearch:['blueprints']},Object.fromEntries(Object.entries(recipe.ingredients).map(([key,n])=>[key,n*quantity])));}
const unchanged=(s:GameState,action:(s:GameState)=>GameState)=>{const before=structuredClone(s);expect(action(s)).toBe(s);expect(s).toEqual(before);};

describe('atomic full-order ingredient reservation',()=>{
 it('rejects five quantum chips when only one compute bus and one unit of Data are available',()=>{const rich=supplies(),one={...rich,data:1800,exactEconomy:{...rich.exactEconomy,data:{m:1.8,e:3}},modules:{...rich.modules,computeBus:1}};unchanged(one,s=>craft(s,'quantum-chip','common',5));const quote=craftAffordability(one,'quantum-chip',5);expect(quote.missingModules.computeBus).toBe(4);expect(quote.data.cost).toBe(9000);expect(quote.data.missing).toBeCloseTo(7200);});
 it('reserves ingredients for exactly five and produces exactly five without another debit',()=>{const s=supplies(),preview=craftAffordability(s,'quantum-chip',5),paid=craft(s,'quantum-chip','common',5);expect(preview.affordable).toBe(true);expect(paid.crafting.active?.ingredients).toEqual(preview.recipe?.ingredients);expect(paid.modules.computeBus).toBe(0);expect(paid.blueprintFragments).toBe(0);expect(paid.data).toBe(0);expect(Object.values(paid.componentInventory).every(n=>n===0)).toBe(true);expect(s.modules.computeBus).toBe(5);const done=advance(paid,1500).state;expect(done.inventory).toHaveLength(5);expect(done.lifetime.itemsCrafted).toBe(5);expect(done.crafting.active).toBeNull();expect(done.data).toBe(0);expect(settleCrafting(done)).toBe(done);expect(advance(done,300).state.inventory).toHaveLength(5);});
 it('rejects Data shortage independently of sufficient modules, fragments and materials',()=>{const s=supplies(),short={...s,data:8999,exactEconomy:{...s.exactEconomy,data:{m:8.999,e:3}}};unchanged(short,x=>craft(x,'quantum-chip','common',5));});
 it('prevents two current-state orders from reserving the same ingredients',()=>{const s=supplies('quantum-chip',1),paid=craft(s,'quantum-chip');expect(paid.crafting.active?.quantity).toBe(1);unchanged(paid,x=>craft(x,'quantum-chip'));});
 it.each([0,-1,1.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1,Number.MAX_SAFE_INTEGER,null,'5'])('rejects invalid/overflow quantity %s without any mutation',quantity=>{unchanged(supplies(),s=>craft(s,'quantum-chip','common',quantity as number));unchanged(moduleSupplies('computeBus'),s=>craftModule(s,'computeBus',quantity as number));});
 it('rejects an unknown recipe, incorrect rarity, locked blueprint and full waiting queue',()=>{unchanged(supplies(),s=>craft(s,'missing' as ItemTypeId));unchanged(moduleSupplies('computeBus'),s=>craftModule(s,'missing' as ModuleId));unchanged(supplies(),s=>craft(s,'quantum-chip','mythic',5));unchanged({...supplies('impulse-relay'),impulseRelayBlueprint:false},s=>craft(s,'impulse-relay','common',5));unchanged({...supplies('insight-archive'),insightArchiveBlueprint:false},s=>craft(s,'insight-archive','common',5));unchanged({...moduleSupplies('computeBus'),completedResearch:[]},s=>craftModule(s,'computeBus',5));let full=moduleSupplies('computeBus',10);for(let i=0;i<4;i++)full=craftModule(full,'computeBus');expect(full.crafting.queue).toHaveLength(3);unchanged(full,s=>craftModule(s,'computeBus'));unchanged({...supplies(),crafting:full.crafting,nextId:full.nextId},s=>craft(s,'quantum-chip'));});
 it.each(Object.keys(BALANCE.itemRecipes) as (keyof typeof BALANCE.itemRecipes)[])('shares preview and complete reservation for item recipe %s',type=>{const s=supplies(type),quote=craftAffordability(s,type,5),paid=craft(s,type,BALANCE.itemRecipes[type].rarity,5);expect(quote.affordable).toBe(true);expect(paid.crafting.active?.ingredients).toEqual(quote.recipe?.ingredients);expect(paid.data).toBe(0);expect(paid.blueprintFragments).toBe(0);expect(advance(paid,quote.recipe!.durationPerUnit*5).state.inventory.filter(i=>i.type===type)).toHaveLength(5);});
 it.each(Object.keys(BALANCE.modules) as ModuleId[])('shares preview and complete reservation for module recipe %s',id=>{const s=moduleSupplies(id),quote=moduleAffordability(s,id,5),paid=craftModule(s,id,5);expect(quote.affordable).toBe(true);expect(paid.crafting.active?.ingredients).toEqual(quote.recipe?.ingredients);expect(paid.data).toBe(0);expect(advance(paid,300).state.modules[id]).toBe(5);});
 it('planner and manual start have identical costs and cannot reuse a reservation',()=>{const s={...supplies('quantum-chip',1),axiomUpgrades:['craftingPlanner' as const],craftingPlanner:{enabled:true,recipeId:'quantum-chip' as const,target:5 as const,elapsed:0}};const manual=craft(s,'quantum-chip'),planned=runCraftingPlanner(s);expect(planned).toEqual(manual);unchanged(planned,runCraftingPlanner);});
 it('uses noncanonical scientific Data and rejects corrupt ledgers rather than reserving materials',()=>{const s=supplies();expect(craft({...s,data:1,exactEconomy:{...s.exactEconomy,data:{m:90,e:2}}},'quantum-chip','common',5).data).toBe(0);for(const bad of [{m:NaN,e:0},{m:1,e:Infinity},{m:-1,e:0}])unchanged({...s,exactEconomy:{...s.exactEconomy,data:bad}},x=>craft(x,'quantum-chip','common',5));unchanged({...s,credits:NaN},x=>craft(x,'quantum-chip','common',5));});
 it('preserves reservations and partial completion across save/load and offline completion exactly once',()=>{let s=craft(supplies('quantum-chip',5),'quantum-chip','common',5);s=advance(s,600).state;expect(s.inventory).toHaveLength(2);expect(s.crafting.active?.completed).toBe(2);const restored=restore(serialize(s),s.savedAt);expect(restored.error).toBeUndefined();expect(restored.state.crafting).toEqual(s.crafting);const values=new Map<string,string>(),storage:StorageLike={getItem:k=>values.get(k)??null,setItem:(k,v)=>{values.set(k,v)},removeItem:k=>{values.delete(k)}};expect(persistGame(storage,restored.state,600000).saved).toBe(true);const offline=advanceTo(loadGame(storage,1500000).state,1500000).state;expect(offline.inventory).toHaveLength(5);expect(offline.data).toBe(0);expect(persistGame(storage,offline,1500000).saved).toBe(true);const reload=advanceTo(loadGame(storage,1500000).state,1500000).state;expect(reload.inventory).toHaveLength(5);expect(reload.crafting.active).toBeNull();});
 it('refunds all ingredients of a queued full order once, and retains the active cancellation rule',()=>{const s=supplies('quantum-chip',6),active=craft(s,'quantum-chip'),queued=craft(active,'quantum-chip','common',5),id=queued.crafting.queue[0].id;unchanged(queued,x=>cancelCrafting(x,x.crafting.active!.id));const refunded=cancelCrafting(queued,id);expect(refunded.componentInventory).toEqual(active.componentInventory);expect(refunded.modules).toEqual(active.modules);expect(refunded.blueprintFragments).toBe(active.blueprintFragments);expect(exactEconomyValue(refunded,'data').compare(exactEconomyValue(active,'data'))).toBe(0);expect(refunded.lifetime).toEqual(queued.lifetime);expect(refunded.crafting).toEqual(active.crafting);unchanged(refunded,x=>cancelCrafting(x,id));expect(advance(refunded,1800).state.inventory).toHaveLength(1);});
 it('refunds queued module costs and retains very large scientific Data',()=>{const s=moduleSupplies('computeBus',2),active=craftModule(s,'computeBus'),queued=craftModule(active,'computeBus'),refunded=cancelCrafting(queued,queued.crafting.queue[0].id);expect(refunded.modules).toEqual(active.modules);expect(refunded.componentInventory).toEqual(active.componentInventory);expect(refunded.data).toBe(active.data);const huge={...queued,data:1e300,exactEconomy:{...queued.exactEconomy,data:{m:1,e:1000}}},after=cancelCrafting(huge,huge.crafting.queue[0].id);expect(after.data).toBe(1e300);expect(after.exactEconomy.data).toEqual({m:1,e:1000});expect(restore(serialize(after),0).error).toBeUndefined();});
 it('rejects missing module materials or total Data before spending anything',()=>{const s=moduleSupplies('computeBus');unchanged({...s,componentInventory:{...s.componentInventory,copperCoils:29}},x=>craftModule(x,'computeBus',5));unchanged({...s,data:1249,exactEconomy:{...s.exactEconomy,data:{m:1.249,e:3}}},x=>craftModule(x,'computeBus',5));});
 it('settles an overdue active job and its queued successor on their reserved timeline only once',()=>{const first=craft(supplies('quantum-chip',6),'quantum-chip'),queued=craft(first,'quantum-chip','common',5),done=settleCrafting({...queued,savedAt:1800000});expect(done.inventory).toHaveLength(6);expect(done.crafting).toEqual({active:null,queue:[]});expect(done.data).toBe(0);expect(settleCrafting(done)).toBe(done);expect(restore(serialize(done),done.savedAt).state.inventory).toHaveLength(6);});
 it('preserves a waiting reservation through reload and refunds it once after partial active completion',()=>{const first=craft(supplies('quantum-chip',6),'quantum-chip','common',5),queued=craft(first,'quantum-chip'),partial=advance(queued,600).state,loaded=restore(serialize(partial),partial.savedAt).state;expect(loaded.crafting.active?.completed).toBe(2);expect(loaded.crafting.queue[0].ingredients).toEqual(queued.crafting.queue[0].ingredients);const id=loaded.crafting.queue[0].id,refunded=cancelCrafting(loaded,id);expect(refunded.data).toBe(1800);expect(refunded.modules.computeBus).toBe(1);expect(refunded.blueprintFragments).toBe(0);unchanged(refunded,x=>cancelCrafting(x,id));expect(advance(refunded,1200).state.inventory).toHaveLength(5);});
 it('existing gem acceleration creates only reserved results and never charges ingredients again',()=>{const paid=craft(supplies('quantum-chip',2),'quantum-chip','common',2),boosted=buyGemOffer(paid,'craft-30m',0);expect(boosted.inventory).toHaveLength(1);expect(boosted.data).toBe(0);expect(boosted.crafting.active?.completed).toBe(1);expect(restore(serialize(boosted),0).error).toBeUndefined();expect(advance(boosted,300).state.inventory).toHaveLength(2);});
 it('keeps immediate fusion atomic and rejects unknown or duplicated ingredient instances',()=>{let s=newGame(0);for(let i=0;i<3;i++)s=createItem(s,'quantum-chip','common');const ids=s.inventory.map(i=>i.id),before=structuredClone(s);for(const invalid of [[ids[0],ids[0],ids[1]],[...ids,'missing'],[ids[0],ids[1],'missing']])unchanged(s,x=>fuseItems(x,invalid));const result=fuseItems(s,ids);expect(s).toEqual(before);expect(result.inventory).toHaveLength(1);expect(result.inventory[0].rarity).toBe('uncommon');expect(result.data).toBe(s.data);expect(restore(serialize(result),0).error).toBeUndefined();});
 it('rejects invalid item creation and ID collisions without changing inventory',()=>{const s=createItem(newGame(0),'quantum-chip','common');unchanged(s,x=>createItem(x,'missing' as ItemTypeId,'common'));unchanged(s,x=>createItem(x,'quantum-chip','missing' as never));unchanged({...s,nextId:1},x=>createItem(x,'quantum-chip','common'));unchanged({...s,nextId:Number.MAX_SAFE_INTEGER},x=>createItem(x,'quantum-chip','common'));});
 it('leaves the whole state unchanged when upgrade or forge Data is insufficient',()=>{const base=grantComponents(createItem(newGame(0),'quantum-chip','common'),{circuits:1000});unchanged(addData(base,749),s=>upgrade(s,s.inventory[0].id));unchanged(addData(base,999),s=>forgeItem(s,s.inventory[0].id));});
 it('does not spend upgrade or forge materials when an invalid scientific ledger prevents payment',()=>{const s=grantComponents({...addData(newGame(0),1e6),inventory:[{id:'x',type:'quantum-chip',rarity:'common',level:0,locked:false}]},{circuits:1000}),invalid={...s,exactEconomy:{...s.exactEconomy,data:{m:NaN,e:0}}};unchanged(invalid,x=>upgrade(x,'x'));unchanged(invalid,x=>forgeItem(x,'x'));});
});
