import{beforeEach,describe,expect,it,vi}from'vitest';import{actionHaptic,actionSound,AudioPlayer,haptic}from'./audio';import{buyHardwareClass,newGame}from'./economy';import{prestige,axiomReset}from'./prestige';
const setupDocument=(hidden=false)=>Object.defineProperty(globalThis,'document',{configurable:true,value:{hidden}});
const fakeAudio=()=>{const play=vi.fn(()=>Promise.resolve()),pause=vi.fn(),listeners=new Map<string,()=>void>();return{play,pause,listeners,element:{canPlayType:()=> 'probably',play,pause,addEventListener:(name:string,fn:()=>void)=>listeners.set(name,fn),src:'',volume:1,loop:false} as unknown as HTMLAudioElement}};
describe('audio routing',()=>{beforeEach(()=>setupDocument(false));it('plays only successful purchases, milestones and resets',()=>{const base={...newGame(0),credits:1e15},bought=buyHardwareClass(base,'calculator',1);expect(actionSound('buy-class',base,bought)).toBe('purchase');expect(actionSound('buy-class',base,base)).toBeNull();const milestone=buyHardwareClass(base,'calculator',9);expect(actionSound('buy-class',base,milestone)).toBe('unlock');const ready={...base,lifetimeEligibleCredits:1e15,cycleEligibleCredits:1e15,exactEconomy:{...base.exactEconomy,lifetimeEligibleCredits:{m:1,e:15},cycleEligibleCredits:{m:1,e:15}}};expect(actionSound('prestige',ready,prestige(ready))).toBe('prestige');const axiomBase={...base,cycleINTEarned:3000,exactEconomy:{...base.exactEconomy,cycleINTEarned:{m:3,e:3}}};expect(actionSound('axiom-reset',axiomBase,axiomReset(axiomBase))).toBe('prestige')});
 it('uses the requested defaults',()=>expect(newGame(0).settings).toMatchObject({musicVolume:.25,sfxVolume:.5,hapticsEnabled:false}));
 it('requires unlock, throttles regular effects and caps concurrent effects',()=>{let now=1000;const made=Array.from({length:6},fakeAudio),create=vi.fn(()=>made.shift()!.element),p=new AudioPlayer(create,()=>now),settings=newGame(0).settings;expect(p.play('ui-click',settings)).toBe(false);p.unlock(settings);expect(p.play('ui-click',settings)).toBe(true);now+=50;expect(p.play('purchase',settings)).toBe(false);now+=100;expect(p.play('unlock',settings)).toBe(true);expect(p.play('prestige',settings)).toBe(true);expect(p.play('gem-pickup',settings)).toBe(true);expect(p.play('error',settings)).toBe(false)});
 it('creates one music instance and pauses/resumes on visibility',()=>{const sound=fakeAudio(),p=new AudioPlayer(()=>sound.element),settings={...newGame(0).settings,musicEnabled:true};p.unlock(settings);p.syncMusic(settings,true);expect(sound.play).toHaveBeenCalledTimes(2);setupDocument(true);p.handleVisibility(settings);expect(sound.pause).toHaveBeenCalled();setupDocument(false);p.handleVisibility(settings);expect(sound.play).toHaveBeenCalledTimes(3)});
});
describe('haptics',()=>{it('stays off by default and safely uses browser vibration when enabled',()=>{const vibrate=vi.fn(()=>true),nav={vibrate} as unknown as Navigator,settings=newGame(0).settings;expect(haptic('short',settings,nav)).toBe(false);expect(vibrate).not.toHaveBeenCalled();expect(haptic('double',{...settings,hapticsEnabled:true},nav)).toBe(true);expect(vibrate).toHaveBeenCalledWith([18,45,18])});it('maps purchases and prestige only after success',()=>{const base={...newGame(0),credits:1e15},bought=buyHardwareClass(base,'calculator',1);expect(actionHaptic('buy-class',base,bought)).toBe('short');expect(actionHaptic('buy-class',base,base)).toBeNull();const ready={...base,lifetimeEligibleCredits:1e15,cycleEligibleCredits:1e15,exactEconomy:{...base.exactEconomy,lifetimeEligibleCredits:{m:1,e:15},cycleEligibleCredits:{m:1,e:15}}};expect(actionHaptic('prestige',ready,prestige(ready))).toBe('strong')})});

describe('audio settings migration',()=>{it('keeps existing volumes and adds disabled haptics',async()=>{const {restore}=await import('./storage'),old=newGame(0) as any;old.settings={...old.settings,musicVolume:.37,sfxVolume:.63};delete old.settings.hapticsEnabled;const restored=restore(JSON.stringify({version:39,state:old}),0);expect(restored.error).toBeUndefined();expect(restored.state.settings).toMatchObject({musicVolume:.37,sfxVolume:.63,hapticsEnabled:false})})});
