import {describe,expect,it} from 'vitest';
import {BALANCE,axiomThresholdScientific,creditMultiplierFromAxioms,newGame,shoppingAgentUnlocked,type GameState} from './economy';
import {axiomReset,buyAxiomUpgrade,buyNode} from './prestige';
import {runAnalysisPlanner} from './experiments';
import {plannedItemCount,runCraftingPlanner} from './inventory';
import {advance} from './simulation';
import {restore,serialize} from './storage';
import {ScientificNumber} from './scientificNumber';

const withData=(amount:number)=>{const s=newGame(0);return {...s,data:amount,exactEconomy:{...s.exactEconomy,data:ScientificNumber.from(amount).toJSON()}}};
const readyReset=()=>{const s=newGame(0),amount=axiomThresholdScientific();return {...s,cycleINTEarned:amount.toNumber(),exactEconomy:{...s.exactEconomy,cycleINTEarned:amount.toJSON()}}};

describe('permanent Axiom upgrades',()=>{
 it('charges exactly one Axiom once and never reduces the permanent bonus',()=>{const base={...newGame(0),axioms:2,availableAxioms:2,totalAxiomsEarned:4},before=creditMultiplierFromAxioms(base),once=buyAxiomUpgrade(base,'anchoredShoppingAgent'),twice=buyAxiomUpgrade(once,'anchoredShoppingAgent');expect(once.availableAxioms).toBe(1);expect(twice).toBe(once);expect(once.totalAxiomsEarned).toBe(4);expect(creditMultiplierFromAxioms(once)).toBe(before)});
 it('persists ownership and planner settings through save and a real Axiom reset',()=>{let s=buyAxiomUpgrade({...readyReset(),axioms:3,availableAxioms:3,totalAxiomsEarned:3},'analysisPlanner');s={...s,analysisPlanner:{enabled:true,type:'artifact',length:'long',elapsed:7}};const loaded=restore(serialize(s),0).state,reset=axiomReset(loaded);expect(reset.axiomUpgrades).toEqual(['analysisPlanner']);expect(reset.analysisPlanner).toEqual(s.analysisPlanner)});
 it('anchors the existing shopping unlock and blocks a duplicate INT purchase',()=>{const s=buyAxiomUpgrade({...newGame(0),axioms:1,availableAxioms:1,totalAxiomsEarned:1,unspentINT:99,prestigeCount:1},'anchoredShoppingAgent');expect(shoppingAgentUnlocked(s)).toBe(true);expect(buyNode(s,'shoppingAgent')).toBe(s)});
 it('analysis planner waits for Data and never replaces a manual job',()=>{let s=buyAxiomUpgrade({...withData(0),axioms:1,availableAxioms:1,totalAxiomsEarned:1,discovered:['calculator','sbc'] as GameState['discovered']},'analysisPlanner');s={...s,analysisPlanner:{enabled:true,type:'hardware',length:'short',elapsed:0}};expect(runAnalysisPlanner(s)).toBe(s);const funded=withData(1e9),configured={...funded,axiomUpgrades:['analysisPlanner' as const],discovered:['calculator','sbc'] as GameState['discovered'],analysisPlanner:s.analysisPlanner} as GameState,started=runAnalysisPlanner(configured),occupied=runAnalysisPlanner(started);expect(started.experiments.active).not.toBeNull();expect(occupied).toBe(started)});
 it('analysis planner completes multiple contracts offline without an unbounded loop',()=>{const funded=withData(1e9),s={...funded,axiomUpgrades:['analysisPlanner' as const],discovered:['calculator','sbc'] as GameState['discovered'],analysisPlanner:{enabled:true,type:'hardware' as const,length:'short' as const,elapsed:0}} as GameState,after=advance(s,3600,false,()=>.5).state;expect(after.experiments.completedIds.length).toBeGreaterThan(1);expect(after.experiments.completedIds.length).toBeLessThan(20)});
 it('crafting planner counts equipped inventory and queued output toward its target',()=>{const item={id:'equipped',type:'impulse-relay' as const,rarity:'common' as const,level:0,locked:false,relayTaps:0},base=newGame(0),s={...base,axiomUpgrades:['craftingPlanner' as const],impulseRelayBlueprint:true,inventory:[item],equipped:{processor:'equipped'},craftingPlanner:{enabled:true,recipeId:'impulse-relay' as const,target:1 as const,elapsed:0}} as GameState;expect(plannedItemCount(s,'impulse-relay')).toBe(1);expect(runCraftingPlanner(s)).toBe(s)});
 it('crafting planner waits on ingredients/full queue and uses the regular reservation path',()=>{const base=newGame(0),configured={...base,axiomUpgrades:['craftingPlanner' as const],impulseRelayBlueprint:true,craftingPlanner:{enabled:true,recipeId:'impulse-relay' as const,target:5 as const,elapsed:0}};expect(runCraftingPlanner(configured)).toBe(configured);const funded={...configured,components:100,componentInventory:{...configured.componentInventory,circuits:100,copperCoils:100}},queued=runCraftingPlanner(funded);expect(queued.crafting.active?.recipeId).toBe('impulse-relay');expect(queued.componentInventory.circuits).toBe(88);expect(plannedItemCount(queued,'impulse-relay')).toBe(1)});
 it('does not start either automation inside the reset transaction',()=>{const s={...readyReset(),axiomUpgrades:['analysisPlanner','craftingPlanner'] as const,analysisPlanner:{enabled:true,type:'hardware' as const,length:'short' as const,elapsed:10},craftingPlanner:{enabled:true,recipeId:'impulse-relay' as const,target:5 as const,elapsed:10}} as GameState,after=axiomReset(s);expect(after.experiments.active).toBeNull();expect(after.crafting.active).toBeNull()});
});
