import {describe,expect,it} from 'vitest';
import {BALANCE,axiomThresholdScientific,addCredits,computeRate,creditMultiplierFromAxioms,creditMultiplierFromINT,creditRate,hardwareIds,newGame,passiveComponentWeights,queueResearchProject,queueTraining} from './economy';
import {axiomPreview,axiomReset,axiomReward,buyNode,prestige} from './prestige';
import {restore,serialize} from './storage';
import {ScientificNumber} from './scientificNumber';

const withCycle=(amount:ScientificNumber)=>{const s=newGame(0),number=amount.toNumber();return{...s,cycleINTEarned:number,totalINTEarned:number,unspentINT:number,exactEconomy:{...s.exactEconomy,cycleINTEarned:amount.toJSON(),totalINTEarned:amount.toJSON(),unspentINT:amount.toJSON()}}};
const withCycleINT=(amount:number)=>withCycle(ScientificNumber.from(amount));

describe('axiom layer',()=>{
 it('uses the configured square-root entitlement boundaries',()=>{const t=axiomThresholdScientific();expect(axiomReward(withCycle(t.multiplyNumber(.999)))).toBe(0);expect(axiomReward(withCycle(t))).toBe(1);expect(axiomReward(withCycle(t.multiplyNumber(3.999)))).toBe(1);expect(axiomReward(withCycle(t.multiplyNumber(4)))).toBe(2)});
 it('counts only INT actually received from normal prestige',()=>{const grant={...newGame(0),totalINTEarned:5000,unspentINT:5000};expect(axiomReward(grant)).toBe(0);const eligible=addCredits(newGame(0),1e300),gain=prestige(eligible);expect(gain.cycleINTEarned).toBeGreaterThan(0);expect(gain.cycleINTEarned).toBe(gain.unspentINT);expect(gain.totalINTEarned).toBe(gain.cycleINTEarned)});
 it('matches preview, protects double clicks, and reloads exactly once',()=>{const ready=withCycle(axiomThresholdScientific().multiplyNumber(4)),preview=axiomPreview(ready),once=axiomReset(ready);expect(once.availableAxioms).toBe(preview.availableAfter);expect(once.totalAxiomsEarned).toBe(preview.totalAfter);expect(axiomReset(once)).toBe(once);expect(restore(serialize(once),0).state.availableAxioms).toBe(2)});
 it('starts a fresh entitlement without replaying historical eligible revenue',()=>{const before={...withCycle(axiomThresholdScientific()),lifetimeEligibleCredits:1e100,cycleEligibleCredits:1e100},reset=axiomReset(before);expect(reset.cycleEligibleCredits).toBe(0);expect(reset.prestigeEntitlementClaimed).toBe(0);expect(prestige(reset)).toBe(reset)});
 it('retains collection, research, equipment, crafting and purchased labs',()=>{const base=withCycle(axiomThresholdScientific()),job={id:'c',kind:'module' as const,recipeId:'computeBus' as const,quantity:1,completed:0,durationPerUnit:30,startedAt:0,endsAt:30000,ingredients:{components:{circuits:1},modules:{},data:0,blueprints:0},result:{kind:'module' as const,id:'computeBus' as const}},state={...base,components:9,componentInventory:{...base.componentInventory,circuits:9},modules:{computeBus:2,dataLattice:1},inventory:[{id:'i',type:'quantum-chip' as const,rarity:'common' as const,level:0,locked:false}],equipped:{processor:'i'},purchasedEquipmentSlots:2,purchasedResearchLabs:2,completedResearch:['operations' as const],researchLabs:[{id:'operations' as const,level:1,startedAt:0,endsAt:100,durationSeconds:1,dataCost:1},null,null,null],crafting:{active:job,queue:[]}},after=axiomReset(state);expect(after.componentInventory).toEqual(state.componentInventory);expect(after.modules).toEqual(state.modules);expect(after.inventory).toEqual(state.inventory);expect(after.equipped).toEqual(state.equipped);expect(after.researchLabs).toEqual(state.researchLabs);expect(after.completedResearch).toEqual(state.completedResearch);expect(after.crafting).toEqual(state.crafting);expect(after.purchasedResearchLabs).toBe(2)});
 it('removes nodes and dependent queues while retaining dormant settings',()=>{let state={...withCycle(axiomThresholdScientific()),prestigeCount:1};state=buyNode(state,'shoppingAgent');state=buyNode(state,'trainingPlan');state=buyNode(state,'componentScanner');state=buyNode(state,'labs1');state=buyNode(state,'labs2');state=queueTraining(state,'quality');state=queueResearchProject(state,'operations');state={...state,discovered:['calculator','sbc'],researchQueue:['operations'],hardwareAutoBuyers:{calculator:true},scannerTarget:'circuits'};const beforeScanner=passiveComponentWeights(state),after=axiomReset(state);expect(after.nodes).toEqual([]);expect(after.trainingQueue).toEqual([]);expect(after.researchQueue).toEqual([]);expect(after.hardwareAutoBuyers.calculator).toBe(true);expect(after.scannerTarget).toBe('circuits');expect(after.credits).toBe(50);expect(after.data).toBe(0);expect(after.classUpgrades).toEqual([]);expect(after.runMilestoneEdges).toEqual([]);expect(after.activeTraining).toBeNull();expect(after.experiments.active).toBeNull();expect(after.exactEconomy.cycleEligibleCredits).toEqual({m:0,e:0});expect(passiveComponentWeights(after)[0].chance).not.toBe(beforeScanner[0].chance)});
 it('keeps the reward finite and monotonic for scientific cycle INT',()=>{const t=axiomThresholdScientific(),reward=axiomReward(withCycle(t.multiplyNumber(100)));expect(Number.isFinite(reward)).toBe(true);expect(reward).toBeGreaterThan(axiomReward(withCycle(t.multiplyNumber(4))))});
 it('separates historical INT, cycle bonus, and permanent axiom credits only',()=>{const before={...withCycle(axiomThresholdScientific()),totalINTEarned:9000,hardware:12,hardwareCounts:{...newGame(0).hardwareCounts,calculator:12}},after=axiomReset(before),loaded=restore(serialize(after),after.savedAt).state;expect(after.totalINTEarned).toBe(9000);expect(after.cycleINTEarned).toBe(0);expect(creditMultiplierFromINT(after)).toBe(1);expect(creditMultiplierFromAxioms(after)).toBe(1.5);expect(after.hardware).toBe(0);expect(hardwareIds.every(id=>after.hardwareCounts[id]===0)).toBe(true);expect(loaded.hardwareCounts.calculator).toBe(0);expect(computeRate(loaded.hardware,loaded)).toBe(0);expect(creditRate(after.hardware,after.level,after)).toBe(0);});
});

it('migrates the previous save schema into the first axiom cycle without inventing axioms',()=>{const old:any=newGame(0);delete old.availableAxioms;delete old.totalAxiomsEarned;delete old.axiomResetCount;delete old.cycleEligibleCredits;delete old.cycleINTEarned;delete old.exactEconomy.cycleEligibleCredits;delete old.exactEconomy.cycleINTEarned;old.totalINTEarned=12;old.unspentINT=12;old.lifetimeEligibleCredits=1e12;const restored=restore(JSON.stringify({version:32,state:old}),0);expect(restored.migrated).toBe(true);expect(restored.state).toMatchObject({availableAxioms:0,totalAxiomsEarned:0,axiomResetCount:0,cycleINTEarned:12,cycleEligibleCredits:1e12})});

it('keeps protected parameters while using a scientific Axiom threshold',()=>{expect(BALANCE.axiom).toEqual({threshold:{m:3,e:3},creditPerTotal:.5,resonanceCost:1,resonanceMax:10,automationCost:2,archiveCost:5});expect(BALANCE).toMatchObject({prestigeBaseRevenue:442_493_746_168,baseOfflineSeconds:28800,maxOfflineSeconds:86400})});
