import {economySnapshot} from './economySnapshot';
import {balanceContexts,balanceEvents,savedJobs,telemetryCoverage,measuredEconomy} from './balanceSnapshot';
import {TELEMETRY_LIMITS} from './telemetry';
import type { GameState } from './economy';
import { BALANCE, creditRate,computeRate,dataRate,itemTypes,newINT,researchRate,exactEconomyJSON,researchProjectDataCost } from './economy';
import { SAVE_VERSION } from './storage';

export const REPORT_VERSION=2;
export const EXPORT_VERSION=3;
export const GAME_VERSION='0.1.0';

const privateKeys=new Set(['ainame','playername','email','ipaddress','realname','account','device','deviceid','fingerprint','profile','story','settings','rawsave','fullsave','savedata','save','backup','password','token']);
function safeValue(value:unknown):unknown{
  if(typeof value==='number')return Number.isFinite(value)?value:null;
  if(Array.isArray(value))return value.map(safeValue);
  if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([key])=>!privateKeys.has(key.toLowerCase())).map(([key,item])=>[key,safeValue(item)]));
  return value;
}

export function createBalanceReport(state:GameState,exportedAt=Date.now()){
  const root=state;state=state.challengeSession?.main??state;
  const telemetry=state.telemetry,campaignDuration=telemetry.campaignStartedAt===null?null:Math.max(0,(exportedAt-telemetry.campaignStartedAt)/1000),runDuration=telemetry.runStartedAt===null?null:Math.max(0,(exportedAt-telemetry.runStartedAt)/1000);
  const allEvents=[...telemetry.permanentEvents,...telemetry.recentEvents],eventCount=(type:string)=>allEvents.filter(event=>event.type===type).length,researchSpent=allEvents.filter(event=>event.type==='research-start').reduce((sum,event)=>sum+Number(event.details.researchPointCost??0),0);
  const report={
    contexts:balanceContexts(root),reportVersion:REPORT_VERSION,gameVersion:GAME_VERSION,saveVersion:SAVE_VERSION,exportedAt,
    privacy:{localExport:true,automaticUpload:false,accountOrDeviceDataIncluded:false},
    campaign:{id:telemetry.campaignId,startedAt:telemetry.campaignStartedAt,durationSeconds:campaignDuration,historicalDataAvailable:telemetry.historicalDataAvailable},
    currentRun:{number:state.prestigeCount+1,startedAt:telemetry.runStartedAt,durationSeconds:runDuration,creditsEarned:state.runCreditsEarned},
    currentState:{
      resources:{credits:state.credits,data:state.data,researchPoints:state.researchPoints,components:{total:state.components,inventory:{...state.componentInventory}},researchFragments:state.researchFragments,blueprintFragments:state.blueprintFragments,gems:state.gems,axioms:{available:state.availableAxioms,totalEarned:state.totalAxiomsEarned,resets:state.axiomResetCount,upgrades:[...state.axiomUpgrades],upgradeLevels:{...state.axiomUpgradeLevels},analysisPlanner:{...state.analysisPlanner},craftingPlanner:{...state.craftingPlanner},prestigeAgent:{...state.prestigeAgent}}},
      hardware:{total:state.hardware,counts:{...state.hardwareCounts},classUpgrades:[...state.classUpgrades],discovered:[...state.discovered]},
      model:{level:state.level,qualityLevel:state.qualityLevel,efficiencyLevel:state.efficiencyLevel,training:state.training,activeTraining:savedJobs(state).training,trainingQueue:state.trainingQueue.map(job=>({...job}))},
      research:{completedProjects:[...state.completedResearch],breakthroughs:[...state.breakthroughs],experiments:{active:state.experiments.active,queued:[...state.experiments.queue],completedCount:state.experiments.completedIds.length}},
      items:{inventory:state.inventory.map(item=>({id:item.id,type:item.type,rarity:item.rarity,level:item.level,locked:item.locked,forge:item.forge??0,relayTaps:item.relayTaps??0})),equipped:{...state.equipped}},
      int:{totalEarned:state.totalINTEarned,historicalEarned:state.totalINTEarned,cycleEarned:state.cycleINTEarned,unspent:state.unspentINT,spent:state.spentINT,prestigeCount:state.prestigeCount,nodes:[...state.nodes],earlyUnlockSettings:{hardwareAutoBuyers:{...state.hardwareAutoBuyers},reservePercent:state.automation.reservePercent??0,scannerTarget:state.scannerTarget}},
      achievements:{claimed:[...state.achievementClaims],points:state.achievementPoints,lifetime:{...state.lifetime}},gemEconomy:{ledger:state.gemLedger.slice(-500).map(x=>({...x})),balance:state.gems,incomeBySource:Object.fromEntries(state.gemLedger.filter(x=>x.amount>0).reduce((map,x)=>map.set(x.source,(map.get(x.source)??0)+x.amount),new Map<string,number>())),spendingByOffer:Object.fromEntries(state.gemLedger.filter(x=>x.amount<0).reduce((map,x)=>map.set(x.source,(map.get(x.source)??0)-x.amount),new Map<string,number>())),permanentPurchases:{researchLabs:state.purchasedResearchLabs,offlineCapacitySeconds:state.offlineCapacitySeconds},earned:state.gemLedger.filter(x=>x.amount>0).reduce((n,x)=>n+x.amount,0),spent:-state.gemLedger.filter(x=>x.amount<0).reduce((n,x)=>n+x.amount,0),firstExtraLabAt:state.gemLedger.find(x=>x.source==='lab-slot-1')?.at??null,timeToFirstExtraLabSeconds:state.gemLedger.find(x=>x.source==='lab-slot-1')&&state.telemetry.campaignStartedAt!==null?(state.gemLedger.find(x=>x.source==='lab-slot-1')!.at-state.telemetry.campaignStartedAt)/1000:null},diagnostics:{researchPoints:{current:state.researchPoints,spentOnProjects:researchSpent,source:'Passiv aus der vollen Compute-Rate; Forschung läuft parallel. Aktuelle Projekte kosten Data; researchPointCost ist nur ein protokollierter historischer Wert.'},eventCounts:{hardwarePurchases:eventCount('hardware-purchase'),trainingStarts:eventCount('training-start'),trainingCompletions:eventCount('training-complete'),researchStarts:eventCount('research-start'),researchCompletions:eventCount('research-complete'),achievements:eventCount('achievement'),prestiges:eventCount('prestige')}},missions:{daily:state.missions.daily,weekly:state.missions.weekly,monthly:state.missions.monthly},selectedGoal:state.pinnedGoal,season:{current:state.season,previous:state.previousSeason},retentionEvents:{offlineReturns:eventCount('offline-return'),goalSelections:eventCount('goal-selected'),goalCompletions:eventCount('goal-completed'),questClaims:eventCount('mission-claim'),seasonRollovers:eventCount('season-rollover')},
    },
    prestigeHistory:telemetry.prestigeHistory,
    events:{permanent:telemetry.permanentEvents,recent:telemetry.recentEvents,challengeArchive:telemetry.challengeArchive??null},coverage:telemetryCoverage(state),jobs:savedJobs(state),economy:measuredEconomy(state),
    aggregates:{archived:telemetry.archivedMetrics,windows:telemetry.metrics},
    unavailable:telemetry.historicalDataAvailable?[]:['campaign duration before telemetry','current run start before telemetry','events before telemetry','income sources before telemetry','offline periods before telemetry'],
  };
  return safeValue(report) as typeof report;
}

export function serializeBalanceReport(state:GameState,exportedAt=Date.now()){return JSON.stringify(createBalanceReport(state,exportedAt),null,2);}

const csvCell=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;
const csv=(headers:string[],rows:unknown[][])=>[headers.map(csvCell).join(','),...rows.map(row=>row.map(csvCell).join(','))].join('\r\n');
export function createBalanceExportFiles(state:GameState,exportedAt=Date.now()):Record<string,string>{
  const root=state;state=state.challengeSession?.main??state;
  const report=createBalanceReport(root,exportedAt),events=[...state.telemetry.permanentEvents,...state.telemetry.recentEvents].sort((a,b)=>a.at-b.at);
  const timeline=balanceEvents(root).map(event=>({utc:new Date(event.at).toISOString(),context:event.context,runId:event.runId,sessionId:null,eventType:event.type,source:event.source,jobId:event.jobId,missingMeasurements:'missingMeasurements' in event?event.missingMeasurements:[],values:safeValue(event.details),resourcesAfter:safeValue(event.resources)}));
  const eventRows=timeline.map(x=>[x.utc,x.context,x.runId,x.sessionId,x.eventType,x.source,x.jobId,JSON.stringify(x.values),JSON.stringify(x.resourcesAfter)]);
  const purchases=events.filter(x=>x.type==='hardware-purchase').map(x=>[new Date(x.at).toISOString(),x.details.id,x.details.amount,x.details.unitCost??'',x.details.cost??'',x.details.creditsBefore??'',x.details.creditsAfter??'',x.details.computeBefore??'',x.details.computeAfter??'',x.details.rateBefore??'',x.details.rateAfter??'',x.details.nextMilestone??'',x.details.paybackSeconds??'',x.details.exactUnitCost??'',x.details.exactCost??'']);
  const milestones=events.filter(x=>x.type==='hardware-milestone').map(x=>[new Date(x.at).toISOString(),x.run,x.details.id,x.details.threshold,x.details.effect??'',x.details.computeBefore??'',x.details.computeAfter??'']);
  const training=events.filter(x=>x.type==='training-start'||x.type==='training-complete').map(x=>[new Date(x.at).toISOString(),x.type,x.details.track,x.details.level??'',x.details.creditCost??'',x.details.dataCost??'',x.details.baseDuration??'',x.details.effectiveRate??'',x.details.expectedDuration??'',x.details.actualDuration??'',x.details.onlineWork??'',x.details.offlineWork??'',x.jobId??'',x.details.exactDataCost??'',x.details.startedAt??'',x.details.endsAt??'',x.details.baseDataCostExact??'',x.details.trainingCostFactor??'',x.details.trainingBonusTotal??'',x.details.trainingBonusSources??'']);
  const research=events.filter(x=>x.type==='research-start'||x.type==='research-complete').map(x=>[new Date(x.at).toISOString(),x.type,x.details.id??'',x.details.labId??'',x.details.durationSeconds??'',x.details.startedAt??'',x.details.endsAt??'',x.details.actualDurationSeconds??'',x.details.creditCost??'',x.details.dataCost??'',x.details.researchPointCost??'',x.details.materials??'',x.details.breakthrough??'',x.jobId??'',x.details.exactDataCost??'']);
  const analyses=events.filter(x=>x.type==='experiment-start'||x.type==='experiment-complete'||x.type==='experiment-cancel').map(x=>[new Date(x.at).toISOString(),x.type,x.details.type??'',x.details.length??'',x.details.creditCost??'',x.details.dataCost??'',x.details.durationSeconds??'',x.details.total??'',x.details.components??'',x.details.mode??'',x.jobId??'',x.details.startedAt??'',x.details.endsAt??'']);
  const components=events.filter(x=>x.type==='component-found').map(x=>[new Date(x.at).toISOString(),x.details.source??'',x.details.mode??'',x.details.total??'',x.details.components??'',x.details.component??'',x.details.circuits??'',x.details.laser??'',x.details.titaniumBolts??'']);
  const crafting=events.filter(x=>x.type==='module-craft'||x.type==='item-craft'||x.type==='item-upgrade'||x.type==='item-equip'||x.type.startsWith('crafting_')).map(x=>[new Date(x.at).toISOString(),x.type,x.details.id??x.details.itemId??'',x.details.blueprint??x.details.type??'',x.details.rarity??'',x.details.dataCost??'',x.details.ingredients??'',x.details.component??'',x.details.componentCost??'',x.details.itemEffect??'',x.jobId??x.details.jobId??'',x.details.quantity??'',x.details.completed??'',x.details.startedAt??'',x.details.endsAt??'',x.details.exactDataCost??'',x.type==='crafting_queued'?'reservation':x.type==='crafting_completed'?'result':x.type==='crafting_cancelled'?'refund':'no additional debit']);
  const nodePurchases=events.filter(x=>x.type==='prestige-node-buy').map(x=>[new Date(x.at).toISOString(),x.details.id??'',x.details.cost??'',x.details.branch??'',x.details.depth??'',x.details.effect??'']);
  const prestigeRows=state.telemetry.prestigeHistory.map(x=>[new Date(x.at).toISOString(),x.run,x.durationSeconds,x.before.runCreditsEarned,x.intEarned,JSON.stringify(x.before.hardwareCounts),x.before.level,x.before.completedResearch.length,x.before.breakthroughs.join('|')]);
  const snapshotRows=state.telemetry.snapshots.map(x=>[x.runSeconds,x.credits,x.creditsPerSecond,x.compute,x.computePerSecond,x.users,x.data,x.dataPerSecond,x.research,x.researchPerSecond,x.gems,...Object.values(x.hardwareCounts),x.modelLevel,x.qualityLevel,x.efficiencyLevel,x.activeTraining,x.activeResearch,x.prestigeClaim,x.activeLabs]);
  const activeSeconds=state.telemetry.archivedMetrics.activeSeconds+state.telemetry.metrics.reduce((n,x)=>n+x.activeSeconds,0),offlineSeconds=state.telemetry.archivedMetrics.offlineSeconds+state.telemetry.metrics.reduce((n,x)=>n+x.offlineSeconds,0),componentSources=events.filter(x=>x.type==='component-found').reduce<Record<string,number>>((out,event)=>{const source=String(event.details.source);out[source]=(out[source]??0)+Number(event.details.total??0);return out},{});
  const diagnostics={...state.telemetry.diagnostics,build:GAME_VERSION};
  const manifest={format:'ai-singularity-local-balance',exportVersion:EXPORT_VERSION,gameVersion:GAME_VERSION,economyVersion:SAVE_VERSION,saveVersion:SAVE_VERSION,createdAt:new Date(exportedAt).toISOString(),runDurationSeconds:report.currentRun.durationSeconds,configuration:{simulationStep:BALANCE.simulationStep,offlineCap:BALANCE.maxOfflineSeconds},privacy:'local-only; no full save, player name, account, device fingerprint or automatic upload',limits:{...TELEMETRY_LIMITS,maxExportBytes:MAX_EXPORT_BYTES},coverage:report.coverage,challengeArchiveCoverage:{droppedEvents:state.telemetry.challengeArchive?.dropped??0,droppedSnapshots:state.telemetry.challengeArchive?.droppedSnapshots??null,discardedEventRange:state.telemetry.challengeArchive?.discardedEventRange??null,metricWindows:'not retained after return'}};
  const {operatingProfiles:legacyProfiles,...activeParameters}=BALANCE;
  const economy={parameters:activeParameters,compatibility:{legacyOperatingProfiles:{savedIds:Object.keys(legacyProfiles),affectsProduction:false}},coreLoop:{compute:'sum effective hardware contributions; rate, not currency',users:'full compute rate * efficiency * capacity modifiers / computePerUser',utilization:1,credits:'users * revenue per user including effective credit factors',jobs:'parallel; no hardware allocation'},scientificPrecision:{mantissa:'binary64 (~15–16 significant decimal digits)',exponent:'safe integer',exactDecimalArithmetic:false},formulas:{trainingDataCost:{base:`${BALANCE.trainingDataBase} * ${BALANCE.trainingDataGrowth}^(targetLevel - 1)`,bonus:'sum existing effective training contributions exactly once',factor:`max(${BALANCE.trainingCostFloor}, 1 / (1 + B))`,cost:'ceil(unrounded base * factor)',duration:`min(${BALANCE.trainingDurationBaseSeconds} * ${BALANCE.trainingDurationGrowth}^(targetLevel - 1), ${BALANCE.trainingDurationCapSeconds} seconds)`,fixedAtStart:true,creditCost:0},repeatableResearchDuration:`min(category.baseDuration * ${BALANCE.researchDurationGrowth}^(level - 1), ${BALANCE.researchDurationCapSeconds})`,repeatableResearchDataCost:`ceil(category.baseData * ${BALANCE.researchDataGrowth}^(level - 1))`,fixedAtStart:true,intEntitlement:{expression:'floor(sqrt(weightedEligibleRevenue / baseRevenue))',baseRevenue:BALANCE.prestigeBaseRevenue},intCreditMultiplier:{expression:`1 + ${BALANCE.prestigeBonusLogScale} * ln(1 + cycleINTEarned)`,basis:'earned cycle INT; spending does not reduce it'},intYield:{milestoneMemory:'.02 per distinct run edge, cap 1',modelSynthesis:'.03 per run training, cap 1.5',researchArchive:'.05 per run research, cap 2',insightArchive:.25},axiomReward:{expression:'floor(sqrt(cycleINTEarned / threshold))',threshold:BALANCE.axiom.threshold},axiomCreditMultiplier:{expression:'1 + creditPerTotal * totalAxiomsEarned',creditPerTotal:BALANCE.axiom.creditPerTotal},axiomUpgrades:{axiomResonance:{cost:BALANCE.axiom.resonanceCost,max:BALANCE.axiom.resonanceMax,effectPerLevel:.1},axiomAutomation:{cost:BALANCE.axiom.automationCost},axiomArchive:{cost:BALANCE.axiom.archiveCost,passiveComponentMultiplier:1.25}}},hardware:BALANCE.hardware,researchProjects:BALANCE.researchProjects,repeatableResearch:BALANCE.repeatableResearch,components:BALANCE.components,componentSources:BALANCE.componentSources,analysisCosts:BALANCE.analysisCosts,itemRecipes:BALANCE.itemRecipes,itemTypes};
  return{
    'manifest.json':JSON.stringify(manifest,null,2),'economy.json':JSON.stringify(economy,null,2),
    'summary.json':JSON.stringify(safeValue({...report,exportVersion:EXPORT_VERSION,runId:`${state.telemetry.campaignId}:${state.prestigeCount}`,time:{activeSeconds,offlineSeconds},progress:{trainingCompletions:state.lifetime.trainingCompleted,researchCompletions:state.lifetime.researchCompleted,prestiges:state.prestigeCount},production:economySnapshot(state),dataSaving:{currentData:state.data,exactEconomy:exactEconomyJSON(state),nextResearchCosts:Object.fromEntries(Object.entries(BALANCE.researchProjects).map(([id])=>[id,researchProjectDataCost(id as keyof typeof BALANCE.researchProjects)]))},componentSources,researchLevels:{...state.researchLevels},observedBlockedActions:events.filter(event=>event.type==='action-blocked').map(event=>event.details),interpretation:'observed retained events only; no inferred bottlenecks, complete history or drop rates'}),null,2),
    'events.csv':csv(['utc','context','runId','sessionId','eventType','source','jobId','values','resourcesAfter'],eventRows),'events.jsonl':timeline.map(event=>JSON.stringify(event)).join('\n'),
    'timeline.json':JSON.stringify(timeline,null,2),'timeline.csv':csv(['utc','context','runId','sessionId','eventType','source','jobId','values','resourcesAfter'],eventRows),
    'snapshots.csv':csv(['relativeRunSeconds','credits','creditsPerSecond','compute','computePerSecond','users','data','dataPerSecond','research','researchPerSecond','gems',...Object.keys(state.hardwareCounts),'modelLevel','quality','efficiency','activeTraining','activeResearch','prestigeClaim','activeLabs'],snapshotRows),
    'purchases.csv':csv(['utc','class','quantity','unitPrice','bulkCost','creditsBefore','creditsAfter','computeBefore','computeAfter','creditsPerSecondBefore','creditsPerSecondAfter','nextMilestone','paybackSeconds','scientificUnitCost','scientificBulkCost'],purchases),
    'milestones.csv':csv(['utc','run','class','owned','effect','computeBefore','computeAfter'],milestones),
    'training.csv':csv(['utc','event','track','modelLevel','creditCost','dataCost','baseDuration','effectiveRate','expectedDuration','actualDuration','onlineWork','offlineWork','jobId','scientificDataCost','startedAt','endsAt','baseDataCostExact','trainingCostFactor','trainingBonusTotal','trainingBonusSources'],training),
    'research.csv':csv(['utc','event','project','labId','durationSeconds','startedAt','endsAt','actualDurationSeconds','creditCost','dataCost','researchPoints','materials','breakthrough','jobId','scientificDataCost'],research),
    'analyses.csv':csv(['utc','event','type','length','creditCost','dataCost','durationSeconds','foundTotal','components','mode','jobId','startedAt','endsAt'],analyses),
    'components.csv':csv(['utc','source','mode','total','components','component','circuits','laser','titaniumBolts'],components),
    'crafting.csv':csv(['utc','event','id','type','rarity','dataCost','ingredients','upgradeComponent','upgradeComponentCost','itemEffect','jobId','quantity','completed','startedAt','endsAt','scientificDataCost','accounting'],crafting),
    'prestige-nodes.csv':csv(['utc','node','cost','branch','depth','effect'],nodePurchases),
    'prestige.csv':csv(['utc','run','runDuration','lifetimeCredits','intClaimed','hardware','modelLevel','researchCount','nodes'],prestigeRows),
    'sessions.csv':csv(['sessionStart','sessionEnd','activeSeconds','offlineSeconds','taps','purchases','trainings','research','prestige'],[[state.telemetry.campaignStartedAt?new Date(state.telemetry.campaignStartedAt).toISOString():'',new Date(exportedAt).toISOString(),state.lifetime.activeSeconds,state.telemetry.metrics.reduce((n,x)=>n+x.offlineSeconds,0),state.lifetime.taps,purchases.length,state.lifetime.trainingCompleted,state.lifetime.researchCompleted,state.prestigeCount]]),
    'diagnostics.json':JSON.stringify(safeValue({...diagnostics,exactEconomy:exactEconomyJSON(state),economy:measuredEconomy(state),coverage:telemetryCoverage(state),challengeArchiveCoverage:{droppedEvents:state.telemetry.challengeArchive?.dropped??0,droppedSnapshots:state.telemetry.challengeArchive?.droppedSnapshots??null,discardedEventRange:state.telemetry.challengeArchive?.discardedEventRange??null,metricWindows:'not retained after return'}}),null,2)
  };
}

export const MAX_EXPORT_BYTES=8*1024*1024;
function boundedFiles(state:GameState,at:number){const files=Object.entries(createBalanceExportFiles(state,at)),encoder=new TextEncoder();let bytes=22;for(const [name,content] of files){bytes+=encoder.encode(content).length+encoder.encode(name).length*2+76;if(bytes>MAX_EXPORT_BYTES)throw new RangeError('Balanceexport überschreitet 8 MiB / Balance export exceeds 8 MiB.');}return files;}
const crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0});
const crc32=(bytes:Uint8Array)=>{let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0};
const concat=(chunks:Uint8Array[])=>{const out=new Uint8Array(chunks.reduce((n,x)=>n+x.length,0));let offset=0;for(const chunk of chunks){out.set(chunk,offset);offset+=chunk.length;}return out;};
const header=(size:number,write:(view:DataView)=>void)=>{const bytes=new Uint8Array(size);write(new DataView(bytes.buffer));return bytes;};
export function createBalanceZip(state:GameState,exportedAt=Date.now()){const encoder=new TextEncoder(),locals:Uint8Array[]=[],central:Uint8Array[]=[],files=boundedFiles(state,exportedAt);let offset=0;for(const[name,content]of files){const fileName=encoder.encode(name),data=encoder.encode(content),crc=crc32(data),localHeader=header(30,v=>{v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x0800,true);v.setUint16(8,0,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,fileName.length,true);}),centralHeader=header(46,v=>{v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0x0800,true);v.setUint16(10,0,true);v.setUint32(16,crc,true);v.setUint32(20,data.length,true);v.setUint32(24,data.length,true);v.setUint16(28,fileName.length,true);v.setUint32(42,offset,true);});locals.push(localHeader,fileName,data);central.push(centralHeader,fileName);offset+=localHeader.length+fileName.length+data.length;}const centralData=concat(central),end=header(22,v=>{v.setUint32(0,0x06054b50,true);v.setUint16(8,files.length,true);v.setUint16(10,files.length,true);v.setUint32(12,centralData.length,true);v.setUint32(16,offset,true);});return concat([...locals,centralData,end]);}

export async function createBalanceZipAsync(state:GameState,exportedAt=Date.now(),signal?:AbortSignal,onProgress:(done:number,total:number)=>void=()=>{}){if(signal?.aborted)throw new DOMException('Export abgebrochen.','AbortError');const snapshot=structuredClone(state),files=boundedFiles(snapshot,exportedAt),encoder=new TextEncoder(),locals:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0,done=0;for(const[name,content]of files){if(signal?.aborted)throw new DOMException('Export abgebrochen.','AbortError');await new Promise<void>(resolve=>setTimeout(resolve,0));const fileName=encoder.encode(name),data=encoder.encode(content),crc=crc32(data),localHeader=header(30,v=>{v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x0800,true);v.setUint16(8,0,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,fileName.length,true);}),centralHeader=header(46,v=>{v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0x0800,true);v.setUint16(10,0,true);v.setUint32(16,crc,true);v.setUint32(20,data.length,true);v.setUint32(24,data.length,true);v.setUint16(28,fileName.length,true);v.setUint32(42,offset,true);});locals.push(localHeader,fileName,data);central.push(centralHeader,fileName);offset+=localHeader.length+fileName.length+data.length;onProgress(++done,files.length);}if(signal?.aborted)throw new DOMException('Export abgebrochen.','AbortError');const centralData=concat(central),end=header(22,v=>{v.setUint32(0,0x06054b50,true);v.setUint16(8,files.length,true);v.setUint16(10,files.length,true);v.setUint32(12,centralData.length,true);v.setUint32(16,offset,true);});return concat([...locals,centralData,end]);}

export function downloadBalanceReport(state:GameState,exportedAt=Date.now()){
  const blob=new Blob([createBalanceZip(state,exportedAt) as BlobPart],{type:'application/zip'}),url=URL.createObjectURL(blob),link=document.createElement('a');
  link.href=url;link.download=`ai-singularity-balance-${new Date(exportedAt).toISOString().replace(/[:.]/g,'-')}.zip`;link.click();URL.revokeObjectURL(url);
}
export async function downloadBalanceReportAsync(state:GameState,signal?:AbortSignal,onProgress?:(done:number,total:number)=>void,exportedAt=Date.now()){const bytes=await createBalanceZipAsync(state,exportedAt,signal,onProgress),blob=new Blob([bytes as BlobPart],{type:'application/zip'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`ai-singularity-balance-${new Date(exportedAt).toISOString().replace(/[:.]/g,'-')}.zip`;link.click();URL.revokeObjectURL(url);}
