import {type GameState, BALANCE, hardwareIds, hardwareCostScientific, researchPreview, trainingPreview, runStartContract} from './economy';
import {economySnapshot} from './economySnapshot';
import {TELEMETRY_LIMITS, type TelemetryEvent} from './telemetry';
import {ScientificNumber} from './scientificNumber';
const amount=(value:number|undefined)=>value===undefined?null:ScientificNumber.from(value).toJSON();
export function savedJobs(s:GameState){return {
 training:s.activeTraining?{track:s.activeTraining.track,costBasis:s.activeTraining.costBasis??null,workRequired:s.activeTraining.workRequired,startedAt:s.activeTraining.startedAt??null,baseDuration:s.activeTraining.baseDuration??null,onlineWork:s.activeTraining.onlineWork??null,offlineWork:s.activeTraining.offlineWork??null,cost:{credits:amount(s.activeTraining.creditCost),data:s.activeTraining.dataCostExact?ScientificNumber.fromJSON(s.activeTraining.dataCostExact).toJSON():amount(s.activeTraining.dataCost)},endsAt:s.activeTraining.startedAt===undefined?null:s.activeTraining.startedAt+s.activeTraining.workRequired*1000}:null,
 research:s.researchLabs.map((job,lab)=>job?{id:job.id,level:job.level,startedAt:job.startedAt,endsAt:job.endsAt,durationSeconds:job.durationSeconds,lab,cost:{data:job.dataCostExact?ScientificNumber.fromJSON(job.dataCostExact).toJSON():amount(job.dataCost)}}:null),
 analysis:s.experiments.active?{id:s.experiments.active.id,type:s.experiments.active.type,length:s.experiments.active.length,startedAt:s.experiments.active.startedAt,endsAt:s.experiments.active.endsAt,durationSeconds:s.experiments.active.durationSeconds??null,cost:{credits:amount(s.experiments.active.creditCost),data:amount(s.experiments.active.dataCost)}}:null,
 crafting:[s.crafting.active,...s.crafting.queue].filter(job=>job!==null).map(job=>({id:job.id,kind:job.kind,recipeId:job.recipeId,quantity:job.quantity,completed:job.completed,durationPerUnit:job.durationPerUnit,startedAt:job.startedAt,endsAt:job.endsAt,result:{kind:job.result.kind,id:job.result.id,rarity:job.result.rarity??null},ingredients:{components:job.ingredients.components,modules:job.ingredients.modules,data:job.ingredients.data,blueprints:job.ingredients.blueprints},reservation:{components:job.ingredients.components,modules:job.ingredients.modules,data:job.ingredients.data,blueprints:job.ingredients.blueprints,dataScientific:amount(job.ingredients.data)},finalEndsAt:job.endsAt===null?null:job.endsAt+(job.quantity-job.completed-1)*job.durationPerUnit*1000})),
 planned:{training:s.trainingQueue.map(job=>({...job,reserved:false})),research:s.researchQueue.map(id=>({id,reserved:false})),analysis:s.experiments.queue.map(id=>({id,reserved:false}))}
};}
export function telemetryCoverage(s:GameState){const t=s.telemetry;return {limits:TELEMETRY_LIMITS,historicalDataAvailable:t.historicalDataAvailable,droppedEvents:t.diagnostics.droppedEvents,droppedSnapshots:t.diagnostics.droppedSnapshots,discardedEventRange:t.diagnostics.discardedEventRange??null,oldestRetainedEvent:[...t.recentEvents,...t.permanentEvents].reduce<number|null>((min,event)=>min===null?event.at:Math.min(min,event.at),null),detailHistoryComplete:t.historicalDataAvailable&&t.diagnostics.droppedEvents===0&&t.diagnostics.droppedSnapshots===0,unavailable:['unrecorded intervals and pre-telemetry events','historical scientific values on legacy events without exactEconomy','main/challenge ownership of legacy events without context','past challenge metric windows and snapshots after return (event archive only)','component drop rates cannot be derived from current inventory','future stochastic finds','passive production intervals are metric aggregates, not individual booked events',...(t.diagnostics.droppedEvents>0&&!t.diagnostics.discardedEventRange?['discarded interval endpoints from older diagnostics']:[])],archivedMetricsThrough:t.archivedMetrics.through};}
export function balanceContexts(state:GameState){const entries:[string,GameState][]=[['main',state.challengeSession?.main??state]];if(state.challengeSession)entries.push(['challenge',state]);return entries.map(([context,s])=>({context,runId:s.retention.activeRun?.runId??`${s.telemetry.campaignId}:main:${s.axiomResetCount}:${s.prestigeCount}`,economy:measuredEconomy(s),jobs:savedJobs(s),coverage:telemetryCoverage(s),aggregates:{archived:s.telemetry.archivedMetrics,windows:s.telemetry.metrics,precision:'legacy native projections; scientific interval totals not recorded'},startContract:{...runStartContract(),isIncome:false,observedAt:null,meaning:'contract, not an inferred historical grant'},nextCosts:measuredEconomy(s).error?null:{hardware:Object.fromEntries(hardwareIds.map(id=>[id,hardwareCostScientific(id,s.hardwareCounts[id],s).toJSON()])),training:Object.fromEntries((['quality','efficiency'] as const).map(track=>[track,trainingPreview(s,track).cost.toJSON()])),research:Object.fromEntries([...Object.keys(BALANCE.researchProjects),...Object.keys(BALANCE.repeatableResearch)].map(id=>[id,researchPreview(s,id as Parameters<typeof researchPreview>[1])!.cost.toJSON()]))}}));}
export function balanceEvents(state:GameState){const main=state.challengeSession?.main??state;
 const wrap=(s:GameState,context:'main'|'challenge',events:TelemetryEvent[])=>events.map(event=>({...event,context:event.context??'unclassified',runId:event.runId??(context==='challenge'?s.retention.activeRun!.runId:`${s.telemetry.campaignId}:legacy:${event.run}`),source:event.source??event.details.source??event.details.action??event.type,jobId:event.jobId??event.details.jobId??null,scientificMeasurementsAvailable:!!event.resources.exactEconomy,missingMeasurements:[...(!event.resources.exactEconomy?['scientific balances']:[]),...(!event.resources.scientificRates?['scientific rates']:[]),...(!event.context?['historical main/challenge ownership']:[])]}));
 return [...wrap(main,'main',[...main.telemetry.permanentEvents,...main.telemetry.recentEvents]),...(main.telemetry.challengeArchive?.events??[]),...(state.challengeSession?wrap(state,'challenge',[...state.telemetry.permanentEvents,...state.telemetry.recentEvents]):[])].sort((a,b)=>a.at-b.at);
}

export function measuredEconomy(s:GameState){try{return {snapshot:economySnapshot(s),error:null};}catch(error){return {snapshot:null,error:error instanceof Error?error.message:"Invalid economy state"};}}
