import {describe,expect,it} from 'vitest';
import {CRASH_DIAGNOSTICS_KEY,CrashRecorder} from './crashDiagnostics';
class MemoryStorage {values=new Map<string,string>();getItem(key:string){return this.values.get(key)??null}setItem(key:string,value:string){this.values.set(key,value)}}
describe('independent crash diagnostics',()=>{
 it('survives an unexpected session and stays bounded',()=>{const storage=new MemoryStorage(),first=new CrashRecorder(storage,'run-1');for(let i=0;i<140;i++){const at=first.begin('actions',`action-${i}`);first.end('actions',`action-${i}`,at)}const raw=storage.getItem(CRASH_DIAGNOSTICS_KEY)!;expect(JSON.parse(raw).actions).toHaveLength(100);const next=new CrashRecorder(storage,'run-1');expect(next.previousUnexpected).toBe(true);expect(next.report().actions).toHaveLength(0)});
 it('marks a clean session and never propagates storage failures',()=>{const storage={getItem:()=>null,setItem:()=>{throw new Error('quota')}};expect(()=>{const recorder=new CrashRecorder(storage,'run');recorder.failure('save-failed',new Error('full'));recorder.heartbeat(4);recorder.cleanExit()}).not.toThrow()});
 it('records bounded ticks, saves, failures and telemetry sizes',()=>{const storage=new MemoryStorage(),recorder=new CrashRecorder(storage,'run');for(let i=0;i<30;i++){const tick=recorder.begin('ticks','simulation');recorder.end('ticks','simulation',tick);const save=recorder.begin('saves','autosave');recorder.end('saves','autosave',save,'ok',123)}for(let i=0;i<30;i++)recorder.failure('unknown',`failure-${i}`);recorder.counts(500,300,4567);const report=recorder.report();expect(report.ticks).toHaveLength(20);expect(report.saves).toHaveLength(20);expect(report.failures).toHaveLength(20);expect(report.telemetry).toEqual({events:500,snapshots:300,saveBytes:4567,storageSizes:undefined})});
});

it('keeps crash evidence when a corrupt primary reloads from the last valid backup',async()=>{const {newGame}=await import('./economy'),{persistGame,loadGame,SAVE_KEY}=await import('./storage');const storage=new MemoryStorage(),recorder=new CrashRecorder(storage,'run');let state={...newGame(0),credits:10};state=persistGame(storage as any,state,0).state;state=persistGame(storage as any,{...state,credits:20},0).state;recorder.failure('save-failed','simulated interruption');storage.setItem(SAVE_KEY,'{broken');const loaded=loadGame(storage as any,0),nextRecorder=new CrashRecorder(storage,'run');expect(loaded.state.credits).toBe(10);expect(loaded.error).toMatch(/Backup/);expect(nextRecorder.previousUnexpected).toBe(true);});
