import {describe,expect,it} from 'vitest';
import {compactDurableState,rotateDurableValues,SaveCoordinator} from './durableStorage';
import {newGame} from './economy';
import {restore,serialize,storageInventory,type StorageLike} from './storage';
describe('durable save generations',()=>{
 it('rotates three independent generations and every generation restores',()=>{const raws=[1,2,3,4].map(credits=>serialize({...newGame(0),credits}));let values:(string|undefined)[]=[];for(const raw of raws){const rotated=rotateDurableValues(values,raw);values=[rotated.current,...rotated.backups]}expect(values).toEqual([raws[3],raws[2],raws[1],raws[0]]);expect(values.map(raw=>restore(raw!).state.credits)).toEqual([4,3,2,1])});
 it('compacts already-grown logs before durable persistence',()=>{const state=newGame(0),snapshot={at:0,runSeconds:0,credits:0,creditsPerSecond:0,compute:0,computePerSecond:0,users:0,data:0,dataPerSecond:0,research:0,researchPerSecond:0,gems:0,hardwareCounts:{...state.hardwareCounts},modelLevel:0,qualityLevel:0,efficiencyLevel:0,activeTraining:null,activeResearch:'',prestigeClaim:0,activeLabs:0},grown={...state,telemetry:{...state.telemetry,snapshots:Array.from({length:1000},(_,i)=>({...snapshot,at:i}))}};expect(compactDurableState(grown).telemetry.snapshots).toHaveLength(300)});
 it('inventories every origin key by name and size without deleting unknown data',()=>{const values=new Map([['unrelated-user-key','secret'],['ai-singularity.save','save']]),storage:StorageLike&Pick<Storage,'length'|'key'>={get length(){return values.size},key:i=>[...values.keys()][i]??null,getItem:k=>values.get(k)??null,setItem:(k,v)=>{values.set(k,v)},removeItem:k=>{values.delete(k)}};expect(storageInventory(storage)).toEqual([{key:'ai-singularity.save',bytes:4,known:true},{key:'unrelated-user-key',bytes:6,known:false}]);expect(values.get('unrelated-user-key')).toBe('secret')});
});

describe('save coordinator',()=>{
 const deferred=<T>()=>{let resolve!:(value:T)=>void,reject!:(reason?:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no});return{promise,resolve,reject}};
 it('keeps newer in-memory progress and coalesces overlap into the latest snapshot',async()=>{let state={credits:1},active=0,maxActive=0;const writes:{credits:number}[]=[];const gates=[deferred<void>(),deferred<void>()];const coordinator=new SaveCoordinator(()=>state,async snapshot=>{active++;maxActive=Math.max(maxActive,active);writes.push({...snapshot});await gates[writes.length-1].promise;active--;return snapshot});const first=coordinator.request();await Promise.resolve();state={credits:2};const second=coordinator.request();state={credits:3};const third=coordinator.request();gates[0].resolve();await Promise.resolve();await Promise.resolve();expect(writes).toEqual([{credits:1},{credits:3}]);gates[1].resolve();await Promise.all([first,second,third]);expect(maxActive).toBe(1);expect(state.credits).toBe(3)});
 it('continues with a later successful save after a failed write',async()=>{let state={credits:4},attempt=0,persisted={credits:0};const coordinator=new SaveCoordinator(()=>state,async snapshot=>{if(attempt++===0)throw new Error('disk full');persisted={...snapshot};return persisted});await expect(coordinator.request()).rejects.toThrow('disk full');state={credits:9};await expect(coordinator.request()).resolves.toEqual({credits:9});expect(state).toEqual({credits:9});expect(persisted).toEqual({credits:9})});
 it('reloads the newest coalesced state',async()=>{let state={credits:10},raw='',release!:(value:void)=>void;const gate=new Promise<void>(resolve=>{release=resolve});let writes=0;const coordinator=new SaveCoordinator(()=>state,async snapshot=>{writes++;if(writes===1)await gate;raw=serialize({...newGame(0),credits:snapshot.credits});return snapshot});const saving=coordinator.request();await Promise.resolve();state={credits:25};void coordinator.request();release();await saving;expect(restore(raw,0).state.credits).toBe(25)});
});
