import type {GameState} from './economy';
import {advanceTo} from './simulation';
import {serialize,restore,validate,SAVE_KEY,TEMP_KEY,RECOVERY_KEY,BACKUP_KEYS,type StorageLike} from './storage';
export const DURABLE_DB='ai-singularity-durable-v1',DURABLE_STORE='saves';
export const DURABLE_KEYS=['current','backup-1','backup-2','backup-3'] as const;
export type DurableSizes={current:number;pending:number;backups:number[]};
export function rotateDurableValues(values:(string|undefined)[],snapshot:string){return{current:snapshot,backups:[values[0],values[1],values[2]] as (string|undefined)[]};}
const request=<T>(req:IDBRequest<T>)=>new Promise<T>((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error??new Error('IndexedDB request failed'))});
const completed=(tx:IDBTransaction)=>new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error??new Error('IndexedDB transaction failed'));tx.onabort=()=>reject(tx.error??new Error('IndexedDB transaction aborted'))});
export function openDurableStorage(){return new Promise<IDBDatabase>((resolve,reject)=>{if(typeof indexedDB==='undefined'){reject(new DOMException('IndexedDB ist nicht verfügbar.','NotSupportedError'));return}const req=indexedDB.open(DURABLE_DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(DURABLE_STORE))req.result.createObjectStore(DURABLE_STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error??new Error('IndexedDB open failed'))});}
export function compactDurableState(state:GameState):GameState{const t=state.telemetry;if(t.snapshots.length<=300&&t.recentEvents.length<=500&&t.permanentEvents.length<=500&&t.prestigeHistory.length<=200)return state;return{...state,telemetry:{...t,snapshots:t.snapshots.slice(-300),recentEvents:t.recentEvents.slice(-500),permanentEvents:t.permanentEvents.slice(-500),prestigeHistory:t.prestigeHistory.slice(-200)}};}
export async function persistDurableGame(state:GameState,now=Date.now()){let synchronized=compactDurableState(advanceTo(state,now).state);synchronized={...synchronized,telemetry:{...synchronized.telemetry,diagnostics:{...synchronized.telemetry.diagnostics,lastSuccessfulSave:now}}};if(!validate(synchronized))throw Object.assign(new TypeError('Der IndexedDB-Snapshot enthält ungültige Werte.'),{stage:'validate'});const snapshot=serialize(synchronized),db=await openDurableStorage();try{const readTx=db.transaction(DURABLE_STORE,'readonly'),readDone=completed(readTx),read=readTx.objectStore(DURABLE_STORE),values=await Promise.all(DURABLE_KEYS.map(key=>request(read.get(key)) as Promise<string|undefined>));await readDone;const rotated=rotateDurableValues(values,snapshot),tx=db.transaction(DURABLE_STORE,'readwrite'),done=completed(tx),store=tx.objectStore(DURABLE_STORE);store.put(snapshot,'pending');store.delete('pending');for(let i=0;i<rotated.backups.length;i++){const value=rotated.backups[i],key=DURABLE_KEYS[i+1];if(value)store.put(value,key);else store.delete(key);}store.put(rotated.current,DURABLE_KEYS[0]);await done;const verifyTx=db.transaction(DURABLE_STORE,'readonly'),verifyDone=completed(verifyTx),written=await request(verifyTx.objectStore(DURABLE_STORE).get(DURABLE_KEYS[0])) as string|undefined;await verifyDone;if(!written||restore(written,now).error)throw Object.assign(new Error('Der geschriebene IndexedDB-Save konnte nicht validiert werden.'),{stage:'verify'});return{state:synchronized,saved:true as const,bytes:snapshot.length,sizes:{current:snapshot.length,pending:0,backups:[values[0]?.length??0,values[1]?.length??0,values[2]?.length??0]} satisfies DurableSizes}}finally{db.close()}}
export async function loadDurableGame(now=Date.now()){const db=await openDurableStorage();try{const tx=db.transaction(DURABLE_STORE,'readonly'),done=completed(tx),store=tx.objectStore(DURABLE_STORE),values=await Promise.all(DURABLE_KEYS.map(key=>request(store.get(key)) as Promise<string|undefined>));await done;for(let i=0;i<values.length;i++){const raw=values[i];if(!raw)continue;const result=restore(raw,now);if(!result.error)return{...result,source:DURABLE_KEYS[i],recovered:i>0,sizes:{current:values[0]?.length??0,pending:0,backups:values.slice(1).map(x=>x?.length??0)} satisfies DurableSizes}}return null}finally{db.close()}}
export async function durableInventory(){const db=await openDurableStorage();try{const tx=db.transaction(DURABLE_STORE,'readonly'),done=completed(tx),store=tx.objectStore(DURABLE_STORE),keys=await request(store.getAllKeys()),values=await Promise.all(keys.map(key=>request(store.get(key)) as Promise<string|undefined>));await done;return keys.map((key,i)=>({key:String(key),bytes:values[i]?.length??0}))}finally{db.close()}}
export async function migrateLocalSaves(storage:StorageLike|undefined,now=Date.now()){if(!storage)return{migrated:false,archived:[] as string[]};const sourceKeys=[SAVE_KEY,...BACKUP_KEYS,TEMP_KEY,RECOVERY_KEY],entries=sourceKeys.map(key=>({key,raw:storage.getItem(key)})).filter((x):x is{key:string;raw:string}=>!!x.raw);if(!entries.length)return{migrated:false,archived:[] as string[]};const db=await openDurableStorage();try{const readTx=db.transaction(DURABLE_STORE,'readonly'),readDone=completed(readTx),existing=await request(readTx.objectStore(DURABLE_STORE).get(DURABLE_KEYS[0])) as string|undefined;await readDone;const valid=entries.map(x=>({...x,result:restore(x.raw,now)})).filter(x=>!x.result.error),tx=db.transaction(DURABLE_STORE,'readwrite'),done=completed(tx),store=tx.objectStore(DURABLE_STORE);for(const entry of entries)store.put(entry.raw,`legacy:${entry.key}`);if(!existing)for(let i=0;i<Math.min(DURABLE_KEYS.length,valid.length);i++)store.put(valid[i].raw,DURABLE_KEYS[i]);await done;const verifyTx=db.transaction(DURABLE_STORE,'readonly'),verifyDone=completed(verifyTx),verified=await Promise.all(entries.map(entry=>request(verifyTx.objectStore(DURABLE_STORE).get(`legacy:${entry.key}`)) as Promise<string|undefined>));await verifyDone;if(verified.some((raw,i)=>raw!==entries[i].raw))throw new Error('Lokale Save-Archive konnten nicht vollständig verifiziert werden.');for(const entry of entries)storage.removeItem(entry.key);return{migrated:true,archived:entries.map(x=>x.key),valid:valid.length}}finally{db.close()}}
export async function removeDurableGame(){const db=await openDurableStorage();try{const tx=db.transaction(DURABLE_STORE,'readwrite'),done=completed(tx);tx.objectStore(DURABLE_STORE).clear();await done}finally{db.close()}}
