import {describe,expect,it} from 'vitest';
import {addCredits,addData,BALANCE,componentIds,newGame,passiveComponentWeights,queueTraining,removeQueuedTraining,selectScannerTarget,type GameState} from './economy';
import {buyNode,prestige,prestigePreview} from './prestige';
import {advance} from './simulation';
import {ScientificNumber} from './scientificNumber';
import {restore,serialize} from './storage';

const withINT=(amount=3):GameState=>{const s=newGame(0);return{...s,prestigeCount:1,unspentINT:amount,totalINTEarned:amount,exactEconomy:{...s.exactEconomy,unspentINT:ScientificNumber.from(amount).toJSON(),totalINTEarned:ScientificNumber.from(amount).toJSON()}}};

describe('three early prestige unlocks',()=>{
 it('uses independent roots, exact costs, first-prestige gating, and double-click protection',()=>{for(const [id,cost] of [['shoppingAgent',1],['trainingPlan',3],['componentScanner',3]] as const){expect(BALANCE.prestigeUpgrades[id]).toMatchObject({cost,requires:[]});expect(buyNode({...withINT(cost),prestigeCount:0},id).nodes).not.toContain(id);const bought=buyNode(withINT(cost),id);expect(bought.nodes).toContain(id);expect(bought.unspentINT).toBe(0);expect(buyNode(bought,id)).toBe(bought);}});
 it('buys calculator then SBC once per ten seconds and honors a percentage reserve online and offline',()=>{let base=buyNode(withINT(3),'shoppingAgent');base=addCredits({...base,hardwareAutoBuyers:{calculator:true,sbc:true},automation:{...base.automation,reservePercent:.25}},1000);const online=advance(base,10,true).state,offline=advance(base,10,false).state;expect(online.hardwareCounts).toEqual(offline.hardwareCounts);expect(online.hardwareCounts.calculator).toBe(1);expect(online.hardwareCounts.sbc).toBe(1);expect(online.credits).toBeGreaterThanOrEqual(250);expect(advance(base,9,true).state.hardwareCounts).toEqual(base.hardwareCounts);});
 it('queues exact target levels, waits for data, preserves order, removes dependants, and reloads',()=>{let s=buyNode(withINT(3),'trainingPlan');s=queueTraining(s,'quality');s=queueTraining(s,'quality');expect(s.trainingQueue.map(x=>x.targetLevel)).toEqual([1,2]);expect(queueTraining(s,'efficiency')).toBe(s);const reloaded=restore(serialize(s),0).state;expect(reloaded.trainingQueue).toEqual(s.trainingQueue);const waiting=advance(reloaded,1,true).state;expect(waiting.activeTraining).toBeNull();expect(waiting.trainingQueue).toHaveLength(2);const funded=advance(addData(reloaded,100),1,true).state;expect(funded.activeTraining?.track).toBe('quality');expect(funded.activeTraining?.dataCost).toBe(15);expect(funded.trainingQueue[0]).toMatchObject({track:'quality',targetLevel:2});expect(removeQueuedTraining(s,0).trainingQueue).toEqual([]);});
 it('clears queued training on prestige while preserving unlock settings',()=>{let s=buyNode(withINT(3),'trainingPlan');s=queueTraining(s,'quality');s={...s,nodes:['trainingPlan','shoppingAgent','componentScanner'],hardwareAutoBuyers:{calculator:true,sbc:true},scannerTarget:'circuits',automation:{...s.automation,reservePercent:.25}};const eligible=addCredits(s,1e18),preview=prestigePreview(eligible),after=prestige(eligible);expect(preview.jobs).toContainEqual(expect.objectContaining({kind:'training',status:'cancelled',lostData:0}));expect(after.trainingQueue).toEqual([]);expect(after.nodes).toEqual(s.nodes);expect(after.hardwareAutoBuyers).toEqual(s.hardwareAutoBuyers);expect(after.automation.reservePercent).toBe(.25);expect(after.scannerTarget).toBe('circuits');});
 it('normalizes scanner chances, keeps accessible materials only, and does not add find rolls',()=>{let base={...withINT(3),discovered:['calculator','sbc'] as GameState['discovered']};base=buyNode(base,'componentScanner');const original=passiveComponentWeights(base),selected=selectScannerTarget(base,'circuits'),boosted=passiveComponentWeights(selected);expect(original.map(x=>x.id)).toEqual(componentIds.slice(0,2));expect(boosted.reduce((n,x)=>n+x.chance,0)).toBeCloseTo(1);expect(boosted.find(x=>x.id==='circuits')!.chance).toBeGreaterThan(original.find(x=>x.id==='circuits')!.chance);const a=advance(base,3600,false,()=>.9).state,b=advance(selected,3600,false,()=>.9).state;expect(a.components).toBe(b.components);expect(a.components).toBe(2);});
});
