import {BALANCE, type GameState, hardwareIds, classComputeScientific, classComputeTerms, milestoneFactor, hardwareMasteryBonus, computeFactors, usersFactors, creditFactors, dataBonusTerms, dataRawBonusScientific, dataMultiplierScientific, baseDataRateScientific, computeRateScientific, usersRateScientific, creditRateScientific, dataRateScientific, researchRateScientific, profileShares, milestoneBonus, equippedBonus, itemCombinationBonus,itemSynergyExponent,milestoneSynergy, exactEconomyJSON, scientificProduct} from './economy';
import {ScientificNumber} from './scientificNumber';
const scientific=(values:Record<string,number|ScientificNumber>)=>Object.fromEntries(Object.entries(values).map(([id,value])=>[id,(typeof value==='number'?ScientificNumber.from(value):value).toJSON()]));
/** Instantaneous rates, not an interval forecast (lifetime Data synergy changes over time).
 * Factors are the same operands, in the same order, used by the production functions.
 */
export function economySnapshot(s:GameState,now=s.savedAt){
 const hardware=hardwareIds.map(id=>({id,count:s.hardwareCounts[id],basePerUnit:BALANCE.hardware[id].compute,terms:classComputeTerms(s,id),milestoneFactor:milestoneFactor(id,s.hardwareCounts[id]),classUpgrade:s.classUpgrades.includes(id)?2:1,mastery:1+hardwareMasteryBonus(s,id),compute:classComputeScientific(s,id).toJSON()}));
 const raw=hardwareIds.reduce((sum,id)=>sum.add(classComputeScientific(s,id)),ScientificNumber.zero()),compute=computeRateScientific(s.hardware,s),users=usersRateScientific(s),credit=creditRateScientific(s.hardware,s.level,s,now),data=dataRateScientific(s),rawBonus=dataRawBonusScientific(s),dataMultiplier=dataMultiplierScientific(rawBonus);
 return{at:now,balances:exactEconomyJSON(s),hardware,compute:{base:raw.toJSON(),additiveFactorTerms:{items:equippedBonus(s,'compute'),milestoneCompute:milestoneBonus(s,'compute'),milestoneGlobal:milestoneBonus(s,'synergy')},factors:scientific(computeFactors(s)),rate:compute.toJSON()},users:{inferenceShare:profileShares(s).inference,base:compute.multiplyNumber(profileShares(s).inference).toJSON(),factors:scientific(usersFactors(s)),rate:users.toJSON()},credits:{base:users.toJSON(),itemPower:{base:1+equippedBonus(s,'credits')+itemCombinationBonus(s,'credits'),exponent:itemSynergyExponent(s)*milestoneSynergy(s).itemExponent},factors:scientific(creditFactors(s,now)),rate:credit.toJSON()},data:{base:baseDataRateScientific(users).toJSON(),userExponent:.5,additiveBonuses:scientific(dataBonusTerms(s)),rawBonus:rawBonus.toJSON(),compression:{scale:BALANCE.dataBonusScale,expression:'1 + raw * scale / (raw + scale)',cap:4.999999999999999},factors:scientific({compressedBonus:dataMultiplier,challenge:s.retention.activeRun?.id==='data-crunch'?.1:1}),rate:data.toJSON()},research:{rate:researchRateScientific(s,now).toJSON()},semantics:{factors:'multiply in listed order; effective exponentiated factors already evaluated',dataBonuses:'add before compression; never multiply each bonus',hardware:'sum class compute; class compute includes additive compute-network links'},reconstructed:{compute:scientificProduct(raw,...Object.values(computeFactors(s))).toJSON(),credits:scientificProduct(users,...Object.values(creditFactors(s,now))).toJSON()}};
}
