import {specialItemEffectText} from './specialItemText';
import {useEffect,useRef,useState} from 'react';
import {BALANCE,computeRate,dataRate,equipmentSlotCount,equipmentSlots,exactEconomyValue,formatScientific,deepPrestigeBonus,itemEffectFor,itemEffectProfile,itemTypes,type GameState,type ItemSlot} from './economy';
import {creditRate} from './economy';
import {ScientificNumber} from './scientificNumber';
import {ItemArt} from './GameArt';
import {effectText,itemText,rarityText} from './gameplayI18n';

type Action=(name:string,...args:any[])=>void;
const slotName=(slot:ItemSlot,de:boolean)=>de?({processor:'Prozessor',core:'Kern',research:'Forschung'}[slot]):({processor:'Processor',core:'Core',research:'Research'}[slot]);
export const equipmentEffectCopy=(s:GameState,item:GameState['inventory'][number])=>specialItemEffectText(s,item)??itemEffectProfile(item).map(effect=>`${effectText(effect,s.settings.language)}${effect==='training'?' (B)':''} +${(itemEffectFor(s,item,effect)*(1+deepPrestigeBonus(s,'manufacturing'))*100).toFixed(1)} %`).join(' · ');
export function equipmentPreview(s:GameState,id:string){const item=s.inventory.find(entry=>entry.id===id);if(!item)return null;const slot=itemTypes[item.type].slot,next={...s,equipped:{...s.equipped,[slot]:id}};return{before:{credits:creditRate(s.hardware,s.level,s,s.savedAt),compute:computeRate(s.hardware,s),data:dataRate(s)},after:{credits:creditRate(next.hardware,next.level,next,next.savedAt),compute:computeRate(next.hardware,next),data:dataRate(next)},state:next};}
export function EquipmentDialog({s,act,onClose}:{s:GameState;act:Action;onClose:()=>void}){
 const de=s.settings.language==='de',[selected,setSelected]=useState<ItemSlot>('processor'),close=useRef<HTMLButtonElement>(null),count=equipmentSlotCount(s),costFor=(target:2|3)=>ScientificNumber.from(BALANCE.equipmentSlotCosts[target-2]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';close.current?.focus();const key=(event:KeyboardEvent)=>event.key==='Escape'&&onClose();addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;removeEventListener('keydown',key);previous?.focus()}},[onClose]);
 const currentId=s.equipped[selected],current=s.inventory.find(item=>item.id===currentId),compatible=s.inventory.filter(item=>itemTypes[item.type].slot===selected);
 return <div className="equipment-backdrop" onPointerDown={event=>event.target===event.currentTarget&&onClose()}><section className="equipment-dialog mobile-equipment" role="dialog" aria-modal="true" aria-labelledby="equipment-title"><header><div><small>{s.aiName??'AURA'} · Q{s.qualityLevel} / E{s.efficiencyLevel}</small><h2 id="equipment-title">{de?'KI-Ausrüstung':'AI Equipment'}</h2></div><button ref={close} aria-label={de?'Ausrüstung schließen':'Close equipment'} onClick={onClose}>×</button></header><div className="visual-equipment-slots">{equipmentSlots.map((slot,index)=>{const unlocked=index<count,item=s.inventory.find(entry=>entry.id===s.equipped[slot]),target=(index+1) as 1|2|3,cost=target>1?costFor(target as 2|3):null;return <button className={`${selected===slot?'selected ':''}${unlocked?'':'locked'}`} key={slot} onClick={()=>unlocked&&setSelected(slot)} disabled={!unlocked&&target!==count+1}>{item?<ItemArt type={item.type}/>:<span className="slot-orb">{unlocked?'＋':'🔒'}</span>}<b>{slotName(slot,de)}</b>{unlocked?<small>{item?itemText(item.type,s.settings.language):(de?'Leer':'Empty')}</small>:<small>{target===1?(de?'Nach Prestige I':'After Prestige I'):formatScientific(cost!,1,s.settings.numberFormat)+' C'}</small>}{!unlocked&&target===count+1&&target>1&&<i onClick={event=>{event.stopPropagation();act('equipment-slot',target)}}>{de?'Freischalten':'Unlock'}</i>}</button>})}</div><section className="equipment-picker"><div className="equipment-picker-title"><div><small>{slotName(selected,de)}</small><h3>{current?(de?'Ausgerüstet':'Equipped'):(de?'Item wählen':'Choose item')}</h3></div>{current&&<button onClick={()=>act('unequip',selected)}>{de?'Ablegen':'Unequip'}</button>}</div><div>{compatible.length===0&&<div className="compact-empty"><b>{de?'Kein passendes Item':'No compatible item'}</b><small>{de?'Finde Items durch Analysen oder Crafting.':'Find items through analyses or crafting.'}</small></div>}{compatible.map(item=>{const equipped=Object.values(s.equipped).includes(item.id);return <article className={`rarity-${item.rarity}`} key={item.id}><ItemArt type={item.type}/><div><b>{itemText(item.type,s.settings.language)}</b><small>{rarityText(item.rarity,s.settings.language)} · Lv {item.level}</small><p>{equipmentEffectCopy(s,item)}</p></div><button disabled={equipped} onClick={()=>act('equip',item.id)}>{equipped?'✓':de?'Anlegen':'Equip'}</button></article>})}</div></section></section></div>;
}
