import {BALANCE,GameState,grantComponents,startQueuedTrainingIfAffordable,trainingRate} from './economy';
import {settleCrafting} from './inventory';
import {addEvent} from './telemetry';
export type GemOfferId='components'|'training-boost'|'lab-slot-1'|'lab-slot-2'|'offline-12'|'offline-16'|'offline-24'|'craft-30m'|'craft-4h'|'training-15m'|'training-1h'|'materials-circuits'|'materials-advanced'|'lab-boost';
export const nativeGemProducts=[{id:'ai_singularity.gems.100',gems:100},{id:'ai_singularity.gems.550',gems:550},{id:'ai_singularity.gems.1200',gems:1200}] as const;
export type GemOffer={id:GemOfferId;section:'permanent'|'time'|'materials';icon:'research'|'time'|'craft'|'training'|'components';name:{de:string;en:string};effect:{de:string;en:string};permanent?:boolean};
export const gemOffers:GemOffer[]=[
 {id:'lab-slot-1',section:'permanent',icon:'research',name:{de:'Labor 3',en:'Lab 3'},effect:{de:'Ein zusätzlicher Laborplatz',en:'One additional lab slot'},permanent:true},{id:'lab-slot-2',section:'permanent',icon:'research',name:{de:'Labor 4',en:'Lab 4'},effect:{de:'Ein zusätzlicher Laborplatz',en:'One additional lab slot'},permanent:true},
 {id:'offline-12',section:'permanent',icon:'time',name:{de:'12 Stunden offline',en:'12 hours offline'},effect:{de:'Dauerhafte Offline-Kapazität',en:'Permanent offline capacity'},permanent:true},{id:'offline-16',section:'permanent',icon:'time',name:{de:'16 Stunden offline',en:'16 hours offline'},effect:{de:'Dauerhafte Offline-Kapazität',en:'Permanent offline capacity'},permanent:true},{id:'offline-24',section:'permanent',icon:'time',name:{de:'24 Stunden offline',en:'24 hours offline'},effect:{de:'Dauerhafte Offline-Kapazität',en:'Permanent offline capacity'},permanent:true},
 {id:'lab-boost',section:'time',icon:'research',name:{de:'Laborbonus · 60 Min.',en:'Lab boost · 60 min'},effect:{de:'Bestehender Bonus: Forschung läuft doppelt',en:'Existing boost: research runs twice as fast'}},{id:'craft-30m',section:'time',icon:'craft',name:{de:'Crafting −30 Min.',en:'Crafting −30 min'},effect:{de:'Nur der aktive Auftrag',en:'Active job only'}},{id:'craft-4h',section:'time',icon:'craft',name:{de:'Crafting −4 Std.',en:'Crafting −4 h'},effect:{de:'Nur der aktive Auftrag',en:'Active job only'}},{id:'training-15m',section:'time',icon:'training',name:{de:'Training −15 Min.',en:'Training −15 min'},effect:{de:'Nur das aktive Training',en:'Active training only'}},{id:'training-1h',section:'time',icon:'training',name:{de:'Training −1 Std.',en:'Training −1 h'},effect:{de:'Nur das aktive Training',en:'Active training only'}},
 {id:'materials-circuits',section:'materials',icon:'components',name:{de:'50 Schaltkreise',en:'50 circuits'},effect:{de:'Direkt in den Komponentenbestand',en:'Added to component inventory'}},{id:'materials-advanced',section:'materials',icon:'components',name:{de:'Spulen- & Waferpaket',en:'Coil & wafer pack'},effect:{de:'10 Kupferspulen + 10 Siliziumwafer',en:'10 copper coils + 10 silicon wafers'}}];
const offlineHours=(id:GemOfferId)=>id==='offline-12'?12:id==='offline-16'?16:id==='offline-24'?24:0;
const duration=(id:GemOfferId)=>id==='craft-30m'?BALANCE.gemShop.crafting[0]:id==='craft-4h'?BALANCE.gemShop.crafting[1]:id==='training-15m'?BALANCE.gemShop.training[0]:id==='training-1h'?BALANCE.gemShop.training[1]:null;
export type GemQuote={cost:number;enabled:boolean;reason?:string;remainingSeconds?:number;appliedSeconds?:number;owned?:boolean};
export function gemOfferQuote(s:GameState,id:GemOfferId):GemQuote{let cost=0,enabled=true,reason:string|undefined,remainingSeconds:number|undefined,appliedSeconds:number|undefined,owned=false;
 if(id==='lab-slot-1'||id==='lab-slot-2'){const index=id==='lab-slot-1'?0:1;cost=BALANCE.gemShop.labSlots[index];owned=s.purchasedResearchLabs>index;if(owned){enabled=false;reason='owned'}else if(!s.nodes.includes('labs1')){enabled=false;reason='prestige-lab'}else if(s.purchasedResearchLabs!==index){enabled=false;reason='previous'};}
 else if(offlineHours(id)){const hours=offlineHours(id),tier=BALANCE.gemShop.offline.find(x=>x.hours===hours)!;cost=tier.cost;owned=s.offlineCapacitySeconds>=hours*3600;if(owned){enabled=false;reason='owned'}else{const previous=hours===12?8:hours===16?12:16;if(s.offlineCapacitySeconds<previous*3600){enabled=false;reason='previous'}}}
 else if(id.startsWith('craft-')){const d=duration(id)!;remainingSeconds=Math.max(0,((s.crafting.active?.endsAt??s.savedAt)-s.savedAt)/1000);appliedSeconds=Math.min(d.seconds,remainingSeconds);cost=Math.ceil(d.cost*appliedSeconds/d.seconds);if(!s.crafting.active||remainingSeconds<=0){enabled=false;reason='no-crafting'}}
 else if(id.startsWith('training-')){const d=duration(id)!,rate=trainingRate(s.hardware,s,s.savedAt);remainingSeconds=s.activeTraining?Math.max(0,s.activeTraining.workRequired-s.training)/Math.max(rate,1e-12):0;appliedSeconds=Math.min(d.seconds,remainingSeconds);cost=Math.ceil(d.cost*appliedSeconds/d.seconds);if(!s.activeTraining||remainingSeconds<=0){enabled=false;reason='no-training'}}
 else if(id==='materials-circuits')cost=BALANCE.gemShop.materials.circuits.cost;
 else if(id==='materials-advanced'){cost=BALANCE.gemShop.materials.advanced.cost;if(!s.discovered.includes('pc')){enabled=false;reason='locked-materials'}}
 else if(id==='lab-boost'){cost=BALANCE.gemShop.labBoost[0];const remaining=Math.max(0,s.labBoostUntil-s.savedAt);if(remaining>=BALANCE.gemShop.boostCap*1000){enabled=false;reason='cap'}}
 if(enabled&&s.gems<cost){enabled=false;reason='gems'}return{cost,enabled:s.retention.activeRun?false:enabled,reason:s.retention.activeRun?'challenge':reason,remainingSeconds,appliedSeconds,owned};}
function spend(s:GameState,id:GemOfferId,cost:number,now:number,apply:(s:GameState)=>GameState){const purchase=`${id}:${now}`;if(cost<=0||s.gems<cost||s.processedGemPurchases.includes(purchase))return s;const granted=apply(s);if(granted===s)return s;return addEvent({...granted,gems:s.gems-cost,processedGemPurchases:[...s.processedGemPurchases,purchase],gemLedger:[...s.gemLedger,{id:purchase,at:now,amount:-cost,source:id}]},'gem-purchase',now,{offer:id,cost});}
export function buyGemOffer(s:GameState,id:GemOfferId,now=s.savedAt){if(id==='training-boost')return s;if(id==='components')id='materials-circuits';const q=gemOfferQuote(s,id);if(!q.enabled)return s;
 if(id==='lab-slot-1'||id==='lab-slot-2')return spend(s,id,q.cost,now,x=>({...x,purchasedResearchLabs:x.purchasedResearchLabs+1}));
 const hours=offlineHours(id);if(hours)return spend(s,id,q.cost,now,x=>({...x,offlineCapacitySeconds:Math.max(x.offlineCapacitySeconds,hours*3600)}));
 if(id.startsWith('craft-'))return spend(s,id,q.cost,now,x=>{const active=x.crafting.active;if(!active||active.endsAt===null)return x;return settleCrafting({...x,crafting:{...x.crafting,active:{...active,endsAt:Math.max(x.savedAt,active.endsAt-(q.appliedSeconds??0)*1000)}}})});
 if(id.startsWith('training-'))return spend(s,id,q.cost,now,x=>{const active=x.activeTraining;if(!active)return x;const rate=trainingRate(x.hardware,x,x.savedAt),work=Math.min(active.workRequired-x.training,(q.appliedSeconds??0)*rate),training=x.training+work;if(training+1e-7<active.workRequired)return{...x,training};const track=active.track,completed=addEvent({...x,training:0,activeTraining:null,level:x.level+1,qualityLevel:x.qualityLevel+(track==='quality'?1:0),efficiencyLevel:x.efficiencyLevel+(track==='efficiency'?1:0),runTrainingCompleted:x.runTrainingCompleted+1,lifetime:{...x.lifetime,trainingCompleted:x.lifetime.trainingCompleted+1}},'training-complete',x.savedAt,{track,level:x.level+1,source:'gem-shop'});return startQueuedTrainingIfAffordable(completed)});
 if(id==='materials-circuits')return spend(s,id,q.cost,now,x=>grantComponents(x,{circuits:BALANCE.gemShop.materials.circuits.amount}));
 if(id==='materials-advanced')return spend(s,id,q.cost,now,x=>grantComponents(x,{copperCoils:BALANCE.gemShop.materials.advanced.copperCoils,siliconWafers:BALANCE.gemShop.materials.advanced.siliconWafers}));
 const [cost,seconds]=BALANCE.gemShop.labBoost;return spend(s,id,cost,now,x=>({...x,labBoostUntil:now+Math.min(BALANCE.gemShop.boostCap*1000,Math.max(0,x.labBoostUntil-now)+seconds*1000)}));}
