import {describe,expect,it} from 'vitest';import {BALANCE,componentTotal,newGame,researchLabCount,startTraining} from './economy';import {buyGemOffer,gemOfferQuote,nativeGemProducts} from './gemShop';import {craftModule} from './inventory';import {advance} from './simulation';import {axiomReset,prestige} from './prestige';import {restore,serialize} from './storage';
describe('central gem offer catalog',()=>{
 it('buys labs at 500/1500 once, respects limits, reload and both prestige resets',()=>{let s={...newGame(0),gems:7000,nodes:['labs1'],lifetimeEligibleCredits:1e15,cycleEligibleCredits:1e15,cycleINTEarned:3000,totalINTEarned:3000,exactEconomy:{...newGame(0).exactEconomy,cycleINTEarned:{m:3,e:3}}};s=buyGemOffer(s,'lab-slot-1',1);expect(s.gems).toBe(6500);s=buyGemOffer(s,'lab-slot-2',2);expect(s.gems).toBe(5000);expect(researchLabCount(s)).toBe(4);expect(buyGemOffer(s,'lab-slot-2',3)).toBe(s);s=buyGemOffer(s,'offline-12',4);s=buyGemOffer(s,'offline-16',5);s=buyGemOffer(s,'offline-24',6);expect(restore(serialize(s)).state.purchasedResearchLabs).toBe(2);expect(prestige(s)).toMatchObject({purchasedResearchLabs:2,offlineCapacitySeconds:86400});expect(axiomReset(s)).toMatchObject({purchasedResearchLabs:2,offlineCapacitySeconds:86400})});
 it('upgrades offline capacity in order without retroactive credit',()=>{let s={...newGame(0),gems:2000,credits:77};expect(buyGemOffer(s,'offline-16',1)).toBe(s);s=buyGemOffer(s,'offline-12',2);expect(s.offlineCapacitySeconds).toBe(12*3600);expect(s.credits).toBe(77);s=buyGemOffer(s,'offline-16',3);expect(s.offlineCapacitySeconds).toBe(16*3600)});
 it('charges proportional rounded crafting cost and completes one active job once',()=>{const b=newGame(0),prepared={...b,gems:100,completedResearch:['blueprints' as const],data:1000,componentInventory:{...b.componentInventory,circuits:20,copperCoils:6,siliconWafers:4,titaniumBolts:4},components:34},queued=craftModule(prepared,'computeBus'),remaining=(queued.crafting.active!.endsAt!-queued.savedAt)/1000,quote=gemOfferQuote(queued,'craft-4h');expect(quote.cost).toBe(Math.ceil(120*remaining/14400));const bought=buyGemOffer(queued,'craft-4h',queued.savedAt);expect(bought.modules.computeBus).toBe(1);const gems=bought.gems;expect(buyGemOffer(bought,'craft-4h',bought.savedAt).gems).toBe(gems)});
 it('shortens only active training, rounds its cost, and completes exactly once',()=>{let s=startTraining({...newGame(0),gems:100,data:1000},'quality'),q=gemOfferQuote(s,'training-1h');expect(q.cost).toBeLessThanOrEqual(45);s=buyGemOffer(s,'training-1h',s.savedAt);expect(s.qualityLevel).toBe(1);expect(s.lifetime.trainingCompleted).toBe(1);expect(buyGemOffer(s,'training-1h',s.savedAt)).toBe(s)});
 it('checks gems, material unlocks and canonical component totals',()=>{let s={...newGame(0),gems:29};expect(buyGemOffer(s,'materials-circuits',0)).toBe(s);s={...s,gems:100};const circuits=buyGemOffer(s,'materials-circuits',1);expect(circuits.componentInventory.circuits).toBe(50);expect(circuits.components).toBe(componentTotal(circuits.componentInventory));expect(buyGemOffer(s,'materials-advanced',2)).toBe(s);const advanced=buyGemOffer({...s,discovered:['calculator','sbc','pc']},'materials-advanced',2);expect(advanced.componentInventory.copperCoils).toBe(10);expect(advanced.componentInventory.siliconWafers).toBe(10);expect(advanced.components).toBe(20)});
 it('uses the prepared product ids without payment functions',()=>expect(nativeGemProducts.map(x=>x.id)).toEqual(['ai_singularity.gems.100','ai_singularity.gems.550','ai_singularity.gems.1200']));
});
