export const languages=['en','de','es','fr','pt','it','pl'] as const;
export type Language=typeof languages[number];
export type NumberFormat='auto'|'scientific'|'engineering';
export const languageNames:Record<Language,string>={en:'English',de:'Deutsch',es:'Español',fr:'Français',pt:'Português',it:'Italiano',pl:'Polski'};
const en={profile:'Profile',collection:'Collection',challenges:'Challenges',seasons:'Seasons',stats:'Stats',inbox:'Inbox',settings:'Settings',playerProfile:'Player Profile',showcase:'Showcase',noArtifact:'No Season Artifact yet',seasonHistory:'Season History',active:'active',language:'Language',numberFormat:'Number format',animations:'Animations / FX',music:'Music',muteEffects:'Mute effects',playerName:'Player name',daily:'Daily',weekly:'Weekly',monthly:'Monthly',quests:'Quests',claim:'Claim',running:'Running',season:'Season',neuralSeason:'30-DAY NEURAL SEASON',level:'Level',artifact:'Artifact',hardwareMastery:'Hardware Mastery',challengeStars:'Challenge Stars',accountChallenges:'Account Challenges',challengeRuns:'Challenge Runs',start:'Start',abort:'Abort',completeChallenge:'Complete challenge',notReady:'Not ready',goal:'Goal',lifetimeCredits:'Lifetime Credits',prestiges:'Prestiges',hardwareBought:'Hardware bought',taps:'Taps',components:'Components',research:'Research',items:'Items',activeTime:'Active time',markRead:'Mark as read',hardwareDiscovered:'Hardware discovered',componentsDiscovered:'Components discovered',itemTypes:'Item types',artifacts:'Artifacts',unlockAt500:'Unlock at 500 units',workshop:'Workshop',inventory:'Inventory',prestige:'Prestige',missions:'Missions'};
type Key=keyof typeof en;
const de:Partial<Record<Key,string>>={profile:'Profil',collection:'Sammlung',challenges:'Challenges',seasons:'Seasons',stats:'Statistik',inbox:'Nachrichten',settings:'Einstellungen',playerProfile:'Spielerprofil',showcase:'Vitrine',noArtifact:'Noch kein Season-Artefakt',seasonHistory:'Season-Verlauf',active:'aktiv',language:'Sprache',numberFormat:'Zahlenformat',animations:'Animationen / FX',music:'Musik',muteEffects:'Effekte stumm',playerName:'Spielername',daily:'Täglich',weekly:'Wöchentlich',monthly:'Monatlich',quests:'Quests',claim:'Abholen',running:'Läuft',season:'Season',neuralSeason:'30-TAGE NEURAL SEASON',level:'Level',artifact:'Artefakt',hardwareMastery:'Hardware-Mastery',challengeStars:'Challenge-Sterne',accountChallenges:'Account-Challenges',challengeRuns:'Challenge-Runs',start:'Start',abort:'Abbrechen',completeChallenge:'Challenge abschließen',notReady:'Noch nicht bereit',goal:'Ziel',lifetimeCredits:'Lifetime Credits',prestiges:'Prestiges',hardwareBought:'Hardware gekauft',taps:'Taps',components:'Komponenten',research:'Forschungen',items:'Items',activeTime:'Aktive Zeit',markRead:'Als gelesen markieren',hardwareDiscovered:'Hardware entdeckt',componentsDiscovered:'Komponenten entdeckt',itemTypes:'Item-Typen',artifacts:'Artefakte',unlockAt500:'500 Einheiten zum Freischalten',workshop:'Werkstatt',inventory:'Inventar',prestige:'Prestige',missions:'Missionen'};
const es:Partial<Record<Key,string>>={profile:'Perfil',collection:'Colección',challenges:'Desafíos',seasons:'Temporadas',stats:'Estadísticas',inbox:'Mensajes',settings:'Ajustes',language:'Idioma',numberFormat:'Formato numérico',daily:'Diario',weekly:'Semanal',monthly:'Mensual',quests:'Misiones',claim:'Reclamar',running:'En curso',workshop:'Taller',research:'Investigación',inventory:'Inventario',prestige:'Prestigio',missions:'Misiones'};
const fr:Partial<Record<Key,string>>={profile:'Profil',collection:'Collection',challenges:'Défis',seasons:'Saisons',stats:'Statistiques',inbox:'Messages',settings:'Réglages',language:'Langue',numberFormat:'Format des nombres',daily:'Quotidien',weekly:'Hebdo',monthly:'Mensuel',quests:'Quêtes',claim:'Récupérer',running:'En cours',workshop:'Atelier',research:'Recherche',inventory:'Inventaire',prestige:'Prestige',missions:'Missions'};
const pt:Partial<Record<Key,string>>={profile:'Perfil',collection:'Coleção',challenges:'Desafios',seasons:'Temporadas',stats:'Estatísticas',inbox:'Mensagens',settings:'Definições',language:'Idioma',numberFormat:'Formato numérico',daily:'Diário',weekly:'Semanal',monthly:'Mensal',quests:'Missões',claim:'Resgatar',running:'Em curso',workshop:'Oficina',research:'Pesquisa',inventory:'Inventário',prestige:'Prestígio',missions:'Missões'};
const it:Partial<Record<Key,string>>={profile:'Profilo',collection:'Collezione',challenges:'Sfide',seasons:'Stagioni',stats:'Statistiche',inbox:'Messaggi',settings:'Impostazioni',language:'Lingua',numberFormat:'Formato numeri',daily:'Giornaliero',weekly:'Settimanale',monthly:'Mensile',quests:'Missioni',claim:'Riscatta',running:'In corso',workshop:'Officina',research:'Ricerca',inventory:'Inventario',prestige:'Prestigio',missions:'Missioni'};
const pl:Partial<Record<Key,string>>={profile:'Profil',collection:'Kolekcja',challenges:'Wyzwania',seasons:'Sezony',stats:'Statystyki',inbox:'Wiadomości',settings:'Ustawienia',language:'Język',numberFormat:'Format liczb',daily:'Dzienne',weekly:'Tygodniowe',monthly:'Miesięczne',quests:'Misje',claim:'Odbierz',running:'W toku',workshop:'Warsztat',research:'Badania',inventory:'Ekwipunek',prestige:'Prestiż',missions:'Misje'};
const dictionaries={en,de,es,fr,pt,it,pl};
export const t=(language:Language,key:Key)=>dictionaries[language][key]??en[key];
export const localeFor=(language:Language)=>({en:'en-US',de:'de-DE',es:'es-ES',fr:'fr-FR',pt:'pt-PT',it:'it-IT',pl:'pl-PL'} as const)[language];
export function formatLocalized(value:number,language:Language,format:NumberFormat='auto',digits=0){if(!Number.isFinite(value))return '∞';if(format==='scientific'||(format==='auto'&&Math.abs(value)>=1e15))return value.toExponential(Math.max(0,Math.min(3,digits||2)));if(format==='engineering'&&value!==0){const e=Math.floor(Math.log10(Math.abs(value))/3)*3;return `${(value/10**e).toLocaleString(localeFor(language),{maximumFractionDigits:2})}e${e}`;}return value.toLocaleString(localeFor(language),{maximumFractionDigits:digits});}
