import {describe,expect,it} from 'vitest';
import {BALANCE,creditRateScientific,exactEconomyValue,newGame,registerTap,tapCreditsScientific} from './economy';
import {completeExperiment,queueExperiment} from './experiments';
import {craft,craftAffordability,equip,createItem} from './inventory';
import {advance} from './simulation';
import {restore,serialize} from './storage';
import {prestige} from './prestige';
import {ScientificNumber} from './scientificNumber';

const analysisReady=()=>({...newGame(0),discovered:['calculator','sbc'] as ('calculator'|'sbc')[],data:1e6,exactEconomy:{...newGame(0).exactEconomy,data:ScientificNumber.from(1e6).toJSON()}});
const relayReady=()=>{const base={...newGame(0),impulseRelayBlueprint:true,componentInventory:{...newGame(0).componentInventory,circuits:12,copperCoils:2},components:14};return base;};
describe('Impulsrelais',()=>{
 it('unlocks its blueprint only when a real hardware analysis completes',()=>{const base=analysisReady(),started=queueExperiment(base,'hardware',0,'short');expect(started.impulseRelayBlueprint).toBe(false);expect(completeExperiment(started,started.experiments.active!.endsAt-1,()=>.5).impulseRelayBlueprint).toBe(false);expect(completeExperiment(started,started.experiments.active!.endsAt,()=>.5).impulseRelayBlueprint).toBe(true);});
 it('subtracts exact ingredients and completes after five elapsed minutes',()=>{const base=relayReady(),started=craft(base,'impulse-relay','common');expect(started.componentInventory.circuits).toBe(0);expect(started.componentInventory.copperCoils).toBe(0);expect(started.crafting.active?.durationPerUnit).toBe(300);expect(advance(started,299).state.inventory).toHaveLength(0);expect(advance(started,300).state.inventory[0]).toMatchObject({type:'impulse-relay',relayTaps:0});});
 it('blocks crafting before the blueprint unlock',()=>{const base=relayReady(),locked={...base,impulseRelayBlueprint:false};expect(craftAffordability(locked,'impulse-relay').unlocked).toBe(false);expect(craft(locked,'impulse-relay','common')).toBe(locked);});
 it('pays exactly two production seconds on every tenth paid tap without recursion',()=>{let state=createItem({...newGame(0),prestigeCount:1},'impulse-relay','common'),id=state.inventory[0].id;state=equip(state,id);for(let i=0;i<9;i++)state=registerTap(state,i);const before=exactEconomyValue(state,'credits'),base=tapCreditsScientific(state,10),bonus=creditRateScientific(state.hardware,state.level,state,10,false).multiplyNumber(2),tenth=registerTap(state,10),gain=exactEconomyValue(tenth,'credits').subtract(before);expect(gain.compare(base.add(bonus))).toBe(0);expect(tenth.inventory[0].relayTaps).toBe(10);expect(tenth.lifetime.taps).toBe(10);expect(BALANCE.tapLimitPerSecond).toBe(5);});
 it('does not count or reward a blocked no-taps challenge impulse',()=>{let state=createItem({...newGame(0),prestigeCount:1,retention:{...newGame(0).retention,activeRun:{id:'no-taps',runId:'test',startedAt:0,eligibleAtStart:{m:0,e:0}}}},'impulse-relay','common'),id=state.inventory[0].id;state=equip(state,id);const before=exactEconomyValue(state,'credits'),after=registerTap(state,1);expect(exactEconomyValue(after,'credits').compare(before)).toBe(0);expect(after.inventory[0].relayTaps).toBe(0);});
 it('persists the counter through reload and equipment changes and permits only one processor relay',()=>{let state=createItem({...newGame(0),prestigeCount:1},'impulse-relay','common'),first=state.inventory[0].id;state=equip(state,first);for(let i=0;i<7;i++)state=registerTap(state,i);state=restore(serialize(state),state.savedAt).state;state=createItem(state,'impulse-relay','common');const second=state.inventory[1].id;state=equip(state,second);expect(state.equipped.processor).toBe(second);state=equip(state,first);expect(state.inventory.find(i=>i.id===first)?.relayTaps).toBe(7);expect(Object.values(state.equipped).filter(id=>[first,second].includes(id!))).toHaveLength(1);});
 it('survives prestige but remains unequippable before the first prestige',()=>{let state=createItem({...relayReady(),impulseRelayBlueprint:true},'impulse-relay','common'),id=state.inventory[0].id;expect(equip(state,id)).toBe(state);const huge=ScientificNumber.from(1e20),eligible={...state,credits:1e20,lifetimeEligibleCredits:1e20,cycleEligibleCredits:1e20,runCreditsEarned:1e20,exactEconomy:{...state.exactEconomy,credits:huge.toJSON(),lifetimeEligibleCredits:huge.toJSON(),cycleEligibleCredits:huge.toJSON(),runCreditsEarned:huge.toJSON()}};const reset=prestige(eligible);expect(reset.inventory.some(i=>i.id===id)).toBe(true);expect(reset.impulseRelayBlueprint).toBe(true);expect(equip(reset,id).equipped.processor).toBe(id);});
});
