import { BALANCE, GameState, grantComponents, Item, itemTypes, ItemTypeId, Rarity, spendComponents } from './economy';
import { addEvent } from './telemetry';
export const rarities=Object.keys(BALANCE.rarity) as Rarity[];
export function createItem(s:GameState,type:ItemTypeId,rarity:Rarity){const item:Item={id:`item-${s.nextId}`,type,rarity,level:0,locked:false},itemTypes=s.lifetime.itemTypes.includes(type)?s.lifetime.itemTypes:[...s.lifetime.itemTypes,type];return addEvent({...s,nextId:s.nextId+1,inventory:[...s.inventory,item],lifetime:{...s.lifetime,itemTypes}},'item-create',s.savedAt,{id:item.id,type,rarity});}
export function randomItem(s:GameState,rng=Math.random){let min=0; const pity={rare:s.pity.rare+1,epic:s.pity.epic+1,legendary:s.pity.legendary+1}; if(pity.legendary>=100)min=4;else if(pity.epic>=50)min=3;else if(pity.rare>=20)min=2; let roll=rng(),idx=rarities.findIndex(r=>{roll-=BALANCE.rarity[r].chance;return roll<=0});idx=Math.max(min,idx<0?0:idx);const rarity=rarities[idx];if(idx>=2)pity.rare=0;if(idx>=3)pity.epic=0;if(idx>=4)pity.legendary=0;const types=Object.keys(itemTypes) as ItemTypeId[];return createItem({...s,pity},types[Math.floor(rng()*types.length)%types.length],rarity);}
export function craft(s:GameState,type:ItemTypeId,rarity:Rarity){const recipe=BALANCE.craftingRecipes[rarity],blueprints=BALANCE.rarity[rarity].craft[1],paid=spendComponents(s,recipe);if(paid===s||s.blueprintFragments<blueprints)return s;const made=createItem({...paid,blueprintFragments:s.blueprintFragments-blueprints,lifetime:{...paid.lifetime,itemsCrafted:paid.lifetime.itemsCrafted+1}},type,rarity);return addEvent(made,'item-craft',s.savedAt,{type,rarity,ingredients:JSON.stringify(recipe),blueprintFragments:blueprints});}
export function equip(s:GameState,id:string){const item=s.inventory.find(i=>i.id===id);return !item?s:addEvent({...s,equipped:{...s.equipped,[itemTypes[item.type].slot]:id},onboarding:{...s.onboarding,completed:[...new Set([...s.onboarding.completed,'equip-item'])]}},'item-equip',s.savedAt,{id,type:item.type});}
export function toggleLock(s:GameState,id:string){const item=s.inventory.find(i=>i.id===id);return !item?s:addEvent({...s,inventory:s.inventory.map(i=>i.id===id?{...i,locked:!i.locked}:i)},'item-lock',s.savedAt,{id,locked:!item.locked});}
export function salvage(s:GameState,id:string){const item=s.inventory.find(i=>i.id===id);if(!item||item.locked||Object.values(s.equipped).includes(id))return s;const gained=BALANCE.rarity[item.rarity].salvage,next=grantComponents({...s,inventory:s.inventory.filter(i=>i.id!==id)},{circuits:gained});return addEvent(next,'item-salvage',s.savedAt,{id,type:item.type,rarity:item.rarity,component:'circuits',amount:gained});}
export function upgrade(s:GameState,id:string){const item=s.inventory.find(i=>i.id===id),discount=s.nodes.includes('artifacts-2')?.95:1,cost=item?Math.ceil(BALANCE.upgradeBase*BALANCE.upgradeGrowth**item.level*discount):Infinity;if(!item||item.level>=BALANCE.maxUpgrade)return s;const paid=spendComponents(s,{circuits:cost});return paid===s?s:addEvent({...paid,inventory:paid.inventory.map(i=>i.id===id?{...i,level:i.level+1}:i)},'item-upgrade',s.savedAt,{id,level:item.level+1,component:'circuits',cost});}
