import { BALANCE, dayKey, GameState, MissionPeriod, weekKey } from './economy';
import { addEvent } from './telemetry';
const rewards=(p:MissionPeriod,daily:boolean)=>daily?[p.activeSeconds>=300&&['active',5],p.hardware>=5&&['hardware',5],p.training>=1&&['training',10]].filter(Boolean) as [string,number][]:[p.days.length>=5&&['days',70],p.training>=30&&['training',70]].filter(Boolean) as [string,number][];
export function rollPeriods(s:GameState,now:number){const d=dayKey(now),w=weekKey(now);let {daily,weekly,mailbox}=s.missions;if(daily.key!==d){for(const [id,gems] of rewards(daily,true))if(!daily.claims.includes(id))mailbox=[...mailbox,{id:`${daily.key}-${id}`,gems}];daily={key:d,activeSeconds:0,hardware:0,training:0,days:[],claims:[]};}if(weekly.key!==w){for(const [id,gems] of rewards(weekly,false))if(!weekly.claims.includes(id))mailbox=[...mailbox,{id:`${weekly.key}-${id}`,gems}];weekly={key:w,activeSeconds:0,hardware:0,training:0,days:[],claims:[]};}return {...s,missions:{daily,weekly,mailbox}};}
export function addActive(s:GameState,seconds:number,now:number){s=rollPeriods(s,now);const day=dayKey(now),days=s.missions.weekly.days.includes(day)?s.missions.weekly.days:[...s.missions.weekly.days,day];return {...s,missions:{...s.missions,daily:{...s.missions.daily,activeSeconds:s.missions.daily.activeSeconds+seconds},weekly:{...s.missions.weekly,days}}};}
export function claimMission(s:GameState,period:'daily'|'weekly',id:string){const p=s.missions[period],entry=rewards(p,period==='daily').find(x=>x[0]===id);if(!entry||p.claims.includes(id))return s;return addEvent({...s,gems:s.gems+entry[1],missions:{...s.missions,[period]:{...p,claims:[...p.claims,id]}}},'mission-claim',s.savedAt,{period,id,gems:entry[1]});}
export function claimMailbox(s:GameState){if(!s.missions.mailbox.length)return s;const gems=s.missions.mailbox.reduce((n,x)=>n+x.gems,0);return addEvent({...s,gems:s.gems+gems,missions:{...s.missions,mailbox:[]}},'mission-claim',s.savedAt,{period:'mailbox',id:'mailbox',gems,count:s.missions.mailbox.length});}
export function achievementCheck(s:GameState){let gems=0,points=0,claims=[...s.achievementClaims],next=s;BALANCE.achievementThresholds.forEach((t,i)=>{if(s.lifetimeCreditsEarned>=t&&!claims.includes(i)){claims.push(i);gems+=BALANCE.achievementGems;points+=BALANCE.achievementPoints;next=addEvent(next,'achievement',s.savedAt,{index:i,threshold:t});}});return {...next,gems:s.gems+gems,achievementPoints:s.achievementPoints+points,achievementClaims:claims};}
export function buyGemComponents(s:GameState){const [g,c]=BALANCE.gemShop.components;return s.gems<g?s:{...s,gems:s.gems-g,components:s.components+c};}
export function buyTrainingBoost(s:GameState,now:number){const [g,d]=BALANCE.gemShop.trainingBoost,remaining=Math.max(0,s.trainingBoostUntil-now);return s.gems<g||remaining>=BALANCE.gemShop.boostCap*1000?s:{...s,gems:s.gems-g,trainingBoostUntil:now+Math.min(BALANCE.gemShop.boostCap*1000,remaining+d*1000)};}
