import {BALANCE,dayKey,GameState,MissionPeriod,MissionTask,ProgressMetric,weekKey} from './economy';
import {addEvent} from './telemetry';
export type MissionKind='daily'|'weekly'|'monthly';
const monthKey=(ms:number)=>new Date(ms).toISOString().slice(0,7);
const dayEnd=(ms:number)=>{const d=new Date(ms);return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()+1)};
const weekEnd=(ms:number)=>{const d=new Date(ms),day=(d.getUTCDay()+6)%7;return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()-day+7)};
const monthEnd=(ms:number)=>{const d=new Date(ms);return Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1)};
export const metricValue=(s:GameState,m:ProgressMetric)=>s.lifetime[m] as number;
type Template={id:string;metric:ProgressMetric;de:string;en:string;base:[number,number,number];available:(s:GameState)=>boolean};
const templates:Template[]=[
 {id:'hardware',metric:'hardwareBought',de:'Hardware kaufen',en:'Buy hardware',base:[25,300,2500],available:()=>true},{id:'milestones',metric:'milestones',de:'Hardware-Meilensteine erreichen',en:'Reach hardware milestones',base:[2,12,50],available:()=>true},{id:'train-start',metric:'trainingStarted',de:'Training starten',en:'Start training',base:[2,15,60],available:()=>true},{id:'train-done',metric:'trainingCompleted',de:'Training abschließen',en:'Complete training',base:[1,10,40],available:()=>true},{id:'research-start',metric:'researchStarted',de:'Forschung starten',en:'Start research',base:[1,10,40],available:s=>s.discovered.includes('sbc')},{id:'research-done',metric:'researchCompleted',de:'Forschung abschließen',en:'Complete research',base:[1,7,30],available:s=>s.discovered.includes('sbc')},{id:'components',metric:'componentsEarned',de:'Komponenten erhalten',en:'Gain components',base:[25,250,1500],available:s=>s.prestigeCount>0||s.experiments.firstReward},{id:'craft',metric:'itemsCrafted',de:'Items herstellen',en:'Craft items',base:[1,5,20],available:s=>s.blueprintFragments>0||s.lifetime.itemsCrafted>0},{id:'credits',metric:'regularCredits',de:'Credits produzieren',en:'Produce credits',base:[1e4,1e7,1e10],available:()=>true},{id:'data',metric:'regularData',de:'Daten produzieren',en:'Produce data',base:[250,5000,50000],available:()=>true},{id:'taps',metric:'taps',de:'Vergütete Taps ausführen',en:'Perform rewarded taps',base:[250,5000,50000],available:()=>true},{id:'overclock',metric:'overclocks',de:'Overclock aktivieren',en:'Activate overclock',base:[2,20,100],available:()=>true},{id:'prestige',metric:'prestiges',de:'Prestige durchführen',en:'Perform prestige',base:[1,3,10],available:s=>s.prestigeCount>0||s.lifetimeEligibleCredits>=1e8},{id:'active',metric:'activeSeconds',de:'Aktiv spielen',en:'Play actively',base:[600,7200,36000],available:()=>true},
];
const counts={daily:6,weekly:12,monthly:30} as const;
const required={daily:4,weekly:8,monthly:20} as const;
function makePeriod(s:GameState,kind:MissionKind,now:number):MissionPeriod{const index=kind==='daily'?0:kind==='weekly'?1:2,count=counts[kind],reward=BALANCE.missionRewards[kind],key=kind==='daily'?dayKey(now):kind==='weekly'?weekKey(now):monthKey(now),endsAt=kind==='daily'?dayEnd(now):kind==='weekly'?weekEnd(now):monthEnd(now);const available=templates.filter(t=>t.available(s)),seed=[...key].reduce((n,c)=>n+c.charCodeAt(0),0),tasks:MissionTask[]=[];for(let i=0;i<count;i++){const t=available[(seed+i)%available.length],stage=Math.floor(i/available.length),multiplier=stage===0?1:5**stage;tasks.push({id:`${key}-${t.id}-${i}`,metric:t.metric,goal:t.base[index]*multiplier,baseline:metricValue(s,t.metric),reward:reward.task*(stage+1),claimed:false,de:`${t.de}${stage?` · Stufe ${stage+1}`:''}`,en:`${t.en}${stage?` · Tier ${stage+1}`:''}`});}return{key,endsAt,tasks,required:required[kind],bonus:reward.bonus,bonusClaimed:false};}
const completed=(s:GameState,t:MissionTask)=>metricValue(s,t.metric)-t.baseline>=t.goal;
function settle(s:GameState,kind:MissionKind,p:MissionPeriod){const taskGems=p.tasks.filter(t=>completed(s,t)&&!t.claimed).reduce((n,t)=>n+t.reward,0),done=p.tasks.filter(t=>completed(s,t)).length,bonus=done>=p.required&&!p.bonusClaimed?p.bonus:0,total=taskGems+bonus;if(!total)return s;return{...s,gems:s.gems+total,gemLedger:[...s.gemLedger,{id:`mission-expiry-${kind}-${p.key}`,at:s.savedAt,amount:total,source:`mission-${kind}-expiry`}]};}
export function rollPeriods(s:GameState,now:number){let next=s;for(const kind of ['daily','weekly','monthly'] as MissionKind[]){let p=next.missions[kind],key=kind==='daily'?dayKey(now):kind==='weekly'?weekKey(now):monthKey(now);if(!p.tasks.length)p=makePeriod(next,kind,now);else if(p.key!==key){next=settle(next,kind,p);p=makePeriod(next,kind,now)}next={...next,missions:{...next.missions,[kind]:p}};}return next;}
export function addActive(s:GameState,seconds:number,now:number){s=rollPeriods(s,now);return{...s,lifetime:{...s.lifetime,activeSeconds:s.lifetime.activeSeconds+seconds}};}
export function claimMission(s:GameState,period:MissionKind,id:string){const p=s.missions[period],task=p.tasks.find(t=>t.id===id);if(!task||task.claimed||!completed(s,task))return s;const tasks=p.tasks.map(t=>t.id===id?{...t,claimed:true}:t),entry={id:`mission-${period}-${id}`,at:s.savedAt,amount:task.reward,source:`mission-${period}`};return addEvent({...s,gems:s.gems+task.reward,gemLedger:[...s.gemLedger,entry],missions:{...s.missions,[period]:{...p,tasks}}},'mission-claim',s.savedAt,{period,id,gems:task.reward});}
export function claimMissionBonus(s:GameState,period:MissionKind){const p=s.missions[period],done=p.tasks.filter(t=>completed(s,t)).length;if(p.bonusClaimed||done<p.required)return s;return addEvent({...s,gems:s.gems+p.bonus,gemLedger:[...s.gemLedger,{id:`mission-bonus-${period}-${p.key}`,at:s.savedAt,amount:p.bonus,source:`mission-${period}-bonus`}],missions:{...s.missions,[period]:{...p,bonusClaimed:true}}},'mission-claim',s.savedAt,{period,id:'bonus',gems:p.bonus});}
export function claimMailbox(s:GameState){return s;}
export const missionProgress=(s:GameState,t:MissionTask)=>Math.min(t.goal,Math.max(0,metricValue(s,t.metric)-t.baseline));
