import {BALANCE,equipmentSlotCount,hardwareIds,isRepeatableResearch,researchLabCount,researchRequirement,repeatableResearchDataCost,type GameState,type ResearchId} from './economy';
import {craftAffordability} from './inventory';
type RecipeId=keyof typeof BALANCE.itemRecipes;
import {itemTypes} from './economy';
import {onboardingSteps} from './onboarding';
import {tutorialGuide} from './tutorialGuide';
import {effectText,itemText,projectText,researchText} from './gameplayI18n';

export type NextGoal={kind:'tutorial'|'onboarding'|'equipment'|'recipe'|'research'|'hardware'|'complete';title:string;progress:string;benefit:string;tab:'workshop'|'research'|'inventory';subtab?:string;targetId:string};
const recipeReady=(s:GameState,type:RecipeId)=>{const a=craftAffordability(s,type);return !a.data.missing&&!a.missingBlueprints&&!Object.keys(a.missingComponents).length&&!Object.keys(a.missingModules).length};
export function nextGoal(s:GameState):NextGoal{
 const de=s.settings.language==='de',guide=s.story.tutorial==='active'?tutorialGuide(s):null;
 if(guide)return{kind:'tutorial',title:guide.title,progress:guide.requirement??(de?'Bereit':'Ready'),benefit:guide.explanation,tab:guide.tab,subtab:guide.subtab,targetId:guide.targetId};
 if(s.story.tutorial==='active')return{kind:'tutorial',title:de?'Miras Einführung':'Mira’s introduction',progress:de?'Dialog fortsetzen':'Continue the dialogue',benefit:de?'Die laufende Einführung ist dein nächster Schritt.':'The active introduction is your next step.',tab:'workshop',targetId:'next-goal-card'};
 const onboarding=onboardingSteps.find(step=>s.onboarding.completed.includes(step.id)&&!s.onboarding.claimed.includes(step.id));
 if(onboarding)return{kind:'onboarding',title:de?`Belohnung abholen: ${onboarding.title}`:`Claim reward: ${onboarding.title}`,progress:onboarding.reward,benefit:de?'Die bereits verdiente Onboarding-Belohnung wartet.':'Your earned onboarding reward is waiting.',tab:'workshop',targetId:'next-goal-onboarding'};
 const equipped=new Set(Object.values(s.equipped)),freeEquipment=s.prestigeCount>0&&Object.values(s.equipped).filter(Boolean).length<equipmentSlotCount(s),compatible=s.inventory.find(item=>!equipped.has(item.id)&&!s.equipped[itemTypes[item.type].slot]);
 if(freeEquipment&&compatible)return{kind:'equipment',title:de?`${itemText(compatible.type,s.settings.language)} ausrüsten`:`Equip ${itemText(compatible.type,s.settings.language)}`,progress:de?'Freier kompatibler Platz':'Compatible slot available',benefit:`${effectText(itemTypes[compatible.type].effect,s.settings.language)} · ${compatible.rarity}`,tab:'workshop',targetId:'tutorial-equipment'};
 if(s.crafting.queue.length<3){const recipe=(Object.keys(BALANCE.itemRecipes) as RecipeId[]).find(type=>recipeReady(s,type));if(recipe)return{kind:'recipe',title:de?BALANCE.itemRecipes[recipe].name:`Craft ${itemText(recipe,s.settings.language)}`,progress:de?'Alle Ressourcen vorhanden':'All resources available',benefit:`${itemText(recipe,s.settings.language)} · ${effectText(itemTypes[recipe].effect,s.settings.language)}`,tab:'inventory',targetId:`tutorial-recipe-${recipe}`}}
 const freeLab=s.researchLabs.some((lab,index)=>index<researchLabCount(s)&&!lab);if(s.discovered.includes('sbc')&&freeLab){const oneTime=Object.keys(BALANCE.researchProjects).find(id=>!s.completedResearch.includes(id as any)&&!s.researchLabs.some(l=>l?.id===id)&&s.data>=BALANCE.researchProjects[id as keyof typeof BALANCE.researchProjects].data) as ResearchId|undefined;const repeatable=(Object.keys(BALANCE.repeatableResearch) as ResearchId[]).find(id=>isRepeatableResearch(id)&&!researchRequirement(s,id)&&!s.researchLabs.some(l=>l?.id===id)&&s.data>=repeatableResearchDataCost(id,s.researchLevels[id]+1));const research=oneTime??repeatable;if(research){const data=isRepeatableResearch(research)?repeatableResearchDataCost(research,s.researchLevels[research]+1):BALANCE.researchProjects[research as keyof typeof BALANCE.researchProjects].data;const copy=isRepeatableResearch(research)?researchText(research,s.settings.language):projectText(research as keyof typeof BALANCE.researchProjects,s.settings.language);return{kind:'research',title:`${de?'Forschung starten':'Start research'}: ${copy.name}`,progress:`${data} ${de?'Daten verfügbar':'data available'}`,benefit:copy.effect,tab:'research',subtab:'research',targetId:`research-${research}`}}}
 for(const id of hardwareIds){const owned=s.hardwareCounts[id];if(owned<=0)continue;const milestone=BALANCE.hardwareMilestones.find(n=>n>owned);if(milestone){const definition=BALANCE.hardware[id].milestones.find(m=>m.threshold===milestone)!;return{kind:'hardware',title:`${BALANCE.hardware[id].name}: ${milestone}`,progress:`${owned} / ${milestone}`,benefit:`+${Math.round(definition.compute*100)} % Compute · ${definition.label}`,tab:'workshop',targetId:`hardware-${id}`}}}
 return{kind:'complete',title:de?'Labor im Gleichgewicht':'Labor in balance',progress:de?'Kein unmittelbares Ziel offen.':'No immediate goal is open.',benefit:de?'Spiele frei weiter oder plane den nächsten Prestige.':'Continue freely or plan the next prestige.',tab:'workshop',targetId:'next-goal-card'};
}
