import {BALANCE,creditRate,dataRate,hardwareCost,hardwareIds,isRepeatableResearch,newINT,prestigeUpgradeCost,researchProjectDataCost,repeatableResearchDataCost,type GameState,type HardwareId,type ItemTypeId,type PrestigeUpgradeId,type ResearchId} from './economy';
import {craftAffordability} from './inventory';
import {tutorialGuide} from './tutorialGuide';
import {onboardingSteps} from './onboarding';
import {missionRewardClaimable} from './missions';
import {seasonClaimable} from './season';
import {hardwareText} from './i18n';
import {itemText,prestigeText,projectText,researchText} from './gameplayI18n';

export type PinnedGoal={kind:'hardware'|'research'|'recipe'|'prestige';id:string;target?:number};
export type NextGoal={kind:'tutorial'|'reward'|'hardware'|'research'|'recipe'|'prestige'|'complete';title:string;progress:string;missing?:string;etaSeconds?:number;reached?:boolean;benefit:string;tab:'workshop'|'research'|'inventory'|'prestige';subtab?:string;targetId:string};
const fmt=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:1,notation:n>=1e6?'compact':'standard'}).format(Math.max(0,n));
export function resolvePinnedGoal(s:GameState,pin:PinnedGoal):NextGoal|null{const de=s.settings.language==='de';
 if(pin.kind==='hardware'){const id=pin.id as HardwareId,h=BALANCE.hardware[id];if(!h)return null;const target=pin.target??h.milestones.find(x=>x.threshold>s.hardwareCounts[id])?.threshold??s.hardwareCounts[id],owned=s.hardwareCounts[id],reached=owned>=target,missing=Math.max(0,target-owned),cost=Array.from({length:missing},(_,i)=>hardwareCost(id,owned+i,s)).reduce((a,b)=>a+b,0),rate=creditRate(s.hardware,s.level,s,s.savedAt);return{kind:'hardware',title:`${hardwareText(id,s.settings.language).name} · ${target}`,progress:`${Math.min(owned,target)} / ${target}`,missing:reached?(de?'Erreicht':'Reached'):`${missing} · ${fmt(Math.max(0,cost-s.credits))} Credits ${de?'fehlen':'missing'}`,etaSeconds:!reached&&rate>0?Math.max(0,cost-s.credits)/rate:undefined,reached,benefit:de?'Hardware-Meilenstein':'Hardware milestone',tab:'workshop',targetId:`hardware-${id}`};}
 if(pin.kind==='research'){const id=pin.id as ResearchId,repeat=isRepeatableResearch(id),level=repeat?(pin.target??s.researchLevels[id]+1):1,reached=repeat?s.researchLevels[id]>=level:s.completedResearch.includes(id as never),cost=repeat?repeatableResearchDataCost(id,level):researchProjectDataCost(id as never),copy=repeat?researchText(id,s.settings.language):projectText(id as never,s.settings.language),missing=Math.max(0,cost-s.data),rate=dataRate(s);return{kind:'research',title:`${copy.name} · ${de?'Stufe':'Level'} ${level}`,progress:reached?(de?'Erreicht':'Reached'):`${fmt(s.data)} / ${fmt(cost)} Data`,missing:reached?(de?'Erreicht':'Reached'):`${fmt(missing)} Data ${de?'fehlen':'missing'}`,etaSeconds:missing>0&&rate>0?missing/rate:undefined,reached,benefit:copy.effect,tab:'research',subtab:'research',targetId:`research-${id}`};}
 if(pin.kind==='recipe'){const id=pin.id as ItemTypeId;if(!(id in BALANCE.itemRecipes))return null;const a=craftAffordability(s,id),missing=Object.values(a.missingComponents).reduce((n,x)=>n+x,0)+a.missingBlueprints+a.data.missing;return{kind:'recipe',title:itemText(id,s.settings.language),progress:missing<=0?(de?'Bereit':'Ready'):`${fmt(missing)} ${de?'Materialien fehlen':'materials missing'}`,missing:missing<=0?(de?'Erreicht':'Reached'):undefined,reached:missing<=0,benefit:de?'Rezept herstellen':'Craft recipe',tab:'inventory',targetId:`tutorial-recipe-${id}`};}
 const id=pin.id as PrestigeUpgradeId,node=BALANCE.prestigeUpgrades[id];if(!node)return null;const reached=s.nodes.includes(id),cost=prestigeUpgradeCost(id),missing=Math.max(0,cost-s.unspentINT);return{kind:'prestige',title:prestigeText(id,s.settings.language).name,progress:reached?(de?'Erreicht':'Reached'):`${fmt(s.unspentINT)} / ${fmt(cost)} INT`,missing:reached?(de?'Erreicht':'Reached'):`${fmt(missing)} INT ${de?'fehlen':'missing'}`,reached,benefit:prestigeText(id,s.settings.language).effect,tab:'prestige',targetId:'tutorial-prestige-action'};
}
export function nextGoal(s:GameState):NextGoal{const de=s.settings.language==='de',guide=s.story.tutorial==='active'?tutorialGuide(s):null;if(guide)return{kind:'tutorial',title:guide.title,progress:guide.requirement??(de?'Bereit':'Ready'),benefit:guide.explanation,tab:guide.tab,subtab:guide.subtab,targetId:guide.targetId};
 if(s.story.tutorial==='active')return{kind:'tutorial',title:de?'Miras Einführung':'Mira’s introduction',progress:de?'Dialog fortsetzen':'Continue dialogue',benefit:de?'Die Einführung ist dein nächster Schritt.':'The introduction is your next step.',tab:'workshop',targetId:'next-goal-card'};
  const onboarding=onboardingSteps.find(step=>s.onboarding.completed.includes(step.id)&&!s.onboarding.claimed.includes(step.id));if(onboarding)return{kind:'tutorial',title:de?`Belohnung abholen: ${onboarding.title}`:`Claim reward: ${onboarding.title}`,progress:onboarding.reward,benefit:de?'Tutorialschritt abschließen':'Complete tutorial step',tab:'workshop',targetId:'next-goal-onboarding'};
 if((['daily','weekly','monthly'] as const).some(k=>missionRewardClaimable(s,k))||seasonClaimable(s))return{kind:'reward',title:de?'Belohnung abholen':'Claim reward',progress:de?'Eine Quest- oder Season-Belohnung ist bereit.':'A quest or Season reward is ready.',benefit:de?'Bereits verdient – keine Ressourcen werden automatisch ausgegeben.':'Already earned — no resources are spent automatically.',tab:'workshop',targetId:'mission-drawer'};
 if(s.pinnedGoal){const pinned=resolvePinnedGoal(s,s.pinnedGoal);if(pinned)return pinned;}
 const id=hardwareIds.find(x=>s.hardwareCounts[x]===0);if(id){const previous=hardwareIds[Math.max(0,hardwareIds.indexOf(id)-1)],needed=BALANCE.hardwareUnlockCount,owned=s.hardwareCounts[previous];return{kind:'hardware',title:hardwareText(id,s.settings.language).name,progress:`${Math.min(owned,needed)} / ${needed} ${hardwareText(previous,s.settings.language).name}`,missing:`${Math.max(0,needed-owned)} ${de?'fehlen':'missing'}`,reached:owned>=needed,benefit:de?'Nächste Hardwareklasse':'Next hardware class',tab:'workshop',targetId:`hardware-${previous}`};}
 return{kind:'complete',title:de?'Alle Hardwareklassen entdeckt':'All hardware classes discovered',progress:de?'Kein unmittelbares Ziel offen.':'No immediate goal is open.',benefit:`${de?'Prestige-Anspruch':'Prestige claim'}: ${newINT(s)} INT`,tab:'prestige',targetId:'tutorial-prestige-action'};}
export function pinnableGoals(s:GameState):PinnedGoal[]{const nextHardware=hardwareIds.flatMap(id=>{const m=BALANCE.hardware[id].milestones.find(x=>x.threshold>s.hardwareCounts[id]);return m?[{kind:'hardware' as const,id,target:m.threshold}]:[]});const research=[...Object.keys(BALANCE.researchProjects),...Object.keys(BALANCE.repeatableResearch)].slice(0,6).map(id=>({kind:'research' as const,id}));const recipes=Object.keys(BALANCE.itemRecipes).map(id=>({kind:'recipe' as const,id}));const prestige=Object.keys(BALANCE.prestigeUpgrades).filter(id=>!s.nodes.includes(id)).slice(0,5).map(id=>({kind:'prestige' as const,id}));return[...nextHardware,...research,...recipes,...prestige];}
