import {MissionHub} from './MetaHub';
import { useCallback, useEffect, useRef, useState,type MouseEvent, type PointerEvent as ReactPointerEvent } from 'react';
import {MobileDetailSheet} from './MobileDetailSheet';
import type {FindCard} from './RewardFeedback';
import { BALANCE, BreakthroughId, classCompute, computeRate, computeAllocation, creditRate, dataRate, researchRate, usersRate, ExperimentId, GameState, HardwareId, TrainingTrack, MAX_ECONOMY_VALUE, componentIds, hardwareBulkCost, hardwareCost, hardwareIds, hardwareBulkCostScientific, hardwareCostScientific, canAffordScientificCreditCost, itemEffect, itemTypes, maxAffordable, newINT, nextPrestigeThreshold, prestigeUpgradeCost,prestigeUpgradeCostScientific, upgradeLevel, PrestigeUpgradeId, OperatingProfileId, ResearchProjectId, RepeatableResearchId, ResearchId, isRepeatableResearch, repeatableResearchDataCost, repeatableResearchDuration, researchRequirement, reachedMilestones, permanentFactor, Rarity, ItemTypeId, tapCredits, trainingCost, trainingDataCost, trainingRate, trainingWork, researchDuration, researchDurationAtStart, researchProjectDataCost, researchLabCount, equipmentSlotCount, productionBreakdown, hardwareAutobuyerUnlocked, hardwareMasteryLevel, hardwareMasteryBonus, legacyHardwareClasses, legacyInfrastructureMultiplier, hardwareOwnershipCreditMultiplier, exactEconomyValue, formatScientific, formatExactEconomy, creditRateScientific, computeRateScientific, usersRateScientific, dataRateScientific, dataMultiplier, researchRateScientific, trainingCostScientific, trainingDataCostScientific, canAffordScientificResources, quality, efficiency, passiveComponentWeights, shoppingAgentUnlocked, axiomUpgradeCost } from './economy';
import { prestigePreview,prestigeUpgrades,axiomPreview,prestigeAgentStatus } from './prestige';
import { analysisAffordability, analysisBlockReason, analysisCost, analysisDropTable, experimentDuration, experimentNames, experimentSpeed } from './experiments';
import { ActivityArt, ComponentArt, HardwareArt, ItemArt, MetaArt, PrestigeArt, ResourceArt } from './GameArt';
import {achievements,achievementReady,achievementResearchBonus,currentAchievementTier} from './achievements';
import {missionProgress,missionText} from './missions';
import { craftAffordability, itemUpgradeCost, moduleAffordability } from './inventory';
import {GemShop} from './GemShopPanel';
import { dialogues, storyChapters } from './story';
import { hardwareText, localeFor } from './i18n';
import { wt, hardwareMilestoneText, operatingProfileText } from './workshopI18n';
import { g, researchText, projectText, experimentText, breakthroughText, componentText, rarityText, itemText, effectText, moduleText, recipeText, prestigeText } from './gameplayI18n';
import {ScientificNumber} from './scientificNumber';
import {PRESTIGE_CANVAS,prestigeLayout,prestigeNodeState,validatePrestigeCatalog} from './prestigeTree';

const componentRarity=(value:string):Rarity=>value==='häufig'?'common':value==='ungewöhnlich'?'uncommon':value==='selten'?'rare':value==='episch'?'epic':value==='legendär'?'legendary':'mythic';
const rarityName:Record<Rarity,string>={common:'Gewöhnlich',uncommon:'Ungewöhnlich',rare:'Selten',epic:'Episch',legendary:'Legendär',mythic:'Mythisch'};
let activeNumberLocale='de-DE';
export const num=(n:number,d=1)=>!Number.isFinite(n)?'—':Math.abs(n)>=1e15?n.toExponential(Math.min(2,d)):new Intl.NumberFormat(activeNumberLocale,{maximumFractionDigits:d,notation:Math.abs(n)>=1e6?'compact':'standard'}).format(n);
export function ExactNumber({s,resourceKey,digits=2}:{s:GameState;resourceKey:'credits'|'data'|'researchPoints';digits?:number}){return <>{formatExactEconomy(s,resourceKey,digits)}</>}
export function AnimatedNumber({value,digits=1}:{value:number;digits?:number}){const [shown,setShown]=useState(value),previous=useRef(value);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches||document.hidden){previous.current=value;setShown(value);return}const from=previous.current,start=performance.now(),duration=350;let frame=0;const tick=(now:number)=>{const p=Math.min(1,(now-start)/duration),eased=1-(1-p)**3;setShown(from+(value-from)*eased);if(p<1)frame=requestAnimationFrame(tick);else previous.current=value};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value]);return <>{num(shown,digits)}</>}
type Action=(name:string,...args:any[])=>void;
const compactHeaderValue=(value:number,language:GameState['settings']['language'],format:GameState['settings']['numberFormat'])=>{if(!Number.isFinite(value))return '∞';if(format!=='auto')return formatScientific(ScientificNumber.from(value),1,format);const abs=Math.abs(value),units=language==='de'?[[1e12,'Bio.'],[1e9,'Mrd.'],[1e6,'Mio.'],[1e3,'Tsd.']] as const:[[1e12,'T'],[1e9,'B'],[1e6,'M'],[1e3,'K']] as const;for(const [limit,suffix] of units)if(abs>=limit){const scaled=value/limit;return `${new Intl.NumberFormat(localeFor(language),{maximumFractionDigits:Math.abs(scaled)>=100?0:Math.abs(scaled)>=10?1:2}).format(scaled)} ${suffix}`}return new Intl.NumberFormat(localeFor(language),{maximumFractionDigits:abs<100?1:0}).format(value)};
export function ResourceBar({s,onMenu,hasNotice}:{s:GameState;onMenu:()=>void;hasNotice:boolean}){activeNumberLocale=localeFor(s.settings.language);return <header className="resource-bar"><div id="tutorial-credits" tabIndex={-1}><ResourceArt id="credits"/><span>{wt(s.settings.language,'credits')}</span><b>{compactHeaderValue(s.credits,s.settings.language,s.settings.numberFormat)}</b><small>+{formatScientific(creditRateScientific(s.hardware,s.level,s,s.savedAt),1,s.settings.numberFormat)}/s</small></div><div id="tutorial-production" tabIndex={-1}><ResourceArt id="compute"/><span>{wt(s.settings.language,'compute')}</span><b>{formatScientific(computeRateScientific(s.hardware,s),1,s.settings.numberFormat)}</b></div><div><ResourceArt id="data"/><span>{wt(s.settings.language,'data')}</span><b>{compactHeaderValue(s.data,s.settings.language,s.settings.numberFormat)}</b><small>+{formatScientific(dataRateScientific(s),1,s.settings.numberFormat)}/s</small></div><div><ResourceArt id="gems"/><span>Gems</span><b>{s.gems}</b></div><button className="menu-button" onClick={onMenu} aria-label="Menü öffnen" aria-haspopup="dialog">☰{hasNotice&&<i/>}</button></header>}

function TapSurface({s,act,findCards}:{s:GameState;act:Action;findCards:FindCard[]}){const hold=useRef<number>(0),[pulse,setPulse]=useState(0),tap=()=>{act('tap');setPulse(x=>x+1)},start=()=>{act('hold-start');tap();window.clearInterval(hold.current);hold.current=window.setInterval(tap,1000/3)},stop=()=>{window.clearInterval(hold.current);act('hold-end')};useEffect(()=>{const hidden=()=>{if(document.hidden)stop()};window.addEventListener('blur',stop);document.addEventListener('visibilitychange',hidden);return()=>{stop();window.removeEventListener('blur',stop);document.removeEventListener('visibilitychange',hidden)}},[]);return <button id="tutorial-tap" className={`tap-surface ${s.overclock.activeUntil>s.savedAt?'overclock-active':''}`} onPointerDown={start} onPointerUp={stop} onPointerCancel={stop} onPointerLeave={stop} onBlur={stop} onClick={(e:any)=>{if(e.detail===0)tap()}}><span className={`core-construct core-stage-${Math.min(4,Math.floor((s.qualityLevel+s.efficiencyLevel)/5))}`} aria-hidden="true"><i/><i/><i/><b>AI</b></span>{pulse>0&&<i key={pulse} className="tap-pop">+{num(tapCredits(s),2)}</i>}<span className="tap-content"><strong>{wt(s.settings.language,'labImpulse')}</strong><span>+{num(tapCredits(s),2)} {wt(s.settings.language,'credits')} · {wt(s.settings.language,'tapOrHold')}</span></span><span className="core-tutorial">{s.hardware===0?(s.credits>=hardwareCost('calculator',0,s)?(s.settings.language==='de'?'Genug Credits für deine erste Hardware.':'Enough Credits for your first hardware.'):(s.lifetime.taps<5?(s.settings.language==='de'?'Tippe auf den Kern, um Credits zu erzeugen.':'Tap the core to generate Credits.'):(s.settings.language==='de'?'100 Impulse lösen automatisch Overclock aus.':'100 impulses automatically trigger Overclock.'))):null}</span><span className="core-status"><b>{s.overclock.activeUntil>s.savedAt?'OVERCLOCK':`${s.overclock.taps} / ${BALANCE.overclockTaps} IMPULSE`}</b>{s.overclock.activeUntil>s.savedAt&&<small>×2 · {Math.ceil((s.overclock.activeUntil-s.savedAt)/1000)}s</small>}</span><span className="core-finds">{findCards.map(card=><i key={card.id}>{componentIds.filter(id=>card.items[id]).map(id=><span key={id}><ComponentArt id={id}/><b>+{card.items[id]} {componentText(id,s.settings.language).name}</b></span>)}</i>)}</span><span className="core-loot">{s.lootDrops.map(drop=><span key={drop.id} role="button" tabIndex={0} className={`core-drop ${drop.variant??'coin'}`} style={{left:`${drop.x??50}%`,top:`${drop.y??40}%`}} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();act('loot-drop',drop.id)}}><ActivityArt id="drop-closed"/><small>×1</small></span>)}</span></button>}

function HardwareStore({s,act}:{s:GameState;act:Action}){const [selected,setSelected]=useState<HardwareId|null>(null),total=computeRate(s.hardware,s),language=s.settings.language;return <><div className="hardware-heading"><h2>{language==='de'?'Hardware':'Hardware'}</h2><div className="compact-buy-modes" role="group" aria-label="Kaufmenge">{([1,10,'max'] as const).map(mode=><button className={s.settings.buyMode===mode?'active':''} key={mode} onClick={()=>act('buy-mode',mode)}>{mode==='max'?'MAX':`×${mode}`}</button>)}</div></div><section id="tutorial-hardware" className="mobile-hardware-list">{hardwareIds.map((id,index)=>{const owned=s.hardwareCounts[id],mode=s.settings.buyMode??1,count=mode==='max'?maxAffordable(id,owned,s.credits,s):mode,cost= count?hardwareBulkCostScientific(id,owned,count,s):hardwareCostScientific(id,owned,s),output=classCompute(s,id),purchaseOutput=count>0?Math.max(0,classCompute(s,id,owned+count)-output):0,unlocked=index===0||s.discovered.includes(id)||s.hardwareCounts[hardwareIds[index-1]]>0,affordable=unlocked&&count>0&&canAffordScientificCreditCost(s,cost);return <article className={unlocked?'':'locked'} key={id}><button className="hardware-info" onClick={()=>setSelected(id)}><HardwareArt id={id}/><span><b>{hardwareText(id,language).name}</b><small>{unlocked?`+${num(purchaseOutput,1)} Compute/s ${language==='de'?'beim Kauf':'on purchase'}`:`🔒 ${language==='de'?'Vorherige Klasse entdecken':'Discover previous class'}`}</small></span><strong>×{owned}</strong></button><button id={id==='calculator'?'tutorial-buy-calculator':undefined} className="hardware-buy" disabled={!affordable} onClick={()=>act('buy-class',id)} aria-label={`${hardwareText(id,language).name} kaufen`}><span>{formatScientific(cost,1,s.settings.numberFormat)} C</span><b>{language==='de'?'KAUFEN':'BUY'}</b></button></article>})}</section>{selected&&(()=>{const id=selected,owned=s.hardwareCounts[id],milestones=reachedMilestones(id,owned),next=BALANCE.hardware[id].milestones.find(entry=>entry.threshold>owned),output=classCompute(s,id);return <MobileDetailSheet title={hardwareText(id,language).name} art={<HardwareArt id={id}/>} onClose={()=>setSelected(null)}><p>{hardwareText(id,language).description}</p><dl className="hardware-detail-stats"><div><dt>{language==='de'?'Besitz':'Owned'}</dt><dd>{owned}</dd></div><div><dt>Compute</dt><dd>{num(output,2)}/s</dd></div><div><dt>{language==='de'?'Anteil':'Share'}</dt><dd>{total?num(output/total*100,1):0}%</dd></div><div><dt>{wt(language,'mastery')}</dt><dd>Lv {hardwareMasteryLevel(s,id)}</dd></div></dl><p>{next?`${wt(language,'nextMilestone')} ${next.threshold}: ${hardwareMilestoneText(id,next.threshold,language)}`:wt(language,'allMilestones')}</p><small>{language==='de'?'Erreichte Meilensteine':'Reached milestones'}: {milestones.length?milestones.map(entry=>entry.threshold).join(', '):'—'}</small></MobileDetailSheet>})()}</>}

export function Workshop({s,act,findCards=[]}:{s:GameState;act:Action;findCards?:FindCard[]}){
 activeNumberLocale=localeFor(s.settings.language);
 const [modelOpen,setModelOpen]=useState(false),goal=s.activeTraining?.workRequired??trainingWork(s),rate=trainingRate(s.hardware,s,s.savedAt),durationText=(seconds:number)=>seconds>=3600?`${num(seconds/3600,1)} h`:seconds>=60?`${num(seconds/60,1)} min`:`${num(seconds,0)} s`;
 useEffect(()=>{if(s.story.tutorial==='active'&&s.story.target==='training')setModelOpen(true)},[s.story.target,s.story.tutorial]);
 const trainingPanel=<section className="training-detail"><div className="section-title"><b>{wt(s.settings.language,'model')} · Q{s.qualityLevel} / E{s.efficiencyLevel}</b><span>{s.activeTraining?`${num(s.training/goal*100,0)} %`:wt(s.settings.language,'ready')}</span></div>{s.activeTraining?<><div className="bar"><i style={{width:`${Math.min(100,s.training/goal*100)}%`}}/></div><small>{s.activeTraining.track==='quality'?wt(s.settings.language,'quality'):wt(s.settings.language,'efficiency')} · {s.settings.language==='de'?'Restzeit':'Remaining'} {durationText(Math.max(0,goal-s.training)/Math.max(rate,1))}</small></>:<div className="training-choices">{(['quality','efficiency'] as TrainingTrack[]).map(track=>{const level=track==='quality'?s.qualityLevel:s.efficiencyLevel,cost=trainingDataCostScientific(s,track),duration=trainingWork(s,track),effect=track==='quality'?`${wt(s.settings.language,'qualityEffect')}: ×${num(quality(level+1)/quality(level),3)}`:`${wt(s.settings.language,'efficiencyEffect')}: ×${num(efficiency(level+1)/efficiency(level),3)}`;return <button id={track==='quality'?'tutorial-quality-training':undefined} key={track} disabled={!canAffordScientificResources(s,undefined,cost)} onClick={()=>act('train',track)}><b>{track==='quality'?wt(s.settings.language,'trainQuality'):wt(s.settings.language,'trainEfficiency')} · {level} → {level+1}</b><small>{effect} · {formatScientific(cost,0,s.settings.numberFormat)} {wt(s.settings.language,'data')} · {durationText(duration)}</small></button>})}</div>}{upgradeLevel(s,'trainingPlan')>0&&<div className="training-queue"><b>{s.settings.language==='de'?'Trainingsplan':'Training plan'} · {s.trainingQueue.length}/2</b>{(['quality','efficiency'] as TrainingTrack[]).map(track=><button key={track} disabled={s.trainingQueue.length>=2} onClick={()=>act('train-queue',track)}>{s.settings.language==='de'?'Vormerken':'Queue'} {track}</button>)}{s.trainingQueue.map((job,index)=><button key={`${job.track}-${job.targetLevel}`} onClick={()=>act('train-queue-remove',index)}>{job.track} {job.targetLevel} · ×</button>)}</div>}</section>;
 return <div className="workshop-screen"><section className="workshop-action" aria-label={s.settings.language==='de'?'AI-Kern':'AI core'}><TapSurface s={s} act={act} findCards={findCards}/><button id="tutorial-equipment" className="model-status-row" onClick={()=>setModelOpen(true)}><span className="model-core-art" aria-hidden="true">AI</span><span><b>{s.aiName??'AURA'} · Q{s.qualityLevel} / E{s.efficiencyLevel}</b><small>{s.activeTraining?`${s.settings.language==='de'?'Training':'Training'} ${num(s.training/goal*100,0)} %`:wt(s.settings.language,'modelEquipment')}</small></span><span aria-hidden="true">›</span></button></section><div className="workshop-scroll" data-scroll-region="workshop-content">{(shoppingAgentUnlocked(s)||upgradeLevel(s,'componentScanner')>0)&&<section className="card early-automation"><b>{s.settings.language==='de'?'Automation':'Automation'}</b>{shoppingAgentUnlocked(s)&&(['calculator','sbc'] as HardwareId[]).map(id=><button key={id} className={s.hardwareAutoBuyers[id]?'owned':''} onClick={()=>act('auto-class',id)}>{hardwareText(id,s.settings.language).name}: {s.hardwareAutoBuyers[id]?(s.settings.language==='de'?'An':'On'):(s.settings.language==='de'?'Aus':'Off')}</button>)}</section>}<HardwareStore s={s} act={act}/></div>{modelOpen&&<MobileDetailSheet title={s.settings.language==='de'?'Modell & Training':'Model & training'} art={<span className="model-core-art">AI</span>} onClose={()=>setModelOpen(false)} action={<button onClick={()=>{setModelOpen(false);act('open-equipment')}}>{wt(s.settings.language,'modelEquipment')}</button>}>{trainingPanel}</MobileDetailSheet>}</div>
}
export function Research({s,act}:{s:GameState;act:Action}){
 const language=s.settings.language,de=language==='de',[view,setView]=useState<'research'|'analysis'|'breakthroughs'>('research'),unlocked=s.discovered.includes('sbc'),slots=researchLabCount(s),repeatableIds=Object.keys(BALANCE.repeatableResearch) as RepeatableResearchId[],freeLab=s.researchLabs.some((x,i)=>i<slots&&!x);
 const projectName=(id:ResearchId)=>isRepeatableResearch(id)?researchText(id,language).name:projectText(id,language).name;
 const tabKey=(event:React.KeyboardEvent<HTMLDivElement>)=>{const tabs=['research','analysis','breakthroughs'] as const,index=tabs.indexOf(view);if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();setView(tabs[(index+(event.key==='ArrowRight'?1:2))%3]);}};
 const block=(dataCost:number,requirement:RepeatableResearchId|null,running:boolean,done=false)=>done?(de?'Bereits abgeschlossen':'Already completed'):!unlocked?g(language,'discoverSbc'):requirement?`${g(language,'requirement')}: ${researchText(requirement,language).name} ${g(language,'level')} 1`:running?(de?'Projekt läuft bereits':'Project already running'):!freeLab?(de?'Alle Forschungslabore belegt':'All research labs occupied'):s.data<dataCost?`${num(dataCost-s.data)} ${g(language,'data')} ${g(language,'missing')}`:null;
 return <div className="panel research-panel mobile-screen">
  <header className="mobile-screen-title"><div><small>{de?'LABORNETZ':'LAB NETWORK'}</small><h1>{de?'Forschung':'Research'}</h1></div><b>{s.researchFragments} {g(language,'fragments')}</b></header>
  {!unlocked&&<p className="locked-next">{g(language,'discoverSbc')}</p>}
  <div className="research-tabs" role="tablist" aria-label={de?'Forschungsbereiche':'Research sections'} onKeyDown={tabKey}>{([['research',de?'Forschung':'Research'],['analysis',de?'Materialanalysen':'Material analyses'],['breakthroughs',g(language,'breakthroughs')]] as const).map(([id,label])=><button id={`tutorial-subtab-${id}`} key={id} role="tab" aria-selected={view===id} tabIndex={view===id?0:-1} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</div>

  {view==='research'&&<div role="tabpanel" className="research-view">
   <section className="grid lab-slots">{s.researchLabs.slice(0,slots).map((lab,index)=>{const progress=lab?Math.min(1,(s.savedAt-lab.startedAt)/(lab.endsAt-lab.startedAt)):0;return <article className="card lab-slot" key={index}><h3>{g(language,'lab')} {index+1}</h3>{lab?<><b>{projectName(lab.id)} · {g(language,'level')} {lab.level}</b><div className="bar"><i style={{width:`${progress*100}%`}}/></div><small>{num(progress*100,0)} % · {g(language,'remaining')} {num(Math.max(0,lab.endsAt-s.savedAt)/1000,1)} s</small></>:<p>{g(language,'readyProject')}</p>}</article>})}</section>
   {slots<s.researchLabs.length&&(()=>{const next=slots+1,offer=next===3?'lab-slot-1':next===4?'lab-slot-2':null,cost=offer?BALANCE.gemShop.labSlots[next-3]:null,requiresPrestige=next===2&&!s.nodes.includes('labs1');return <article className="lab-slot lab-unlock" data-lab-unlock="next"><div><h3>{g(language,'lab')} {next}</h3><b>🔒 {de?'Gesperrt':'Locked'}</b><small>{requiresPrestige?(de?'Voraussetzung: Parallel-Lab im Prestige-Baum':'Requirement: Parallel Lab in prestige tree'):`💎 ${cost}`}</small></div>{offer&&<button disabled={!s.nodes.includes('labs1')||s.gems<(cost??0)} onClick={()=>act('gem-offer',offer)}>{de?'FREISCHALTEN':'UNLOCK'}</button>}</article>})()}
   <h2>{g(language,'oneTime')}</h2><section className="grid research-projects">{(Object.keys(BALANCE.researchProjects) as ResearchProjectId[]).map(id=>{const p=BALANCE.researchProjects[id],copy=projectText(id,language),cost=researchProjectDataCost(id),running=s.researchLabs.some(x=>x?.id===id),done=s.completedResearch.includes(id),reason=block(cost,null,running,done);return <article id={`research-${id}`} tabIndex={-1} className="card research-card" key={id}><h3>{copy.name}</h3><p>{copy.effect}</p><div className="effect-step"><b>{de?'Wirkung':'Effect'}</b><span>{done?(de?'Aktiv':'Active'):(de?'Nicht aktiv → Freigeschaltet':'Inactive → Unlocked')}</span></div><small>{num(cost)} {g(language,'data')} · {num(researchDurationAtStart(s,id,1)/60,1)} Min.</small><button disabled={!!reason} onClick={()=>act('research-project',id)}>{reason?'🔒':g(language,'startProject')}</button><details><summary><span aria-hidden="true">ⓘ</span><span>{de?'Details':'Details'}</span></summary><p>{copy.effect}</p></details></article>})}</section>
   <h2>{g(language,'repeatable')}</h2><section className="grid research-projects">{repeatableIds.map(id=>{const p=BALANCE.repeatableResearch[id],copy=researchText(id,language),level=s.researchLevels[id],next=level+1,duration=researchDurationAtStart(s,id,next),cost=repeatableResearchDataCost(id,next),requirement=researchRequirement(s,id),running=s.researchLabs.some(x=>x?.id===id),reason=block(cost,requirement,running);return <article id={id==='dataGeneration'&&s.story.tutorial==='active'&&s.story.target==='research'?'tutorial-data-generation':`research-${id}`} tabIndex={id==='dataGeneration'?-1:undefined} className="card research-card" key={id}><small>{copy.category}</small><h3>{copy.name} · {g(language,'level')} {level}</h3><p>{copy.effect}</p><div className="effect-step"><b>{g(language,'current')} → {g(language,'nextLevel')}</b><span>+{num(level*p.effectPerLevel*100,0)} % → +{num(next*p.effectPerLevel*100,0)} %</span></div><small>{num(cost)} {g(language,'data')} · {num(duration/60,1)} Min.</small><button disabled={!!reason} onClick={()=>act('research-project',id)}>{reason?'🔒':`${g(language,'level')} ${next} · ${g(language,'start')}`}</button>{upgradeLevel(s,'labs2')>0&&!running&&<button onClick={()=>act('research-queue',id)}>{s.researchQueue.includes(id)?g(language,'queued'):g(language,'queue')}</button>}<details><summary><span aria-hidden="true">ⓘ</span><span>{de?'Details':'Details'}</span></summary><p>{requirement?`${g(language,'requirement')}: ${researchText(requirement,language).name} ${g(language,'level')} 1`:de?'Keine weitere Voraussetzung.':'No further requirement.'}</p></details></article>})}</section>
  </div>}

  {view==='analysis'&&<div role="tabpanel" className="analysis-view"><section className={`card analysis-slot ${s.experiments.active?'occupied':''}`}><h2>{de?'Analyseslot':'Analysis slot'}</h2>{s.experiments.active?<><b>{experimentText(s.experiments.active.type,language)}</b><div className="bar"><i style={{width:`${Math.min(100,(s.savedAt-s.experiments.active.startedAt)/(s.experiments.active.endsAt-s.experiments.active.startedAt)*100)}%`}}/></div><small>{g(language,'remaining')} {num(Math.max(0,s.experiments.active.endsAt-s.savedAt)/1000,0)} s</small></>:<p>{de?'Frei · unabhängig von Forschungslaboren':'Available · independent from research labs'}</p>}</section>
   {!s.experiments.active&&s.experiments.lastResult&&<section className="card analysis-result-card"><b>{de?'Analyse abgeschlossen':'Analysis complete'} · {experimentText(s.experiments.lastResult.type,language)}</b><div className="result-items">{componentIds.filter(id=>(s.experiments.lastResult?.components[id]??0)>0).map(id=><div key={id}><ComponentArt id={id}/><span>{componentText(id,language).name}</span><strong>+{s.experiments.lastResult?.components[id]}</strong></div>)}</div><div className="result-actions"><button onClick={()=>act('experiment',s.experiments.lastResult!.type,s.experiments.lastResult!.length)}>{de?'Erneut starten':'Start again'}</button><button onClick={()=>act('open-inventory')}>{de?'Inventar':'Inventory'}</button></div></section>}
   <section className="grid analysis-grid">{(['hardware','architecture','artifact'] as ExperimentId[]).map(id=>{const reward=BALANCE.experimentRewards[id];return <article className="card analysis-card" key={id}><ActivityArt id={id}/><h3>{experimentText(id,language)}</h3><p><b>{de?'Garantiert':'Guaranteed'}:</b> {reward.components} {g(language,'components')}{reward.blueprints?` · ${reward.blueprints} ${g(language,'blueprintFragments')}`:''}{reward.research?` · ${reward.research} ${g(language,'fragments')}`:''}</p><p><b>{de?'Zufallsfunde':'Random finds'}:</b> {reward.itemChance?`${num(reward.itemChance*100,0)} % Item`:(de?'keine Items':'no items')}</p>{(['short','long'] as const).map(length=>{const cost=analysisCost(id,length),reason=analysisBlockReason(s,id,length,de?'de':'en'),duration=experimentDuration(id,length)/experimentSpeed(s),scale=length==='short'?1/24:1;return <div className="analysis-option" key={length}><b>{length==='short'?g(language,'short'):g(language,'long')}</b><small>{num(cost.data)} {g(language,'data')} · {num(duration/60,1)} Min. · {de?'garantiertes Minimum':'guaranteed minimum'} {Math.floor(reward.components*scale)} {g(language,'components')}</small><button id={id==='hardware'&&length==='short'?'tutorial-hardware-analysis':undefined} disabled={!!reason} onClick={()=>act('experiment',id,length)}>{reason?'🔒':`${length==='short'?g(language,'short'):g(language,'long')} · ${g(language,'start')}`}</button></div>})}<details><summary>{de?'Mögliche Komponenten':'Possible components'}</summary><div className="analysis-drops">{analysisDropTable(s,id).map(drop=><div key={drop.id}><ComponentArt id={drop.id}/><span>{componentText(drop.id,language).name} · {num(drop.chance*100,1)} %</span></div>)}</div></details></article>})}</section>
  </div>}

  {view==='breakthroughs'&&<div role="tabpanel" className="breakthrough-view"><p>{de?'Forschungsfragmente':'Research fragments'}: <b>{s.researchFragments}</b></p>{(['distillation','graph','planning'] as BreakthroughId[]).map(id=>{const copy=breakthroughText(id,language),cost=BALANCE.breakthroughs[id][0],owned=s.breakthroughs.includes(id);return <article className="row card" key={id}><div><b>{copy.name}</b><small>{copy.effect} · {de?'Voraussetzung: keine weitere':'Requirement: none'}</small></div><button disabled={owned||s.researchFragments<cost} onClick={()=>act('breakthrough',id)}>{owned?g(language,'researched'):`${cost} ${g(language,'fragments')}`}</button></article>})}</div>}
 </div>
}
export function Inventory({s,act}:{s:GameState;act:Action}){
 const language=s.settings.language,[view,setView]=useState<'components'|'items'|'workbench'>('components'),[component,setComponent]=useState<(typeof componentIds)[number]|null>(null),[itemId,setItemId]=useState<string|null>(null),item=s.inventory.find(entry=>entry.id===itemId),equipped=Object.values(s.equipped).filter(Boolean).length,slots=equipmentSlotCount(s);
 return <div className="panel mobile-screen inventory-screen">
  <header className="mobile-screen-title"><div><small>{g(language,'inventory')}</small><h1>{language==='de'?'Inventar':'Inventory'}</h1></div><button className="equipment-summary" onClick={()=>act('open-equipment')}><span>◇</span><b>{equipped}/{slots}</b><small>{g(language,'equipment')}</small></button></header>
  <div className="mobile-segments" role="tablist">{(['components','items','workbench'] as const).map(tab=><button key={tab} role="tab" aria-selected={view===tab} className={view===tab?'active':''} onClick={()=>setView(tab)}>{tab==='components'?(language==='de'?'Komponenten':'Components'):tab==='items'?(language==='de'?'Items':'Items'):(language==='de'?'Werkbank':'Workbench')}</button>)}</div>
  {view==='components'&&<><div className="inventory-caption"><b>{g(language,'componentInventory')}</b><span>{s.blueprintFragments} {g(language,'blueprintFragments')}</span></div><section id="tutorial-components" tabIndex={-1} className="mobile-component-grid">{componentIds.map(id=><button className={`component-tile rarity-${componentRarity(BALANCE.components[id].rarity)}`} key={id} onClick={()=>setComponent(id)}><ComponentArt id={id}/><strong>×{s.componentInventory[id]}</strong><span>{componentText(id,language).name}</span><small>{rarityText(componentRarity(BALANCE.components[id].rarity),language)}</small></button>)}</section></>}
  {view==='items'&&<><section className={`equipment-strip ${slots?'':'locked'}`} onClick={()=>act('open-equipment')}><span className="equipment-orb">◇</span><div><b>{g(language,'equipment')}</b><small>{slots?`${equipped}/${slots} ${g(language,'slots')}`:(language==='de'?'Wird nach dem ersten Prestige freigeschaltet':'Unlocks after the first prestige')}</small></div><span>›</span></section><section className="mobile-item-grid">{(Object.keys(itemTypes) as ItemTypeId[]).map(type=>{const entry=s.inventory.find(candidate=>candidate.type===type);return entry?<button className={`item-tile rarity-${entry.rarity}`} key={entry.id} onClick={()=>setItemId(entry.id)}><ItemArt type={entry.type}/><span>{itemText(entry.type,language)}</span><small>{rarityText(entry.rarity,language)} · Lv {entry.level}</small>{Object.values(s.equipped).includes(entry.id)&&<i>{g(language,'equipped')}</i>}</button>:<button className="item-tile locked" key={type} disabled><ItemArt type={type}/><span>{itemText(type,language)}</span><small>🔒 {language==='de'?'Noch nicht entdeckt':'Not discovered'}</small></button>})}</section></>}
  {view==='workbench'&&<><section className="craft-status">{s.crafting.active?(()=>{const job=s.crafting.active!,remaining=Math.max(0,((job.endsAt??s.savedAt)-s.savedAt)/1000),progress=Math.max(0,Math.min(1,1-remaining/job.durationPerUnit));return <><ActivityArt id="workbench"/><div><b>{String(job.recipeId)}</b><small>{num(remaining,0)} s {g(language,'remaining')}</small><div className="bar"><i style={{width:`${progress*100}%`}}/></div></div></>})():<><ActivityArt id="workbench"/><div><b>{language==='de'?'Werkbank bereit':'Workbench ready'}</b><small>{language==='de'?'Wähle unten einen Bauplan.':'Choose a blueprint below.'}</small></div></>}</section>{s.crafting.queue.length>0&&<section className="craft-queue"><b>{language==='de'?'Warteschlange':'Queue'} · {s.crafting.queue.length}/3</b>{s.crafting.queue.map(job=><div key={job.id}><span>{String(job.recipeId)} ×{job.quantity}</span><button onClick={()=>act('craft-cancel',job.id)}>×</button></div>)}</section>}<h2>{g(language,'blueprints')}</h2><section className="craft-list">{(Object.keys(BALANCE.itemRecipes) as (keyof typeof BALANCE.itemRecipes)[]).map(type=>{const recipe=BALANCE.itemRecipes[type],afford=craftAffordability(s,type),missing=componentIds.some(id=>(recipe.ingredients[id]??0)>s.componentInventory[id]),blocked=!afford.unlocked||missing||Object.values(afford.missingModules).some(Number)||afford.data.missing>0||afford.missingBlueprints>0||s.crafting.queue.length>=3;return <article key={type}><ItemArt type={type}/><div><b>{recipeText(type,language)}</b><small>{rarityText(recipe.rarity,language)} · {num('duration'in recipe?recipe.duration:BALANCE.craftingSeconds[recipe.rarity],0)} s</small></div><button id={`tutorial-recipe-${type}`} disabled={blocked} onClick={()=>act('craft',type,recipe.rarity,1)}>{g(language,'craftPermanent')}</button></article>})}</section></>}
  {component&&<MobileDetailSheet title={componentText(component,language).name} art={<ComponentArt id={component}/>} onClose={()=>setComponent(null)}><div className="detail-quantity">×{s.componentInventory[component]}</div><p><b>{g(language,'source')}:</b> {componentText(component,language).source}</p><p><b>{language==='de'?'Seltenheit':'Rarity'}:</b> {rarityText(componentRarity(BALANCE.components[component].rarity),language)}</p><p>{language==='de'?'Wird für Module, Baupläne und Item-Verbesserungen verwendet.':'Used for modules, blueprints, and item upgrades.'}</p></MobileDetailSheet>}
  {item&&<MobileDetailSheet title={itemText(item.type,language)} art={<ItemArt type={item.type}/>} onClose={()=>setItemId(null)} action={<button className="primary" disabled={s.prestigeCount<1} onClick={()=>act('equip',item.id)}>{g(language,'equip')}</button>}><p><b>{rarityText(item.rarity,language)} · {g(language,'level')} {item.level}</b></p><p>{item.type==='impulse-relay'?effectText('relay',language):`${g(language,'base')} +${num(itemEffect(item)*100)} % ${effectText(itemTypes[item.type].effect,language)}`}</p><div className="sheet-actions"><button onClick={()=>act('lock',item.id)}>{item.locked?g(language,'unlock'):g(language,'lock')}</button><button onClick={()=>act('forge',item.id)}>{g(language,'forge')} +{item.forge??0}</button><button disabled={item.locked||Object.values(s.equipped).includes(item.id)} onClick={()=>act('salvage',item.id)}>{g(language,'salvage')}</button></div></MobileDetailSheet>}
 </div>
}
export function Shop({s,act}:{s:GameState;act:Action}){return <div className="panel mobile-screen shop-screen"><header className="mobile-screen-title"><div><small>AI SINGULARITY</small><h1>{s.settings.language==='de'?'Shop':'Shop'}</h1></div><b>💎 {s.gems}</b></header><GemShop s={s} act={act}/></div>}

export function Prestige({s,act}:{s:GameState;act:Action}){
 const language=s.settings.language,de=language==='de',[selected,setSelected]=useState<PrestigeUpgradeId|null>(null),[confirming,setConfirming]=useState(false),[prestigeDetails,setPrestigeDetails]=useState(false),[prestigeLayer,setPrestigeLayer]=useState<'int'|'axiom'>('int'),[axiomConfirming,setAxiomConfirming]=useState(false),preview=prestigePreview(s),claim=preview.claimableINT,nextNeed=Math.max(0,nextPrestigeThreshold(s)-s.cycleEligibleCredits),firstNeed=Math.max(0,BALANCE.prestigeBaseRevenue*9-s.cycleEligibleCredits),ids=Object.keys(prestigeUpgrades) as PrestigeUpgradeId[],chosen=selected?prestigeUpgrades[selected]:null,compatibleItem=s.inventory.some(item=>!s.equipped[itemTypes[item.type].slot]),treeRef=useRef<HTMLDivElement>(null),closeRef=useRef<HTMLButtonElement>(null),returnFocus=useRef<HTMLElement|null>(null),axiomTriggerRef=useRef<HTMLButtonElement>(null),axiomDialogRef=useRef<HTMLButtonElement>(null),catalogCheck=validatePrestigeCatalog();
 const [mapView,setMapView]=useState({x:0,y:0,scale:.4}),pointers=useRef(new Map<number,{x:number;y:number}>()),gesture=useRef<{distance:number;center:{x:number;y:number};view:{x:number;y:number;scale:number}}|null>(null);
 const clampScale=(value:number)=>Math.max(.28,Math.min(1.5,value));
 const fitTree=useCallback(()=>{const viewport=treeRef.current;if(!viewport)return;const scale=clampScale(Math.min((viewport.clientWidth-20)/PRESTIGE_CANVAS.width,(viewport.clientHeight-20)/PRESTIGE_CANVAS.height));setMapView({scale,x:(viewport.clientWidth-PRESTIGE_CANVAS.width*scale)/2,y:(viewport.clientHeight-PRESTIGE_CANVAS.height*scale)/2})},[]);
 const zoomMap=(factor:number)=>{const viewport=treeRef.current;if(!viewport)return;setMapView(view=>{const scale=clampScale(view.scale*factor),cx=viewport.clientWidth/2,cy=viewport.clientHeight/2;return{scale,x:cx-(cx-view.x)*scale/view.scale,y:cy-(cy-view.y)*scale/view.scale}})};
 const mapPointerDown=(event:ReactPointerEvent<HTMLDivElement>)=>{event.currentTarget.setPointerCapture(event.pointerId);pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});const points=[...pointers.current.values()];gesture.current=points.length===2?{distance:Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y),center:{x:(points[0].x+points[1].x)/2,y:(points[0].y+points[1].y)/2},view:mapView}:null};
 const mapPointerMove=(event:ReactPointerEvent<HTMLDivElement>)=>{const previous=pointers.current.get(event.pointerId);if(!previous)return;const before=[...pointers.current.values()];pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});const points=[...pointers.current.values()];if(points.length===1){setMapView(view=>({...view,x:view.x+event.clientX-previous.x,y:view.y+event.clientY-previous.y}));return}if(points.length===2&&gesture.current){const distance=Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y),center={x:(points[0].x+points[1].x)/2,y:(points[0].y+points[1].y)/2},start=gesture.current,scale=clampScale(start.view.scale*distance/Math.max(1,start.distance));setMapView({scale,x:center.x-(start.center.x-start.view.x)*scale/start.view.scale,y:center.y-(start.center.y-start.view.y)*scale/start.view.scale})}};
 const mapPointerUp=(event:ReactPointerEvent<HTMLDivElement>)=>{pointers.current.delete(event.pointerId);gesture.current=null};
 const status=(id:PrestigeUpgradeId)=>{const node=prestigeUpgrades[id],owned=upgradeLevel(s,id)>0,missing=node.requires.filter(x=>!upgradeLevel(s,x as PrestigeUpgradeId));return{node,owned,missing,cost:prestigeUpgradeCost(id),available:!owned&&!missing.length&&(!('requiresPrestige' in node)||s.prestigeCount>0)&&exactEconomyValue(s,'unspentINT').compare(prestigeUpgradeCostScientific(id))>=0}};

 const revenueText=(amount:number,first=false)=>{
  const x=num(amount);
  if(language==='de')return `Noch ${x} berechtigter Umsatz bis zur ${first?'ersten INT':'nächsten zusätzlichen INT'}.`;
  if(language==='es')return `Faltan ${x} de ingresos elegibles para ${first?'el primer INT':'el siguiente INT adicional'}.`;
  if(language==='fr')return `Encore ${x} de revenu éligible avant ${first?'le premier INT':'le prochain INT supplémentaire'}.`;
  if(language==='pt')return `Faltam ${x} de receita elegível para ${first?'o primeiro INT':'o próximo INT adicional'}.`;
  if(language==='it')return `Mancano ${x} ricavi idonei per ${first?'il primo INT':'il prossimo INT aggiuntivo'}.`;
  if(language==='pl')return `Pozostało ${x} kwalifikowanego przychodu do ${first?'pierwszego INT':'następnego dodatkowego INT'}.`;
  return `${x} eligible revenue remaining until ${first?'the first INT':'the next additional INT'}.`;
 };

 const resetLost=de?'Run-Credits, Run-Daten, Hardware, Nutzer/Kapazität, Klassen-Upgrades und Modelllevel. Laufendes Training und die aktive Analyse werden ohne Erstattung abgebrochen.':'Run credits, run data, hardware, users/capacity, class upgrades, and model levels. Active training and analysis are cancelled without a refund.';

 const resetKept=de?'INT, Prestige-Knoten, Komponenten, Module, Items, Baupläne/Fragmente, Equipment, Achievements, Gems sowie laufende Forschung und Crafting-Aufträge.':'INT, prestige nodes, components, modules, items, blueprints/fragments, equipment, achievements, gems, running research, and crafting jobs.';
 const axiom=axiomPreview(s);
 const layerTabs=<nav className="prestige-layer-tabs" aria-label={de?'Prestige-Ebene':'Prestige layer'}><button className={prestigeLayer==='int'?'active':''} onClick={()=>setPrestigeLayer('int')}>INT</button><button className={prestigeLayer==='axiom'?'active':''} onClick={()=>setPrestigeLayer('axiom')}>{de?'Axiome':'Axioms'}</button></nav>;

 useEffect(()=>{if(!selected)return;closeRef.current?.focus();const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setSelected(null)};window.addEventListener('keydown',escape);return()=>{window.removeEventListener('keydown',escape);returnFocus.current?.focus()}},[selected]);
 useEffect(()=>{if(!axiomConfirming)return;axiomDialogRef.current?.focus();const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setAxiomConfirming(false)};window.addEventListener('keydown',escape);return()=>{window.removeEventListener('keydown',escape);axiomTriggerRef.current?.focus()}},[axiomConfirming]);
 const openNode=(id:PrestigeUpgradeId,event:MouseEvent<HTMLButtonElement>)=>{returnFocus.current=event.currentTarget;setSelected(id)};
 useEffect(()=>{if(prestigeLayer!=='int')return;const viewport=treeRef.current;if(!viewport)return;const observer=new ResizeObserver(fitTree);observer.observe(viewport);requestAnimationFrame(fitTree);return()=>observer.disconnect()},[fitTree,prestigeLayer]);

 if(prestigeLayer==='axiom'){
  const upgrades=[
   {id:'axiomResonance' as const,name:de?'Axiom-Resonanz':'Axiom Resonance',text:de?'+10 % auf künftig verbuchten normalen INT-Anspruch je Stufe (maximal 10).':'+10% to future normal INT entitlement per level (maximum 10).',art:<ResourceArt id="int"/>},
   {id:'axiomAutomation' as const,name:de?'Axiom-Automation':'Axiom Automation',text:de?'Schaltet den permanenten Auto-Prestige-Agenten frei.':'Unlocks the permanent auto-prestige agent.',art:<PrestigeArt id="shoppingAgent"/>},
   {id:'axiomArchive' as const,name:de?'Axiom-Archiv':'Axiom Archive',text:de?'+25 % Komponenten aus passiven Quellen, ohne zusätzliche Fundwürfe.':'+25% components from passive sources without additional drop rolls.',art:<ComponentArt id="circuits"/>}
  ];
  const agentReason=prestigeAgentStatus(s),reasonText:Record<string,string>=de?{locked:'Nicht freigeschaltet',disabled:'Deaktiviert','insufficient-int':'Mindest-INT nicht erreicht','minimum-runtime':'Mindestlaufzeit nicht erreicht','training-active':'Wartet auf Training','analysis-active':'Wartet auf Analyse',ready:'Bereit'}:{locked:'Locked',disabled:'Disabled','insufficient-int':'Minimum INT not met','minimum-runtime':'Minimum run time not met','training-active':'Waiting for training','analysis-active':'Waiting for analysis',ready:'Ready'};
  return <div className="panel axiom-panel"><h2>{g(language,'singularity')}</h2>{layerTabs}<section className="axiom-hero"><ResourceArt id="int"/><div><small>{de?'ZWEITE PRESTIGE-EBENE':'SECOND PRESTIGE LAYER'}</small><h2>{de?'Axiome':'Axioms'}</h2><p>{de?'Nur tatsächlich durch normale Prestiges verdiente Zyklus-INT zählen.':'Only cycle INT actually earned through normal prestiges count.'}</p></div></section>
   <section className="axiom-stats"><article><small>{de?'Zyklus-INT':'Cycle INT'}</small><b>{num(s.cycleINTEarned,0)}</b></article><article><small>{de?'Nächste Schwelle':'Next threshold'}</small><b>{num(axiom.nextThreshold,0)} INT</b></article><article><small>{de?'Jetzt erhältlich':'Available now'}</small><b>{axiom.reward}</b></article><article><small>{de?'Verfügbar / insgesamt':'Available / total'}</small><b>{s.availableAxioms} / {s.totalAxiomsEarned}</b></article><article><small>{de?'Permanenter Creditbonus':'Permanent credit bonus'}</small><b>×{num(axiom.creditBonusBefore,2)}</b></article></section>
   <section className="axiom-upgrades" aria-label={de?'Permanente Axiom-Knoten':'Permanent Axiom nodes'}>{upgrades.map(card=>{const level=s.axiomUpgradeLevels[card.id],max=card.id==='axiomResonance'?BALANCE.axiom.resonanceMax:1,cost=axiomUpgradeCost(card.id),owned=level>=max,affordable=s.availableAxioms>=cost;return <article className={`axiom-upgrade-card ${owned?'owned':affordable?'available':'locked'}`} key={card.id}>{card.art}<div><h3>{card.name}</h3><p>{card.text}</p><small>{de?'Stufe':'Level'} {level}/{max} · {cost} {de?'Axiomkosten':'Axiom cost'}</small></div><button disabled={owned||!affordable} onClick={()=>act('axiom-upgrade',card.id)}>{owned?(de?'Maximal':'Maximum'):(de?`${cost} kaufen`:`Buy for ${cost}`)}</button></article>})}</section>
   {(s.axiomUpgradeLevels.axiomAutomation??0)>0&&<section className="axiom-planner-settings" aria-label={de?'Prestige-Agent':'Prestige agent'}><h3>{de?'Prestige-Agent':'Prestige Agent'}</h3><p><b>{de?'Status':'Status'}:</b> {reasonText[agentReason]??agentReason} · {de?'Nächste Prüfung':'Next check'}: {num(Math.max(0,10-s.prestigeAgent.elapsed),0)} s · {de?'Erwartet':'Expected'}: {num(newINT(s),0)} INT</p><button className={s.prestigeAgent.enabled?'owned':''} onClick={()=>act('prestige-agent-enabled')}>{de?'Auto-Prestige':'Auto prestige'}: {s.prestigeAgent.enabled?(de?'An':'On'):(de?'Aus':'Off')}</button><label>{de?'Mindest-INT':'Minimum INT'}<input inputMode="decimal" defaultValue={ScientificNumber.fromJSON(s.prestigeAgent.minimumReward).toScientificString(3)} onBlur={e=>act('prestige-agent-reward',e.currentTarget.value)}/></label><label>{de?'Mindestlaufzeit':'Minimum run time'}<select value={s.prestigeAgent.minimumRunMinutes} onChange={e=>act('prestige-agent-minutes',Number(e.target.value))}>{[15,30,60,120].map(value=><option key={value} value={value}>{value} min</option>)}</select></label><label><input type="checkbox" checked={s.prestigeAgent.waitForTraining??true} onChange={()=>act('prestige-agent-wait-training')}/>{de?'Auf Training warten':'Wait for training'}</label><label><input type="checkbox" checked={s.prestigeAgent.waitForAnalysis??true} onChange={()=>act('prestige-agent-wait-analysis')}/>{de?'Auf Analyse warten':'Wait for analysis'}</label><small>{de?'Verwendet nur den normalen Prestige-Pfad und löst niemals einen Axiom-Reset aus.':'Uses only the normal prestige path and never triggers an Axiom reset.'}</small></section>}
   <p className="axiom-bonus-note">{de?'Ausgeben reduziert deinen permanenten Axiom-Bonus nicht.':'Spending does not reduce your permanent Axiom bonus.'}</p><p className="axiom-warning">{de?`${num(axiom.discardedCycleINT,0)} Zyklus-INT verfallen beim Reset.`:`${num(axiom.discardedCycleINT,0)} cycle INT will be discarded by the reset.`}</p><button ref={axiomTriggerRef} className="primary" disabled={axiom.reward<1} onClick={()=>setAxiomConfirming(true)}>{axiom.reward<1?(de?'Noch kein Axiom':'No axiom yet'):(de?`${axiom.reward} Axiom${axiom.reward===1?'':'e'} beanspruchen`:`Claim ${axiom.reward} axiom${axiom.reward===1?'':'s'}`)}</button>
   {axiomConfirming&&<div className="prestige-confirm-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setAxiomConfirming(false)}><section className="prestige-confirm" role="dialog" aria-modal="true" aria-labelledby="axiom-confirm-title"><h2 id="axiom-confirm-title">{de?'Axiom-Reset bestätigen':'Confirm axiom reset'}</h2><p>{de?'Axiome':'Axioms'}: {s.availableAxioms} → {axiom.availableAfter} · {de?'Bonus':'bonus'} ×{num(axiom.creditBonusBefore,2)} → ×{num(axiom.creditBonusAfter,2)}</p><h3>{de?'Geht verloren':'Will be lost'}</h3><ul><li>{de?'Credits, Data, Hardware, Klassen-Upgrades und Modell-/Trainingfortschritt':'Credits, data, hardware, class upgrades, and model/training progress'}</li><li>{de?'Training, Trainingsqueue sowie aktive und wartende Analysen':'Training, training queue, and active/queued analyses'}</li><li>{de?'Verfügbare/ausgegebene INT, INT-Knoten, Zyklusumsatz und Anspruch':'Available/spent INT, INT nodes, cycle revenue, and entitlement'}</li></ul><h3>{de?'Bleibt erhalten':'Will be kept'}</h3><ul><li>{de?'Axiome und Axiom-Knoten; Komponenten, Module, Baupläne, Items und Ausrüstung':'Axioms and Axiom nodes; components, modules, blueprints, items, and equipment'}</li><li>{de?'Abgeschlossene/laufende Forschung und Crafting-Aufträge mit Reservierungen':'Completed/running research and crafting jobs with reservations'}</li><li>{de?'Gems, Labor-/Equipmentplätze, Achievements, Quests, Season, Profil und Story':'Gems, lab/equipment slots, achievements, quests, season, profile, and story'}</li></ul><div className="prestige-confirm-actions"><button ref={axiomDialogRef} onClick={()=>setAxiomConfirming(false)}>{de?'Zurück':'Back'}</button><button className="primary" disabled={axiomPreview(s).reward<1} onClick={()=>{if(axiomPreview(s).reward<1)return;setAxiomConfirming(false);act('axiom-reset')}}>{de?'Firma neu starten':'Restart company'}</button></div></section></div>}</div>;
 }

 return <div className="panel">
  <h2>{g(language,'singularity')}</h2>{layerTabs}
  <section className="prestige-summary" aria-label={de?'Prestige-Übersicht':'Prestige summary'}><span><small>INT</small><b>{num(s.unspentINT,2)}</b></span><span><small>{g(language,'prestigeNow')}</small><b>+{claim}</b></span><span><small>{de?'Bonus':'Bonus'}</small><b>×{num(preview.creditBonusBefore,2)} → ×{num(preview.creditBonusAfter,2)}</b></span></section>
  <div className="prestige-actions"><button id="tutorial-prestige-action" className="primary" disabled={claim<1} onClick={()=>setConfirming(true)}>{claim<1?g(language,'noInt'):`+${claim} INT ${g(language,'claim')}`}</button><button className="prestige-info" onClick={()=>setPrestigeDetails(true)}>ⓘ {de?'Prestige-Details':'Prestige details'}</button></div>
  {prestigeDetails&&<MobileDetailSheet title={de?'Prestige-Details':'Prestige details'} onClose={()=>setPrestigeDetails(false)}><p>{claim>0?revenueText(nextNeed):revenueText(firstNeed,true)}</p><p><b>{g(language,'lost')}:</b> {resetLost}</p><p><b>{g(language,'kept')}:</b> {resetKept}</p></MobileDetailSheet>}
  {confirming&&<div className="prestige-confirm-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setConfirming(false)}><section className="prestige-confirm" role="dialog" aria-modal="true" aria-labelledby="prestige-confirm-title"><h2 id="prestige-confirm-title">{de?`Du erhältst ${claim} INT`:`You receive ${claim} INT`}</h2><p>{de?'Dauerhafter Creditbonus':'Permanent credit bonus'}: ×{num(preview.creditBonusBefore,2)} → ×{num(preview.creditBonusAfter,2)}</p><p>{de?'Gesamt-INT danach':'Total INT afterwards'}: {num(preview.totalINTAfter,0)} · {de?'verfügbar':'available'}: {num(preview.availableINTAfter,0)}</p>{preview.firstEquipmentSlot&&<p className="prestige-first-slot">{de?'Dein erster Ausrüstungsplatz wird geöffnet.':'Your first equipment slot will be unlocked.'}</p>}<h3>{de?'Wird zurückgesetzt':'Will be reset'}</h3><ul><li>{de?'Credits und Data':'Credits and Data'}: {num(preview.reset.credits)} / {num(preview.reset.data)}</li><li>{de?'Hardware und Modelllevel':'Hardware and model levels'}: {num(preview.reset.hardware,0)} / Q{preview.reset.qualityLevel} E{preview.reset.efficiencyLevel}</li></ul><h3>{de?'Bleibt erhalten':'Will be kept'}</h3><ul><li>{de?'Komponenten / Zwischenprodukte / Items':'Components / intermediate products / items'}: {preview.kept.components} / {preview.kept.modules} / {preview.kept.items}</li><li>{de?'Bauplanfragmente / Gems / Achievements':'Blueprint fragments / gems / achievements'}: {preview.kept.blueprintFragments} / {preview.kept.gems} / {preview.kept.achievements}</li><li>{de?'Equipment-Plätze, Ausrüstung und Crafting-Aufträge':'Equipment slots, equipped items, and crafting jobs'}: {preview.kept.craftingJobs}</li></ul><h3>{de?'Laufende Aufträge':'Running jobs'}</h3>{preview.jobs.length?<ul>{preview.jobs.map((job,index)=><li className={job.status==='cancelled'?'prestige-warning':''} key={`${job.kind}-${index}`}>{job.kind}: {job.name} · {job.status==='continues'?(de?'läuft weiter':'continues'):(de?'wird ohne Erstattung abgebrochen':'cancelled without refund')} · {num(job.remainingSeconds,0)} s{job.lostData>0?` · ${num(job.lostData,0)} Data ${de?'verloren':'lost'}`:''}</li>)}</ul>:<p>{de?'Keine laufenden Aufträge.':'No running jobs.'}</p>}<div className="prestige-confirm-actions"><button onClick={()=>setConfirming(false)}>{de?'Zurück':'Back'}</button><button className="primary" disabled={prestigePreview(s).claimableINT<1} onClick={()=>{if(prestigePreview(s).claimableINT<1)return;setConfirming(false);act('prestige')}}>{de?'Prestige durchführen':'Perform prestige'}</button></div></section></div>}

  <div className="tree-heading"><h2>{g(language,'circuit')}</h2><span>{de?'Ziehen · Zwei Finger zum Zoomen':'Drag · pinch to zoom'}</span></div>
  <div className="branch-legend" aria-label={de?'Astfarben':'Branch colors'}>{BALANCE.prestigeBranches.map((name,index)=><span className={`branch-${index}`} key={name}><i/>{name}</span>)}<span className="branch-special"><i/>{de?'Werkzeuge':'Utilities'}</span></div>
  <p className="swipe-hint">↔ {de?'Seitlich wischen':'Swipe sideways'}</p>
  {(catalogCheck.unknown.length>0||catalogCheck.cycles.length>0)&&<p className="warning" role="alert">Prestige catalog invalid: {[...catalogCheck.unknown,...catalogCheck.cycles].join(', ')}</p>}
  <div className="prestige-map-shell">
   <div className="prestige-map-controls" aria-label={de?'Kartensteuerung':'Map controls'}><button onClick={()=>zoomMap(.8)} aria-label={de?'Verkleinern':'Zoom out'}>−</button><button onClick={fitTree}>{de?'Einpassen':'Fit tree'}</button><button onClick={()=>zoomMap(1.25)} aria-label={de?'Vergrößern':'Zoom in'}>+</button></div>
   <div className="prestige-viewport" ref={treeRef} tabIndex={0} aria-label={de?'Verschiebbare und zoombare Prestige-Karte':'Pannable and zoomable prestige map'} onPointerDown={mapPointerDown} onPointerMove={mapPointerMove} onPointerUp={mapPointerUp} onPointerCancel={mapPointerUp}>
   <div className="prestige-board" style={{width:PRESTIGE_CANVAS.width,height:PRESTIGE_CANVAS.height,transform:`translate3d(${mapView.x}px,${mapView.y}px,0) scale(${mapView.scale})`}} role="list">
    <div className="ai-core" style={{left:PRESTIGE_CANVAS.core.x,top:PRESTIGE_CANVAS.core.y}} aria-label="AURA Core">AURA<br/><small>CORE</small></div>
    <svg className="prestige-links" width={PRESTIGE_CANVAS.width} height={PRESTIGE_CANVAS.height} aria-hidden="true">{ids.flatMap(id=>prestigeUpgrades[id].requires.map(requirement=>{const from=prestigeLayout[requirement as PrestigeUpgradeId],to=prestigeLayout[id];return <path key={`${requirement}-${id}`} className={s.nodes.includes(requirement as PrestigeUpgradeId)?'active':''} d={`M ${from.x} ${from.y+PRESTIGE_CANVAS.nodeHeight/2} C ${from.x} ${from.y+82}, ${to.x} ${to.y-82}, ${to.x} ${to.y-PRESTIGE_CANVAS.nodeHeight/2}`}/> }))}</svg>
    {ids.map(id=>{const x=status(id),copy=prestigeText(id,language),state=prestigeNodeState(s,id),point=prestigeLayout[id],branch=x.node.branch<5?`branch-${x.node.branch}`:'branch-special',stateCopy=state==='owned'?(de?'Gekauft':'Purchased'):state==='affordable'?(de?'Kaufbar':'Purchasable'):state==='ready'?(de?'INT fehlt':'Needs INT'):(de?'Gesperrt':'Locked');return <button type="button" role="listitem" style={{left:point.x,top:point.y}} aria-label={`${copy.name}, ${stateCopy}`} className={`circuit-node ${branch} ${state}`} key={id} onClick={event=>openNode(id,event)}><PrestigeArt id={id}/><i aria-hidden="true">{state==='owned'?'✓':state==='affordable'?num(x.cost,0):'•'}</i></button>})}
   </div>
   </div>
  </div>

  {chosen&&selected&&(()=>{
   const anchored=selected==='shoppingAgent'&&s.axiomUpgrades.includes('anchoredShoppingAgent'),x=status(selected),copy=prestigeText(selected,language),next=ids.find(id=>prestigeUpgrades[id].requires.includes(selected as never));
   return <div className="node-backdrop" onClick={()=>setSelected(null)}>
    <section className="node-detail" role="dialog" aria-modal="true" aria-labelledby="node-title" onClick={e=>e.stopPropagation()}>
     <button ref={closeRef} className="close" aria-label={g(language,'close')} onClick={()=>setSelected(null)}>×</button>
     <PrestigeArt id={selected}/>
     <h3 id="node-title">{copy.name}</h3>
     <p><b>{g(language,'effect')}:</b> {copy.effect}</p>
     <p><b>{g(language,'formula')}:</b> {copy.effect}</p>{selected==='shoppingAgent'&&<p>{language==='de'?`Aktuell: Rechner ${s.hardwareAutoBuyers.calculator?'an':'aus'}, SBC ${s.hardwareAutoBuyers.sbc?'an':'aus'}, Reserve ${(s.automation.reservePercent??0)*100} %`:`Current: calculator ${s.hardwareAutoBuyers.calculator?'on':'off'}, SBC ${s.hardwareAutoBuyers.sbc?'on':'off'}, reserve ${(s.automation.reservePercent??0)*100}%`}</p>}{selected==='trainingPlan'&&<p>{language==='de'?`Aktuell: ${s.trainingQueue.length}/2 vorgemerkt`:`Current: ${s.trainingQueue.length}/2 queued`}</p>}{selected==='componentScanner'&&<p>{language==='de'?`Aktuelles Ziel: ${s.scannerTarget?componentText(s.scannerTarget,language).name:'keines'}`:`Current target: ${s.scannerTarget?componentText(s.scannerTarget,language).name:'none'}`}</p>}
     <p><b>{g(language,'currentValue')}:</b> {g(language,'level')} {upgradeLevel(s,selected)}</p>
     <div className="node-requirements"><b>{g(language,'requirement')}:</b> {'requiresPrestige' in chosen&&chosen.requiresPrestige&&<span className={s.prestigeCount>0?'met':'unmet'}>{s.prestigeCount>0?'✓':'○'} {de?'Erster Prestige':'First prestige'}</span>}{!('requiresPrestige' in chosen)&&!chosen.requires.length&&<span className="met">✓ AURA Core</span>}{chosen.requires.map(id=><span key={id} className={s.nodes.includes(id as PrestigeUpgradeId)?'met':'unmet'}>{s.nodes.includes(id as PrestigeUpgradeId)?'✓':'○'} {prestigeText(id as PrestigeUpgradeId,language).name}</span>)}</div>
     <p><b>{g(language,'nextNode')}:</b> {next?prestigeText(next,language).name:g(language,'branchComplete')}</p>
     <p><b>{g(language,'example')}:</b> {g(language,'level')} {upgradeLevel(s,selected)} → {upgradeLevel(s,selected)+1}</p>
     {selected==='shoppingAgent'&&(x.owned||anchored)&&<div className="node-settings"><button onClick={()=>act('auto-class','calculator')}>{de?'Rechner':'Calculator'}: {s.hardwareAutoBuyers.calculator?(de?'An':'On'):(de?'Aus':'Off')}</button><button onClick={()=>act('auto-class','sbc')}>SBC: {s.hardwareAutoBuyers.sbc?(de?'An':'On'):(de?'Aus':'Off')}</button><label>{de?'Reserve':'Reserve'}: {Math.round((s.automation.reservePercent??0)*100)} %<input type="range" min="0" max="90" step="5" value={(s.automation.reservePercent??0)*100} onChange={event=>act('auto-reserve',event.currentTarget.valueAsNumber/100)}/></label></div>}
     {selected==='trainingPlan'&&x.owned&&s.trainingQueue.length>0&&<div className="node-settings">{s.trainingQueue.map((job,index)=><button key={`${job.track}-${job.targetLevel}`} onClick={()=>act('train-queue-remove',index)}>× {job.track} {job.targetLevel}</button>)}</div>}
     {selected==='componentScanner'&&x.owned&&<label className="node-settings">{de?'Scannerziel':'Scanner target'}<select value={s.scannerTarget??''} onChange={event=>act('scanner-target',event.currentTarget.value||null)}><option value="">{de?'Keines':'None'}</option>{passiveComponentWeights({...s,scannerTarget:null}).map(row=><option key={row.id} value={row.id}>{componentText(row.id,language).name}</option>)}</select></label>}
     <button className="primary" disabled={!x.available||anchored} onClick={()=>act('node',selected)}>{anchored?(de?'Durch Axiom dauerhaft freigeschaltet':'Permanently unlocked by Axiom'):x.owned?g(language,'alreadyPurchased'):x.missing.length?g(language,'requirementMissing'):s.unspentINT<x.cost?`${num(x.cost,2)} INT ${g(language,'needed')}`:`${g(language,'buy')} · ${num(x.cost,2)} INT`}</button>
    </section>
   </div>
  })()}

  <p className="stats">INT {g(language,'total')} {num(s.totalINTEarned,2)} · {g(language,'available')} {num(s.unspentINT,2)} · {g(language,'spent')} {num(s.spentINT,2)}</p>
 </div>
}

export function Missions({s,act,mode='missions'}:{s:GameState;act:Action;mode?:'missions'|'season'}){const [kind,setKind]=useState<'daily'|'weekly'|'monthly'>('daily'),language=s.settings.language,de=language==='de',period=s.missions[kind],done=period.tasks.filter(task=>missionProgress(s,task)>=task.goal).length,remaining=Math.max(0,period.endsAt-s.savedAt);if(mode==='season')return <div className="panel mobile-screen season-screen"><MissionHub s={s} act={act} variant="season"/></div>;return <div className="panel mobile-screen missions-screen"><header className="mobile-screen-title"><div><small>{de?'AUFTRÄGE':'QUESTS'}</small><h1>{de?'Missionen':'Missions'}</h1></div><span>{num(remaining/3600000,1)} h</span></header><div className="mobile-segments mission-periods" role="tablist">{(['daily','weekly','monthly'] as const).map(tab=><button role="tab" aria-selected={kind===tab} className={kind===tab?'active':''} key={tab} onClick={()=>setKind(tab)}>{tab==='daily'?'Daily':tab==='weekly'?'Weekly':'Monthly'}</button>)}</div><section className="period-progress"><div><b>{de?'Periodenbonus':'Period bonus'}</b><span>{done}/{period.required}</span></div><div className="bar"><i style={{width:`${Math.min(100,done/period.required*100)}%`}}/></div><button disabled={done<period.required||period.bonusClaimed} onClick={()=>act('claim-bonus',kind)}>{period.bonusClaimed?'✓':`💎 ${period.bonus}`}</button></section><section className="mobile-mission-list">{period.tasks.map(task=>{const progress=missionProgress(s,task),ready=progress>=task.goal&&!task.claimed,percent=Math.min(100,progress/task.goal*100);return <article className={`mission-row ${ready?'claimable':task.claimed?'claimed':''}`} key={task.id}><div className="mission-icon"><MetaArt id={kind}/></div><div className="mission-content"><b className="mission-title">{missionText(task,language)}</b><div className="mission-progress"><div className="bar"><i style={{width:`${percent}%`}}/></div><small>{num(Math.min(progress,task.goal),0)} / {num(task.goal,0)}</small></div></div><span className="mission-reward">💎 {task.reward}</span><button className="mission-claim" disabled={!ready} onClick={()=>act('claim',kind,task.id)}>{task.claimed?'✓':ready?(de?'Abholen':'Claim'):'···'}</button></article>})}</section></div>}
