import {describe,expect,it} from 'vitest';
import {activateOverclock,BALANCE,GameState,buyClassUpgrade,buyHardwareClass,classCompute,hardwareBulkCost,hardwareCost,maxAffordable,milestoneFactor,newGame,newInsight,registerTap,tapCredits} from './economy';
import {completeExperiment,queueExperiment} from './experiments';
import {prestige} from './prestige';
import {advance} from './simulation';

describe('phase 1 hardware and active play',()=>{
  it('uses exact geometric bulk costs and corrected analytic max purchases',()=>{const s=newGame(0),sum=Array.from({length:10},(_,i)=>hardwareCost('calculator',1+i,s)).reduce((a,b)=>a+b,0);expect(hardwareBulkCost('calculator',1,10,s)).toBeCloseTo(sum,10);const max=maxAffordable('calculator',1,1000,s);expect(hardwareBulkCost('calculator',1,max,s)).toBeLessThanOrEqual(1000+1e-9);expect(hardwareBulkCost('calculator',1,max+1,s)).toBeGreaterThan(1000)});
  it('doubles class compute at 10, 25 and 50',()=>{expect(milestoneFactor(9)).toBe(1);expect(milestoneFactor(10)).toBe(2);expect(milestoneFactor(25)).toBe(4);expect(milestoneFactor(50)).toBe(8)});
  it('unlocks classes and buys a class upgrade only once',()=>{let s={...newGame(0),credits:1e9};s=buyHardwareClass(s,'calculator',9);expect(s.discovered).toContain('sbc');s=buyHardwareClass(s,'calculator',6);const before=classCompute(s,'calculator');s=buyClassUpgrade(s,'calculator');expect(classCompute(s,'calculator')).toBe(before*2);expect(buyClassUpgrade(s,'calculator')).toBe(s)});
  it('tap reward excludes temporary boosts and charges overclock',()=>{let s={...newGame(0),creditBoostUntil:1e9,overclock:{taps:0,charged:false,activeUntil:1e9,cooldownUntil:0}};expect(tapCredits(s,1)).toBe(tapCredits({...s,creditBoostUntil:0,overclock:{...s.overclock,activeUntil:0}},1));for(let i=0;i<BALANCE.overclockTaps;i++)s=registerTap(s,1);expect(s.overclock.charged).toBe(true);s=activateOverclock(s,1);expect(s.overclock.activeUntil).toBe(15001);expect(s.overclock.cooldownUntil).toBe(90001);expect(activateOverclock(s,2)).toBe(s)});
  it('keeps overclock timer through prestige and expires it offline',()=>{let s:GameState={...newGame(0),lifetimeEligibleCredits:13e9,specialization:'assistant' as const,overclock:{taps:0,charged:true,activeUntil:0,cooldownUntil:0}};s=activateOverclock(s,0);s=prestige(s);expect(s.overclock.activeUntil).toBe(15000);const next=advance(s,20).state;expect(next.savedAt).toBe(20000);expect(next.overclock.activeUntil).toBe(15000)});
  it('grants intro item once and accumulates short experiment fractions',()=>{let s:GameState={...newGame(0),discovered:['calculator','sbc'] as ('calculator'|'sbc')[]};s=queueExperiment(s,'hardware',0,'intro');s=completeExperiment(s,60000,()=>0);expect(s.inventory).toHaveLength(1);expect(queueExperiment(s,'hardware',60000,'intro')).toBe(s);for(let i=0;i<24;i++){s=queueExperiment(s,'hardware',60000+i*600000,'short');s=completeExperiment(s,660000+i*600000,()=>1)}expect(s.components).toBe(45);expect(s.blueprintFragments).toBe(1)});
  it('uses cumulative entitlement and cannot claim twice',()=>{let s:GameState={...newGame(0),lifetimeEligibleCredits:13e9,specialization:'assistant' as const};expect(newInsight(s)).toBe(3);s=prestige(s);expect(s.totalInsightEarned).toBe(3);expect(newInsight(s)).toBe(0);expect(prestige(s)).toBe(s)});
});
