import {describe,expect,it} from 'vitest';
import {activateOverclock,BALANCE,GameState,buyClassUpgrade,buyHardwareClass,classCompute,hardwareBulkCost,hardwareCost,maxAffordable,milestoneFactor,newGame,newInsight,newINT,canPrestige,hardwareIds,reachedMilestones,prestigeUpgradeCost,creditMultiplierFromINT,registerTap,tapCredits} from './economy';
import {completeExperiment,queueExperiment,splitMaterialReward} from './experiments';
import {prestige} from './prestige';
import {advance} from './simulation';

describe('phase 1 hardware and active play',()=>{
  it('uses exact geometric bulk costs and corrected analytic max purchases',()=>{const s=newGame(0),sum=Array.from({length:10},(_,i)=>hardwareCost('calculator',1+i,s)).reduce((a,b)=>a+b,0);expect(hardwareBulkCost('calculator',1,10,s)).toBeCloseTo(sum,10);const max=maxAffordable('calculator',1,1000,s);expect(hardwareBulkCost('calculator',1,max,s)).toBeLessThanOrEqual(1000+1e-9);expect(hardwareBulkCost('calculator',1,max+1,s)).toBeGreaterThan(1000)});
  it('defines and triggers all 90 class-specific milestones exactly at their thresholds',()=>{for(const id of hardwareIds){const milestones=BALANCE.hardware[id].milestones;expect(milestones.map(m=>m.threshold)).toEqual([10,25,50,100,250,500]);for(const milestone of milestones){expect(reachedMilestones(id,milestone.threshold-1)).not.toContainEqual(milestone);expect(reachedMilestones(id,milestone.threshold)).toContainEqual(milestone);expect(milestone.compute).toBeGreaterThan(0);expect(milestone.label.length).toBeGreaterThan(3)}}});
  it('applies milestone effects to class compute without generic doubling',()=>{for(const id of hardwareIds){expect(milestoneFactor(id,9)).toBe(1);expect(milestoneFactor(id,10)).toBeCloseTo(1.12);expect(milestoneFactor(id,500)).toBeGreaterThan(milestoneFactor(id,250));expect(milestoneFactor(id,500)).not.toBe(64)}});
  it('allows the first prestige as soon as one INT is available',()=>{const eligible=BALANCE.prestigeThreshold*(10**((1/BALANCE.prestigeScale)**(1/BALANCE.prestigePower))-1),state={...newGame(0),lifetimeEligibleCredits:eligible};expect(newINT(state)).toBe(1);expect(canPrestige(state)).toBe(true)});
  it('uses additive permanent INT and fixed depth costs',()=>{const state={...newGame(0),totalINTEarned:12};expect(creditMultiplierFromINT(state)).toBeCloseTo(2.2);expect(prestigeUpgradeCost('impulseNetwork',2)).toBe(1);});
  it('unlocks classes and buys a class upgrade only once',()=>{let s={...newGame(0),credits:1e9};s=buyHardwareClass(s,'calculator',9);expect(s.discovered).toContain('sbc');s=buyHardwareClass(s,'calculator',6);const before=classCompute(s,'calculator');s=buyClassUpgrade(s,'calculator');expect(classCompute(s,'calculator')).toBe(before*2);expect(buyClassUpgrade(s,'calculator')).toBe(s)});
  it('tap reward excludes temporary boosts and charges overclock',()=>{let s={...newGame(0),creditBoostUntil:1e9,overclock:{taps:0,charged:false,activeUntil:1e9,cooldownUntil:0}};expect(tapCredits(s,1)).toBe(tapCredits({...s,creditBoostUntil:0,overclock:{...s.overclock,activeUntil:0}},1));for(let i=0;i<BALANCE.overclockTaps;i++)s=registerTap(s,1);expect(s.overclock.charged).toBe(true);s=activateOverclock(s,1);expect(s.overclock.activeUntil).toBe(15001);expect(s.overclock.cooldownUntil).toBe(90001);expect(activateOverclock(s,2)).toBe(s)});
  it('keeps overclock timer through prestige and expires it offline',()=>{let s:GameState={...newGame(0),lifetimeEligibleCredits:13e9,overclock:{taps:0,charged:true,activeUntil:0,cooldownUntil:0}};s=activateOverclock(s,0);s=prestige(s);expect(s.overclock.activeUntil).toBe(15000);const next=advance(s,20).state;expect(next.savedAt).toBe(20000);expect(next.overclock.activeUntil).toBe(15000)});
  it('grants the intro item only once',()=>{let s:GameState={...newGame(0),discovered:['calculator','sbc'],credits:1e9,data:1e9};s=queueExperiment(s,'hardware',0,'intro');s=completeExperiment(s,60000,()=>0);expect(s.inventory).toHaveLength(1);expect(queueExperiment(s,'hardware',60000,'intro')).toBe(s)});
  it.each(['hardware','architecture','artifact'] as const)('makes 24 short %s experiments equal one long material reward',(type:'hardware'|'architecture'|'artifact')=>{const base:GameState={...newGame(0),discovered:['calculator','sbc'],credits:1e9,data:1e9};let short=base;for(let i=0;i<24;i++){const start=i*600000;short=queueExperiment(short,type,start,'short');short=completeExperiment(short,start+600000,()=>1)}let long=queueExperiment(base,type,0,'long');long=completeExperiment(long,14400000,()=>1);expect(short.components).toBe(long.components);expect(short.researchFragments).toBe(long.researchFragments);expect(short.blueprintFragments).toBe(long.blueprintFragments);expect(short.componentRemainder).toBe(long.componentRemainder);expect(short.researchRemainder).toBe(long.researchRemainder);expect(short.blueprintRemainder).toBe(long.blueprintRemainder)});
  it('normalizes only floating-point values within machine precision of an integer',()=>{expect(splitMaterialReward(24*(1/24))).toEqual({whole:1,remainder:0});expect(splitMaterialReward(.999)).toEqual({whole:0,remainder:.999})});
  it('uses cumulative entitlement and cannot claim twice',()=>{let s:GameState={...newGame(0),lifetimeEligibleCredits:13e9};expect(newInsight(s)).toBe(3);s=prestige(s);expect(s.totalINTEarned).toBe(3);expect(s.unspentINT).toBe(3);expect(s.spentINT).toBe(0);expect(newInsight(s)).toBe(0);expect(prestige(s)).toBe(s)});
});
