import {describe,expect,it} from 'vitest';
import {BALANCE,buyHardwareClass,classCompute,creditMultiplierFromINT,impulseNetworkBonus,newGame,queueResearchProject,registerTap,researchLabCount} from './economy';
import {buyNode,prestige} from './prestige';
import {advance} from './simulation';
import {restore,serialize} from './storage';

describe('INT prestige tree stages 1–3',()=>{
 it('charges fixed depth costs, accepts cross prerequisites, and never spends earned INT',()=>{let s={...newGame(0),unspentINT:100,totalINTEarned:100};s=buyNode(s,'impulseNetwork');expect(s.unspentINT).toBe(99);expect(buyNode(s,'feedback')).toBe(s);s=buyNode(buyNode(s,'hardwareAtlas'),'overclockSwitch');s=buyNode(s,'computeNetwork');s=buyNode(s,'feedback');expect(s.spentINT).toBe(74);expect(creditMultiplierFromINT(s)).toBe(11)});
 it('adds capped current-rate impulse reward without recursion',()=>{const s={...newGame(0),nodes:['impulseNetwork'],hardwareCounts:{...newGame(0).hardwareCounts,calculator:250},hardware:250};expect(impulseNetworkBonus(s)).toBeCloseTo(BALANCE.impulseNetworkCap*1.35*.75*250);expect(registerTap(s,0).credits).toBeGreaterThan(impulseNetworkBonus(s))});
 it('adds atlas and bounded predecessor compute',()=>{let s={...newGame(0),nodes:['hardwareAtlas','computeNetwork'],hardwareCounts:{...newGame(0).hardwareCounts,calculator:25,sbc:5},hardware:30};expect(classCompute(s,'sbc')).toBeCloseTo(5*12*1.25);expect(classCompute({...s,hardwareCounts:{...s.hardwareCounts,sbc:11}},'sbc')).toBeLessThan(11*12*1.26)});
 it('keeps the paid gem lab additional to the INT lab',()=>{const s={...newGame(0),nodes:['parallelLab'],purchasedResearchLabs:1};expect(researchLabCount(s)).toBe(3)});
 it('respects automation reserve and persists its plan through prestige/reload',()=>{let s:import('./economy').GameState={...newGame(0),nodes:['shoppingAgent','shoppingPlan'],automation:{enabled:true,reserve:500,elapsed:0,target:'calculator' as const},credits:1000,lifetimeEligibleCredits:13e9};const advanced=advance(s,10).state;expect(advanced.credits).toBeGreaterThanOrEqual(500);s=prestige(s);expect(s.automation).toMatchObject({reserve:500,target:'calculator'});expect(restore(serialize(s)).state.automation.target).toBe('calculator')});
 it('awards scanner once per account and recycling once per run even with bulk buys',()=>{let s={...newGame(0),nodes:['componentScanner','milestoneRecycling'],credits:1e9};s=buyHardwareClass(s,'calculator',50);expect(s.components).toBe(BALANCE.scannerComponents+6);expect(s.blueprintFragments).toBe(1);const again=buyHardwareClass({...s,hardwareCounts:{...s.hardwareCounts,calculator:9},hardware:9},'calculator',41);expect(again.components).toBe(s.components)});
 it('queues exactly one project and assistant starts it only when affordable',()=>{let s={...newGame(0),nodes:['labQueue','labAssistant']};s=queueResearchProject(s,'operations');expect(s.researchQueue).toBe('operations');expect(advance(s,10).state.researchQueue).toBe('operations');s={...s,credits:5000,data:250,researchPoints:25};const next=advance(s,10).state;expect(next.researchQueue).toBeNull();expect(next.researchLabs[0]?.id).toBe('operations')});
 it('resets run rewards but retains account scanner rewards on prestige',()=>{const s={...newGame(0),lifetimeEligibleCredits:13e9,scannerRewards:['calculator:10'],runRecyclingRewards:['calculator:25']};const next=prestige(s);expect(next.scannerRewards).toEqual(['calculator:10']);expect(next.runRecyclingRewards).toEqual([])});
});
