import {describe,expect,it} from 'vitest';
import {BALANCE,computeRate,dataResearchMultiplier,dataRate,newGame,queueResearchProject,researchLabCount} from './economy';
import {buyNode,prestige} from './prestige';

describe('five-branch prestige tree',()=>{
 it('uses exact branch-scaled costs and same-branch prerequisites',()=>{expect(BALANCE.prestigeUpgrades.dataArchive1.cost).toBe(100);expect(BALANCE.prestigeUpgrades.computeNet1.cost).toBe(1000);expect(BALANCE.prestigeUpgrades.manufacturing3.cost).toBe(100000000);let s={...newGame(0),unspentINT:20000};expect(buyNode(s,'dataArchive2')).toBe(s);s=buyNode(s,'dataArchive1');s=buyNode(s,'dataArchive2');expect(s.unspentINT).toBe(18900)});
 it('applies additive data research softcap and archive bonus',()=>{expect(dataResearchMultiplier(1)).toBe(1.02);expect(dataResearchMultiplier(25)).toBe(1.5);expect(dataResearchMultiplier(1000)).toBe(1.5);const base={...newGame(0),hardwareCounts:{...newGame(0).hardwareCounts,calculator:10},hardware:10,researchLevels:{...newGame(0).researchLevels,dataGeneration:25}};expect(dataRate({...base,nodes:['dataArchive3']})).toBeCloseTo(dataRate(base)*1.3)});
 it('applies compute network by unlocked hardware classes',()=>{const base={...newGame(0),discovered:['calculator','sbc'] as import('./economy').HardwareId[],hardwareCounts:{...newGame(0).hardwareCounts,calculator:10,sbc:1},hardware:11};expect(computeRate(11,{...base,nodes:['computeNet3']})).toBeCloseTo(computeRate(11,base)*1.1)});
 it('unlocks second lab and two-entry queue',()=>{let s={...newGame(0),nodes:['labs1','labs2']};expect(researchLabCount(s)).toBe(2);s=queueResearchProject(s,'operations');s=queueResearchProject(s,'blueprints');s=queueResearchProject(s,'alignment');expect(s.researchQueue).toEqual(['operations','blueprints'])});
 it('prestige cancels running labs/analysis and retains durable inventory',()=>{const base=newGame(0);const s={...base,lifetimeEligibleCredits:13e9,componentInventory:{...base.componentInventory,circuits:7},components:7,modules:{computeBus:2,dataLattice:1},inventory:[{id:'kept',type:'quantum-chip' as const,rarity:'common' as const,level:0,locked:false}],researchQueue:['operations' as const],researchLabs:[{id:'operations' as const,level:1,startedAt:0,endsAt:100,durationSeconds:100,dataCost:1},null,null,null]};const after=prestige(s);expect(after.researchLabs.every(x=>x===null)).toBe(true);expect(after.researchQueue).toEqual([]);expect(after.components).toBe(7);expect(after.modules.computeBus).toBe(2);expect(after.inventory).toEqual(s.inventory)});
});
