import {describe,expect,it} from 'vitest';
import {addCredits,BALANCE,canPrestige,creditMultiplierFromINT,newGame,newINT,prestigeClaimForEligible} from './economy';
import {prestige,prestigePreview} from './prestige';
import {ScientificNumber} from './scientificNumber';

describe('calibrated cumulative INT entitlement',()=>{
 it('is monotonic and handles scientific revenues far beyond Number range',()=>{const values=[ScientificNumber.zero(),ScientificNumber.from(1e12),ScientificNumber.from(1e100),ScientificNumber.fromParts(1,10_000)],claims=values.map(prestigeClaimForEligible);expect(claims).toEqual([...claims].sort((a,b)=>a-b));expect(claims.every(Number.isFinite)).toBe(true);expect(claims.at(-1)).toBeGreaterThan(claims.at(-2)!);});
 it('subtracts claimed entitlement and never grants the same revenue twice',()=>{const ready=addCredits(newGame(0),1e15),first=prestige(ready);expect(first.totalINTEarned).toBeGreaterThan(0);expect(newINT(first)).toBe(0);expect(prestige(first)).toBe(first);});
 it('allows reset at one INT without any additional gate and keeps preview exact',()=>{const threshold=BALANCE.prestigeThreshold*(10**((1/BALANCE.prestigeScale)**(1/BALANCE.prestigePower))-1),state=addCredits(newGame(0),threshold),preview=prestigePreview(state),after=prestige(state);expect(newINT(state)).toBe(1);expect(canPrestige(state)).toBe(true);expect(preview.claimableINT).toBe(1);expect(preview.totalINTAfter).toBe(after.totalINTEarned);expect(preview.availableINTAfter).toBe(after.unspentINT);});
 it('keeps the lifetime bonus after INT spending',()=>{const earned=prestige(addCredits(newGame(0),1e18)),spent={...earned,unspentINT:0};expect(creditMultiplierFromINT(spent)).toBe(creditMultiplierFromINT(earned));});
 it('does not count explicitly ineligible reward, shop, or debug-style credits',()=>{const state=addCredits(newGame(0),1e30,false);expect(newINT(state)).toBe(0);expect(canPrestige(state)).toBe(false);});
 it('changes only the calibrated threshold among protected economy parameters',()=>{expect(BALANCE).toMatchObject({prestigeThreshold:428_273_652_944,prestigeScale:3,prestigePower:1.5,intCreditPerPoint:.1,baseDataPerSecond:.1,trainingDurationBaseSeconds:90,trainingDurationGrowth:1.35,researchDataGrowth:1.85,researchDurationGrowth:1.35});expect(BALANCE.hardware.calculator).toMatchObject({baseCost:15,growth:1.17,compute:1});expect(BALANCE.analysisCosts.hardware.short).toEqual({data:57623,duration:600});});
 it('uses the smallest integer threshold that places the measured decision at 45 minutes',async()=>{const {simulateBalance}=await import('./simulation'),mutable=BALANCE as {prestigeThreshold:number},threshold=BALANCE.prestigeThreshold,measure=()=>simulateBalance(90/1440,true,1708,Infinity,'training-first',[{start:0,end:5400}],false);try{const calibrated=measure();expect(calibrated.evaluation?.firstPrestigeAvailable).toBe(2115);expect(calibrated.milestones.firstPrestige).toBe(2700);mutable.prestigeThreshold=threshold-1;expect(measure().milestones.firstPrestige).toBe(2690);}finally{mutable.prestigeThreshold=threshold;}} ,20_000);
});
