import {describe,expect,it} from 'vitest';
import {addCredits,creditMultiplierFromINT,equipmentSlotCount,newGame,type GameState} from './economy';
import {craft,createItem} from './inventory';
import {prestige,prestigePreview} from './prestige';
import {restore,serialize} from './storage';

const ready=()=>addCredits(newGame(1_000,'prestige-preview'),1e12);

describe('prestige preview and reset safety',()=>{
 it('matches the actual reset and allows prestige exactly when at least one INT is claimable',()=>{const below=newGame(0);expect(prestigePreview(below).claimableINT).toBe(0);expect(prestige(below)).toBe(below);const s=ready(),preview=prestigePreview(s),after=prestige(s);expect(preview.claimableINT).toBeGreaterThanOrEqual(1);expect(after.totalINTEarned).toBe(preview.totalINTAfter);expect(after.unspentINT).toBe(preview.availableINTAfter);expect(creditMultiplierFromINT(after)).toBe(preview.creditBonusAfter);expect(after).toMatchObject({credits:0,data:0,hardware:1,qualityLevel:0,efficiencyLevel:0});});
 it('does not let spent INT reduce the lifetime credit bonus or a double click grant twice',()=>{const s=ready(),once=prestige(s),spent={...once,unspentINT:0,spentINT:once.totalINTEarned,exactEconomy:{...once.exactEconomy,unspentINT:{m:0,e:0},spentINT:once.exactEconomy.totalINTEarned}};expect(creditMultiplierFromINT(spent)).toBe(creditMultiplierFromINT(once));expect(prestige(once)).toBe(once);const loaded=restore(serialize(once),once.savedAt).state;expect(prestige(loaded)).toBe(loaded);});
 it('keeps durable inventory, equipment slots, and reserved crafting jobs',()=>{let s=ready();s={...s,prestigeCount:1,impulseRelayBlueprint:true,componentInventory:{...s.componentInventory,circuits:12,copperCoils:2},components:14,purchasedEquipmentSlots:1};s=createItem(s,'quantum-chip','common');s=craft(s,'impulse-relay','common',1);const before=s.crafting,after=prestige(s);expect(after.componentInventory).toEqual(s.componentInventory);expect(after.inventory).toEqual(s.inventory);expect(after.crafting).toEqual(before);expect(after.purchasedEquipmentSlots).toBe(1);expect(equipmentSlotCount(after)).toBe(2);});
 it('documents research/crafting as continuing and training/analysis as cancelled without refunds',()=>{const s:GameState={...ready(),data:100,activeTraining:{track:'quality',workRequired:90,creditCost:0,dataCost:15},training:10,researchLabs:[{id:'dataGeneration',level:1,startedAt:0,endsAt:61_000,durationSeconds:60,dataCost:40},null,null,null],experiments:{...ready().experiments,active:{id:'a',type:'hardware',length:'short',startedAt:1_000,endsAt:601_000,dataCost:75}},crafting:{active:{id:'c',kind:'module',recipeId:'computeBus',quantity:1,completed:0,durationPerUnit:30,startedAt:1_000,endsAt:31_000,ingredients:{components:{circuits:1},modules:{},data:0,blueprints:0},result:{kind:'module',id:'computeBus'}},queue:[]}};const preview=prestigePreview(s),after=prestige(s);expect(preview.jobs.map(job=>[job.kind,job.status])).toEqual([['training','cancelled'],['research','continues'],['analysis','cancelled'],['crafting','continues']]);expect(after.activeTraining).toBeNull();expect(after.experiments.active).toBeNull();expect(after.researchLabs[0]).toEqual(s.researchLabs[0]);expect(after.crafting).toEqual(s.crafting);expect(after.data).toBe(0);});
 it('opens the first free equipment slot exactly once',()=>{const first=prestige(ready());expect(equipmentSlotCount(first)).toBe(1);const secondReady=addCredits(first,1e15),second=prestige(secondReady);expect(equipmentSlotCount(second)).toBe(1);expect(first.purchasedEquipmentSlots).toBe(0);expect(second.purchasedEquipmentSlots).toBe(0);});
});
