import {describe,expect,it} from 'vitest';
import {BALANCE,exactEconomyValue,newGame,repeatableResearchDataCost,repeatableResearchDuration,researchDuration,researchDurationAtStart,researchProjectDataCost,researchProjectDataCostScientific,startResearchProject} from './economy';
import {ScientificNumber} from './scientificNumber';
import {advance} from './simulation';
import {restore,serialize} from './storage';

const funded=(data:ScientificNumber|number)=>{const value=typeof data==='number'?ScientificNumber.from(data):data,base=newGame(0);return{...base,data:value.toNumber(),exactEconomy:{...base.exactEconomy,data:value.toJSON()}}};
describe('category research contracts',()=>{
 it('assigns every project to an existing central category',()=>{for(const project of Object.values(BALANCE.researchProjects))expect(BALANCE.researchCategories[project.balanceCategory]).toBeDefined();for(const project of Object.values(BALANCE.repeatableResearch))expect(BALANCE.researchCategories[project.balanceCategory]).toBeDefined();});
 it('uses category formulas with L=1 and the 72-hour duration cap',()=>{for(const [id,project] of Object.entries(BALANCE.repeatableResearch)){const category=BALANCE.researchCategories[project.balanceCategory];expect(repeatableResearchDataCost(id as keyof typeof BALANCE.repeatableResearch,1)).toBe(category.baseData);expect(repeatableResearchDataCost(id as keyof typeof BALANCE.repeatableResearch,5)).toBeCloseTo(Math.ceil(category.baseData*1.85**4),10);expect(repeatableResearchDuration(id as keyof typeof BALANCE.repeatableResearch,5)).toBeCloseTo(category.baseDuration*1.35**4);expect(repeatableResearchDuration(id as keyof typeof BALANCE.repeatableResearch,100)).toBe(72*3600);}});
 it('uses category bases for one-time projects',()=>{expect([researchProjectDataCost('operations'),researchDuration('operations')]).toEqual([600,3600]);expect([researchProjectDataCost('blueprints'),researchDuration('blueprints')]).toEqual([100,600]);expect([researchProjectDataCost('alignment'),researchDuration('alignment')]).toEqual([250,1800]);});
 it('charges only exact Data once and protects shortage and double clicks',()=>{const cost=researchProjectDataCostScientific('operations'),poor=funded(cost.subtract(ScientificNumber.from(1)));expect(startResearchProject(poor,'operations')).toBe(poor);const ready={...funded(cost),credits:0,researchPoints:0},started=startResearchProject(ready,'operations');expect(exactEconomyValue(started,'data').isZero()).toBe(true);expect(started.credits).toBe(0);expect(started.researchPoints).toBe(0);expect(startResearchProject(started,'operations')).toBe(started);});
 it('freezes duration at start, including an already active lab boost',()=>{const ready={...funded(1000),labBoostUntil:10_000_000},started=startResearchProject(ready,'operations'),ends=started.researchLabs[0]!.endsAt;expect(researchDurationAtStart(ready,'operations',1)).toBe(1800);const changed={...started,labBoostUntil:0};expect(advance(changed,100).state.researchLabs[0]!.endsAt).toBe(ends);});
 it('completes exactly once online, offline, and after reload',()=>{for(const active of [true,false]){const started=startResearchProject(funded(1000),'blueprints'),partial=advance(started,300,active).state,loaded=restore(serialize(partial),300_000).state,done=advance(loaded,300,active).state;expect(done.completedResearch).toContain('blueprints');expect(done.lifetime.researchCompleted).toBe(1);expect(advance(done,600,active).state.lifetime.researchCompleted).toBe(1);}});
});
