import {describe,expect,it} from 'vitest';
import {addCredits,BALANCE,buyHardwareClass,dataRate,hardwareCost,hardwareMasteryLevel,newGame,tapCredits} from './economy';
import {abortRunChallenge,challengeClaimable,challenges,claimChallenge,collectionSummary,completeRunChallenge,prestigeGate,runChallengeProgress,runChallengeReady,startRunChallenge,totalMastery} from './retention';
import {restore,serialize} from './storage';

const challengeRevenue=BALANCE.prestigeThreshold*(10**((1/BALANCE.prestigeScale)**(1/BALANCE.prestigePower))-1);
const earnRunGoal=<T extends ReturnType<typeof newGame>>(s:T)=>addCredits(s,challengeRevenue) as T;

describe('long-term retention progression',()=>{
 it('earns persistent mastery XP only beyond 500 owned',()=>{let s=newGame(0);s={...s,credits:1e100,hardwareCounts:{...s.hardwareCounts,calculator:500},hardware:500,discovered:['calculator'],exactEconomy:{...s.exactEconomy,credits:{m:1,e:100}}};s=buyHardwareClass(s,'calculator',250);expect(s.retention.hardwareMasteryXp.calculator).toBe(250);expect(hardwareMasteryLevel(s,'calculator')).toBe(1);});
 it('claims challenge stars exactly once',()=>{let s=newGame(0);s={...s,lifetime:{...s.lifetime,prestiges:25}};const c=challenges.find(x=>x.id==='prestige-25')!;expect(challengeClaimable(s,c)).toBe(true);s=claimChallenge(s,c.id);expect(s.retention.challengeStars).toBe(2);expect(claimChallenge(s,c.id).retention.challengeStars).toBe(2);});
 it('tracks collection completion from permanent discovery',()=>{const s=newGame(0),c=collectionSummary(s);expect(c.hardware).toBe(1);expect(c.hardwareTotal).toBe(15);expect(c.componentsTotal).toBe(Object.keys(s.componentInventory).length);expect(c.componentsTotal).toBe(10);expect(c.itemTypesTotal).toBe(10);});
 it('gates deep prestige by account progression',()=>{let s=newGame(0);expect(prestigeGate(s,7)?.ok).toBe(false);s={...s,retention:{...s.retention,challengeStars:10}};expect(prestigeGate(s,7)?.ok).toBe(true);expect(totalMastery(s)).toBe(0);});
 it('ignores old unclaimed INT and requires eligible revenue earned by this run',()=>{const rich=addCredits(newGame(0,'account'),challengeRevenue*10),started=startRunChallenge(rich,'no-taps');expect(started.retention.activeRun).toMatchObject({id:'no-taps',runId:'account:no-taps:1'});expect(runChallengeProgress(started)).toBe(0);expect(runChallengeReady(started)).toBe(false);const rewarded=addCredits(started,challengeRevenue*10,false);expect(runChallengeReady(rewarded)).toBe(false);const earned=earnRunGoal(rewarded);expect(runChallengeProgress(earned)).toBe(1);expect(runChallengeReady(earned)).toBe(true)});
 it('rewards a challenge run once across double click and reload',()=>{let s=earnRunGoal(startRunChallenge(newGame(0),'no-taps'));s={...s,savedAt:60000};const completed=completeRunChallenge(s),reloaded=restore(serialize(completed),60000).state;expect(completed.retention.runCompletions['no-taps']).toBe(1);expect(completed.retention.challengeStars).toBe(2);expect(completeRunChallenge(completed)).toBe(completed);expect(completeRunChallenge(reloaded)).toBe(reloaded)});
 it('improves a repeat best time without granting more stars',()=>{let first=earnRunGoal(startRunChallenge(newGame(0),'no-taps'));first=completeRunChallenge({...first,savedAt:120000});let repeat=earnRunGoal(startRunChallenge(first,'no-taps'));repeat=completeRunChallenge({...repeat,savedAt:first.savedAt+60000});expect(repeat.retention.runCompletions['no-taps']).toBe(2);expect(repeat.retention.runBestSeconds['no-taps']).toBe(60);expect(repeat.retention.challengeStars).toBe(2)});
 it('supports data crunch, inflation and abort without rewards',()=>{const base=newGame(0),normalData=dataRate(base),normalCost=hardwareCost('calculator',1,base);let data=startRunChallenge(base,'data-crunch');expect(dataRate(data)).toBeCloseTo(normalData*.1);let inflation=startRunChallenge(base,'inflation');expect(hardwareCost('calculator',1,inflation)).toBeCloseTo(normalCost*100);const runId=inflation.retention.activeRun?.runId;inflation=abortRunChallenge(inflation);expect(inflation.retention.challengeStars).toBe(0);expect(inflation.retention.activeRun).toBeNull();expect(startRunChallenge(inflation,'inflation').retention.activeRun?.runId).not.toBe(runId)});
});
