import {useEffect,useRef} from 'react';
import type {GameState} from './economy';
import type {AdvanceReport} from './simulation';
import {ScientificNumber} from './scientificNumber';
import {ComponentArt,MetaArt} from './GameArt';
import {componentText} from './gameplayI18n';

const duration=(seconds:number,language:string)=>{const minutes=Math.floor(seconds/60),hours=Math.floor(minutes/60),rest=minutes%60;return hours?`${hours} h ${rest} min`:`${minutes} min`};
const amount=(value:{m:number;e:number},format:GameState['settings']['numberFormat'])=>ScientificNumber.fromJSON(value).toDisplayString(2,format==='engineering');
export function ReturnReport({report,state,onClose}:{report:AdvanceReport;state:GameState;onClose:()=>void}){const button=useRef<HTMLButtonElement>(null),de=state.settings.language==='de';useEffect(()=>{const previous=document.activeElement as HTMLElement|null;button.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};addEventListener('keydown',key);return()=>{removeEventListener('keydown',key);previous?.focus()}},[onClose]);const components=Object.entries(report.components).filter(([,n])=>Number(n)>0);return <div className="return-backdrop"><section className="return-report" role="dialog" aria-modal="true" aria-labelledby="return-title"><header><MetaArt id="season"/><div><small>{de?'RÜCKKEHRÜBERSICHT':'RETURN SUMMARY'}</small><h2 id="return-title">{de?'Willkommen zurück':'Welcome back'}</h2></div></header><div className="return-scroll"><dl><div><dt>{de?'Tatsächliche Abwesenheit':'Actual absence'}</dt><dd>{duration(report.elapsedSeconds,state.settings.language)}</dd></div><div><dt>{de?'Berücksichtigte Offline-Zeit':'Credited offline time'}</dt><dd>{duration(report.seconds,state.settings.language)}</dd></div></dl>{report.lostSeconds>0&&<p className="return-limit">{de?`${duration(report.lostSeconds,state.settings.language)} lagen über deinem Offline-Limit und erzeugten daher keine Erträge.`:`${duration(report.lostSeconds,state.settings.language)} exceeded your offline limit and therefore produced no income.`}</p>}<section className="return-resources"><article><b>Credits</b><strong>+{amount(report.exactCredits,state.settings.numberFormat)}</strong></article><article><b>{de?'Daten':'Data'}</b><strong>+{amount(report.exactData,state.settings.numberFormat)}</strong></article></section>{components.length>0&&<section><h3>{de?'Komponenten':'Components'}</h3><div className="return-components">{components.map(([id,n])=><div key={id}><ComponentArt id={id as keyof GameState['componentInventory']}/><span>{componentText(id as keyof GameState['componentInventory'],state.settings.language).name}</span><strong>+{n}</strong></div>)}</div></section>}<section><h3>{de?'Abschlüsse':'Completions'}</h3><ul><li>{de?'Trainings':'Training'}: <b>{report.levels}</b></li><li>{de?'Forschungen':'Research'}: <b>{report.researchCompleted}</b></li><li>{de?'Analysen':'Analyses'}: <b>{report.experiments}</b></li><li>{de?'Crafting-Aufträge':'Crafting jobs'}: <b>{report.craftingCompleted}</b></li></ul></section><p><small>{de?'Alle Erträge wurden bereits automatisch gebucht.':'All income has already been applied automatically.'}</small></p></div><footer><button ref={button} onClick={onClose}>{de?'Weiter':'Continue'}</button></footer></section></div>}
