import {GameState,ComponentId,SeasonState} from './economy';
import {addEvent} from './telemetry';
export const SEASON_DAYS=30,SEASON_LEVELS=50,SEASON_XP_PER_LEVEL=1000,SEASON_GRACE_DAYS=7;
export type SeasonReward={level:number;gems?:number;component?:ComponentId;amount?:number;artifact?:string};
export const seasonRewards:SeasonReward[]=Array.from({length:SEASON_LEVELS},(_,i)=>{const level=i+1;if(level===50)return{level,artifact:'boot-sequence-core',gems:250};if(level%10===0)return{level,gems:100,component:level>=40?'quantumCores':level>=30?'nanotubes':'graphene',amount:Math.max(1,level/10)};if(level%5===0)return{level,gems:40,component:level>=25?'graphene':'photonicLenses',amount:level>=25?2:5};return{level,gems:10+(level%3)*5,component:level>20?'titaniumBolts':'circuits',amount:level>20?3:8};});
const levelFor=(season:SeasonState)=>Math.min(SEASON_LEVELS,Math.floor(season.xp/SEASON_XP_PER_LEVEL));
export const seasonLevel=(s:GameState)=>levelFor(s.season);
export const seasonProgress=(s:GameState)=>s.season.xp>=SEASON_LEVELS*SEASON_XP_PER_LEVEL?1:(s.season.xp%SEASON_XP_PER_LEVEL)/SEASON_XP_PER_LEVEL;
export function rollSeason(s:GameState,now:number){if(now<s.season.endsAt)return s.previousSeason&&now>s.previousSeason.claimUntil?{...s,previousSeason:null}:s;const completed=seasonLevel(s)>=SEASON_LEVELS,completedSeasons=completed?[...new Set([...s.profile.completedSeasons,s.season.id])]:s.profile.completedSeasons,elapsed=Math.max(1,Math.floor((now-s.season.startedAt)/(SEASON_DAYS*86400000))),number=Math.max(2,Number(s.season.id.split('-')[1]||1)+elapsed),previous={...s.season,claimUntil:s.season.endsAt+SEASON_GRACE_DAYS*86400000},next={...s,profile:{...s.profile,completedSeasons},previousSeason:now<=previous.claimUntil?previous:null,season:{id:`season-${String(number).padStart(2,'0')}`,startedAt:s.season.endsAt+(elapsed-1)*SEASON_DAYS*86400000,endsAt:s.season.endsAt+elapsed*SEASON_DAYS*86400000,xp:0,claimed:[]}};return addEvent(next,'season-rollover',now,{from:s.season.id,to:next.season.id,graceUntil:previous.claimUntil});}
export const seasonClaimable=(s:GameState)=>seasonRewards.some(r=>r.level<=seasonLevel(s)&&!s.season.claimed.includes(r.level))||!!s.previousSeason&&s.savedAt<=s.previousSeason.claimUntil&&seasonRewards.some(r=>r.level<=levelFor(s.previousSeason!)&&!s.previousSeason!.claimed.includes(r.level));
export function addSeasonXP(s:GameState,xp:number,source:string){if(xp<=0)return s;return addEvent({...s,season:{...s.season,xp:s.season.xp+xp}},'season-xp',s.savedAt,{xp,source});}
export function claimSeasonReward(s:GameState,level:number,seasonId=s.season.id){const previous=seasonId===s.previousSeason?.id&&s.savedAt<=s.previousSeason.claimUntil,target=previous?s.previousSeason:s.season;if(!target||seasonId!==target.id)return s;const reward=seasonRewards.find(r=>r.level===level);if(!reward||level>levelFor(target)||target.claimed.includes(level))return s;const claimed={...target,claimed:[...target.claimed,level]};let next:GameState=previous?{...s,previousSeason:claimed as GameState['previousSeason']}:{...s,season:claimed};if(reward.gems)next={...next,gems:next.gems+reward.gems,gemLedger:[...next.gemLedger,{id:`season-${seasonId}-${level}`,at:s.savedAt,amount:reward.gems,source:'season'}]};if(reward.component&&reward.amount)next={...next,components:next.components+reward.amount,componentInventory:{...next.componentInventory,[reward.component]:next.componentInventory[reward.component]+reward.amount},lifetime:{...next.lifetime,componentsEarned:next.lifetime.componentsEarned+reward.amount}};if(reward.artifact){const artifact=`${seasonId}-core`;if(!next.profile.artifacts.includes(artifact))next={...next,profile:{...next.profile,artifacts:[...next.profile.artifacts,artifact],completedSeasons:[...new Set([...next.profile.completedSeasons,seasonId])]}}}return addEvent(next,'season-reward',s.savedAt,{seasonId,level,gems:reward.gems??0,component:reward.component??'',amount:reward.amount??0,artifact:reward.artifact??''});}
export const questSeasonXP=(kind:'daily'|'weekly'|'monthly',tier=1)=>({daily:100,weekly:500,monthly:900}[kind]*tier);
