import {GameState,ComponentId} from './economy';
import {addEvent} from './telemetry';
export const SEASON_DAYS=30,SEASON_LEVELS=50,SEASON_XP_PER_LEVEL=1000;
export type SeasonReward={level:number;gems?:number;component?:ComponentId;amount?:number;artifact?:string};
export const seasonRewards:SeasonReward[]=Array.from({length:SEASON_LEVELS},(_,i)=>{const level=i+1;if(level===50)return{level,artifact:'boot-sequence-core',gems:250};if(level%10===0)return{level,gems:100,component:level>=40?'quantumCores':level>=30?'nanotubes':'graphene',amount:Math.max(1,level/10)};if(level%5===0)return{level,gems:40,component:level>=25?'graphene':'laser',amount:level>=25?2:5};return{level,gems:10+(level%3)*5,component:level>20?'titaniumBolts':'circuits',amount:level>20?3:8};});
export const seasonLevel=(s:GameState)=>Math.min(SEASON_LEVELS,Math.floor(s.season.xp/SEASON_XP_PER_LEVEL));
export const seasonProgress=(s:GameState)=>s.season.xp>=SEASON_LEVELS*SEASON_XP_PER_LEVEL?1:(s.season.xp%SEASON_XP_PER_LEVEL)/SEASON_XP_PER_LEVEL;
export function rollSeason(s:GameState,now:number){if(now<s.season.endsAt)return s;const completed=seasonLevel(s)>=SEASON_LEVELS,completedSeasons=completed?[...new Set([...s.profile.completedSeasons,s.season.id])]:s.profile.completedSeasons;const elapsed=Math.max(1,Math.floor((now-s.season.startedAt)/(SEASON_DAYS*86400000))),number=Math.max(2,Number(s.season.id.split('-')[1]||1)+elapsed);return{...s,profile:{...s.profile,completedSeasons},season:{id:`season-${String(number).padStart(2,'0')}`,startedAt:s.season.endsAt+(elapsed-1)*SEASON_DAYS*86400000,endsAt:s.season.endsAt+elapsed*SEASON_DAYS*86400000,xp:0,claimed:[]}}}
export const seasonClaimable=(s:GameState)=>seasonRewards.some(r=>r.level<=seasonLevel(s)&&!s.season.claimed.includes(r.level));
export function addSeasonXP(s:GameState,xp:number,source:string){if(xp<=0)return s;return addEvent({...s,season:{...s.season,xp:s.season.xp+xp}},'season-xp',s.savedAt,{xp,source});}
export function claimSeasonReward(s:GameState,level:number){const reward=seasonRewards.find(r=>r.level===level);if(!reward||level>seasonLevel(s)||s.season.claimed.includes(level))return s;let next={...s,season:{...s.season,claimed:[...s.season.claimed,level]}};if(reward.gems)next={...next,gems:next.gems+reward.gems,gemLedger:[...next.gemLedger,{id:`season-${s.season.id}-${level}`,at:s.savedAt,amount:reward.gems,source:'season'}]};if(reward.component&&reward.amount){next={...next,components:next.components+reward.amount,componentInventory:{...next.componentInventory,[reward.component]:next.componentInventory[reward.component]+reward.amount},lifetime:{...next.lifetime,componentsEarned:next.lifetime.componentsEarned+reward.amount}}}if(reward.artifact){const artifact=`${s.season.id}-core`;if(!next.profile.artifacts.includes(artifact))next={...next,profile:{...next.profile,artifacts:[...next.profile.artifacts,artifact],completedSeasons:[...new Set([...next.profile.completedSeasons,s.season.id])]}}}return addEvent(next,'season-reward',s.savedAt,{level,gems:reward.gems??0,component:reward.component??'',amount:reward.amount??0,artifact:reward.artifact??''});}
export const questSeasonXP=(kind:'daily'|'weekly'|'monthly',tier=1)=>({daily:100,weekly:500,monthly:900}[kind]*tier);
