import {type GameState,type HardwareId,newINT,reachedMilestones,tapCredits,trainingCost} from './economy';

export type TutorialTarget='prologue'|'tap'|'calculator'|'quality'|'research'|'analysis'|'components'|'craft'|'equip'|null;
export type StoryState={tutorial:'active'|'skipped'|'completed';target:TutorialTarget;open:string|null;queue:string[];seen:string[]};
export const newStory=():StoryState=>({tutorial:'active',target:'prologue',open:'prologue-welcome',queue:[],seen:['prologue-welcome']});
export const migratedStory=():StoryState=>({tutorial:'skipped',target:null,open:null,queue:[],seen:[]});
type Dialogue={speaker:'Mira'|'AURA';text:(s:GameState)=>string};
export const dialogues:Record<string,Dialogue>={
 'prologue-welcome':{speaker:'Mira',text:()=> 'Gut, du bist da. Ich bin Dr. Mira Voss. Das hier ist unser Labor.'},
 'prologue-aura':{speaker:'Mira',text:s=>`Das ist ${s.aiName??'AURA'}. Im Moment läuft ihr ganzes Modell auf ziemlich bescheidener Hardware.`},
 'prologue-funding':{speaker:'Mira',text:()=> 'Die Förderung ist weg. Wenn wir das Labor selbst finanzieren, können wir die KI weiterentwickeln und echte Forschungsfragen angehen.'},
 'prologue-mission':{speaker:'Mira',text:()=> 'Hilfst du mir, aus diesem kleinen Prototyp eine KI zu machen, die die Welt verändern kann?'},
 'tutorial-tap':{speaker:'Mira',text:s=>s.settings.language==='de'?`Gib ${s.aiName??'AURA'} einen Labor-Impuls. Er bringt aktuell ${tapCredits(s).toLocaleString('de-DE',{maximumFractionDigits:2})} Credits.`:`Give ${s.aiName??'AURA'} a lab impulse. It currently grants ${tapCredits(s).toLocaleString('en-US',{maximumFractionDigits:2})} credits.`},
 'tutorial-calculator':{speaker:'Mira',text:s=>s.settings.language==='de'?'Hardware erzeugt Compute; Nutzer erzeugen Credits und Daten. Kaufe einen Taschenrechner.':'Hardware produces compute; users produce credits and data. Buy one calculator.'},
 'tutorial-quality':{speaker:'Mira',text:s=>s.settings.language==='de'?`Training verbessert das Modell. Starte Quality-Training; der aktuelle Creditpreis ist ${trainingCost(s,'quality').toLocaleString('de-DE')}.`:`Training improves the model. Start quality training; its current credit cost is ${trainingCost(s,'quality').toLocaleString('en-US')}.`},
 'tutorial-research':{speaker:'Mira',text:s=>s.settings.language==='de'?'Forschung kostet Daten und hat eine feste Laufzeit. Starte Datenerzeugung Stufe 1 und warte auf den echten Abschluss.':'Research costs data and has a fixed duration. Start data generation level 1 and wait for its actual completion.'},
 'tutorial-analysis':{speaker:'Mira',text:s=>s.settings.language==='de'?'Analysen sammeln Komponenten in einem separaten Slot. Starte und beende eine kurze Hardwareanalyse.':'Analyses collect components in a separate slot. Start and finish a short hardware analysis.'},
 'tutorial-components':{speaker:'Mira',text:s=>s.settings.language==='de'?'Öffne jetzt den Komponentenbestand und sieh dir die echten Analysefunde an.':'Now open the component inventory and inspect the actual analysis finds.'},
 'tutorial-craft':{speaker:'Mira',text:s=>s.settings.language==='de'?'Crafting verarbeitet Materialien zu Ausrüstung. Stelle ein tatsächlich freigeschaltetes und bezahlbares Rezept fertig.':'Crafting turns materials into equipment. Complete a recipe that is genuinely unlocked and affordable.'},
 'tutorial-equip':{speaker:'Mira',text:s=>s.settings.language==='de'?'Prestige öffnet den ersten Ausrüstungsplatz. Nach dem ersten Prestige kannst du dein Item dort ausrüsten.':'Prestige opens the first equipment slot. After your first prestige, equip your item there.'},
 'tutorial-complete':{speaker:'Mira',text:s=>s.settings.language==='de'?'Sehr gut. Du kennst jetzt den vollständigen Laborablauf; alle Entscheidungen bleiben bei dir.':'Excellent. You now know the full laboratory loop; every decision remains yours.'},
 'first-hardware':{speaker:'Mira',text:s=>`Erste Hardware online. ${s.hardware} Geräte liefern zusammen Compute; daraus entstehen Nutzer, und Nutzer erzeugen Credits sowie Daten.`},
 'first-training':{speaker:'Mira',text:s=>`Training abgeschlossen. Dein Modell steht jetzt bei Qualität ${s.qualityLevel} und Effizienz ${s.efficiencyLevel}.`},
 'first-research':{speaker:'Mira',text:()=> 'Der erste Forschungsabschluss steht. Ab jetzt gehen wir Schritt für Schritt schwierigere Fragen an.'},
 'first-milestone':{speaker:'Mira',text:()=> 'Ein echter Hardware-Meilenstein. Große Stückzahlen verbessern nicht nur die Klasse selbst, sondern prägen die Leistung des ganzen Labors.'},
 'prestige-ready':{speaker:'Mira',text:s=>`${newINT(s)} INT wären jetzt erreichbar. Der Neustart geschieht nur, wenn du ihn im Prestige-Reiter selbst bestätigst.`},
 'first-prestige':{speaker:'Mira',text:s=>`Der Neustart brachte ${s.telemetry.prestigeHistory.at(-1)?.intEarned??0} INT. Credits, Daten, Hardwarebestände, Klassen-Upgrades und Modell wurden zurückgesetzt. INT, Entdeckungen, Items, Forschung, Gems, Aufträge, Projekte und Timer bleiben.`},
};
const append=(s:GameState,id:string)=>{if(s.story.seen.includes(id)||s.story.open===id||s.story.queue.includes(id))return s;const story=s.story.open?{...s.story,queue:[...s.story.queue,id]}:{...s.story,open:id,seen:[...s.story.seen,id]};return{...s,story}};
const events=(s:GameState)=>[...s.telemetry.permanentEvents,...s.telemetry.recentEvents];
const totalTaps=(s:GameState)=>s.telemetry.archivedMetrics.taps+s.telemetry.metrics.reduce((sum,b)=>sum+b.taps,0);
const firstMilestoneCount=(s:GameState)=>Object.entries(s.hardwareCounts).reduce((sum,[id,count])=>sum+reachedMilestones(id as HardwareId,count).length,0);
const targets:Exclude<TutorialTarget,'prologue'|null>[]=['tap','calculator','quality','research','analysis','components','craft','equip'];
const fulfilled=(s:GameState,target:TutorialTarget)=>target==='tap'?totalTaps(s)>0:target==='calculator'?s.lifetime.calculatorsBought>0:target==='quality'?s.qualityLevel>0||s.activeTraining?.track==='quality'||events(s).some(e=>e.type==='training-start'&&e.details.track==='quality'):target==='research'?s.researchLevels.dataGeneration>=1:target==='analysis'?(s.experiments.lastResult?.type==='hardware'&&s.experiments.lastResult.length==='short')||events(s).some(e=>e.type==='experiment-complete'&&e.details.type==='hardware'&&e.details.length==='short'):target==='craft'?s.lifetime.itemsCrafted>0:target==='equip'?s.onboarding.completed.includes('equip-item')||Object.values(s.equipped).some(Boolean):false;
const nextTarget=(target:TutorialTarget)=>targets[targets.indexOf(target as typeof targets[number])+1]??null;
export function advanceTutorial(s:GameState,allowComponents=false):GameState{if(s.story.tutorial!=='active'||s.story.target==='prologue'||!s.story.target)return s;let next=s,target=s.story.target,guard=0;while(target&&guard++<8&&(fulfilled(next,target)||(target==='components'&&allowComponents))){target=nextTarget(target);next={...next,story:{...next.story,target,tutorial:target?'active':'completed'}};next=append(next,target?`tutorial-${target}`:'tutorial-complete');allowComponents=false}return next}
export function syncStory(before:GameState,after:GameState):GameState{let next=advanceTutorial(after);if(after.hardware>before.hardware)next=append(next,'first-hardware');if(after.level>before.level)next=append(next,'first-training');if(after.completedResearch.length>before.completedResearch.length||after.breakthroughs.length>before.breakthroughs.length)next=append(next,'first-research');if(firstMilestoneCount(after)>firstMilestoneCount(before))next=append(next,'first-milestone');if(newINT(before)<1&&newINT(after)>=1)next=append(next,'prestige-ready');if(after.prestigeCount>before.prestigeCount)next=append(next,'first-prestige');return next}
const showNext=(s:GameState,story:StoryState,id?:string)=>{const open=id??story.queue[0]??null,queue=id?story.queue.filter(q=>q!==id):story.queue.slice(open?1:0);return{...s,story:{...story,open,queue,seen:open&&!story.seen.includes(open)?[...story.seen,open]:story.seen}}};
export function continueDialogue(s:GameState):GameState{const id=s.story.open;if(!id)return s;let story={...s.story,open:null};if(story.tutorial==='active'){const prologue=['prologue-welcome','prologue-aura','prologue-funding','prologue-mission'];const index=prologue.indexOf(id);if(index>=0)return showNext(s,story,prologue[index+1]??'tutorial-tap');if(id==='tutorial-tap'){story.target='tap';return advanceTutorial({...s,story})}if(id.startsWith('tutorial-'))return advanceTutorial({...s,story})}return showNext(s,story)}
export function visitTutorialComponents(s:GameState){return advanceTutorial(s,true)}
export function skipTutorial(s:GameState):GameState{const story={...s.story,tutorial:'skipped' as const,open:null,queue:s.story.queue.filter(id=>!id.startsWith('prologue-')&&!id.startsWith('tutorial-'))};return showNext(s,story)}
export function resumeTutorial(s:GameState):GameState{if(s.story.tutorial!=='skipped'||!s.story.target)return s;const open=`tutorial-${s.story.target}`,story={...s.story,tutorial:'active' as const,open};return{...s,story:{...story,seen:story.seen.includes(open)?story.seen:[...story.seen,open]}}}
export function skipCurrentDialogue(s:GameState){return s.story.tutorial==='active'?skipTutorial(s):showNext(s,{...s.story,open:null})}
export function reopenDialogue(s:GameState,id:string){return !dialogues[id]||!s.story.seen.includes(id)||s.story.open!==null?s:{...s,story:{...s.story,open:id}}}
