import {type GameState,type HardwareId,newINT,reachedMilestones,tapCredits,trainingCost,usersRate} from './economy';

export type TutorialTarget='name'|'prologue'|'tap'|'hardware'|'production'|'credits'|'training'|'research'|'analysis'|'crafting'|'prestige'|null;
export type StoryState={tutorial:'active'|'skipped'|'completed';target:TutorialTarget;open:string|null;queue:string[];seen:string[];chapters?:string[];enabled?:boolean};
export const newStory=():StoryState=>({tutorial:'active',target:'name',open:null,queue:[],seen:[],chapters:[],enabled:true});
export const migratedStory=():StoryState=>({tutorial:'skipped',target:null,open:null,queue:[],seen:[],chapters:[],enabled:true});
type Dialogue={speaker:'Mira'|'AURA';title?:(s:GameState)=>string;text:(s:GameState)=>string};
const localized=(s:GameState,de:string,en:string)=>s.settings.language==='de'?de:en;
export const dialogueUiCopy=(s:GameState)=>s.settings.language==='de'?{heading:'Mira-Dialog',close:'Schließen',skip:'Überspringen',continue:'Weiter'}:{heading:'Mira dialogue',close:'Close',skip:'Skip',continue:'Continue'};
const ai=(s:GameState)=>s.aiName??'AURA';
export const dialogues:Record<string,Dialogue>={
 'prologue-welcome':{speaker:'Mira',text:s=>localized(s,'Gut, du bist da. Ich bin Dr. Mira Voss. Das hier ist unser Garagenlabor.','Good, you are here. I am Dr. Mira Voss. This is our garage laboratory.')},
 'prologue-aura':{speaker:'Mira',text:s=>localized(s,`Das ist ${ai(s)}. Im Moment läuft das ganze Modell auf bescheidener Hardware.`,`This is ${ai(s)}. For now, the entire model runs on modest hardware.`)},
 'prologue-funding':{speaker:'Mira',text:s=>localized(s,'Die Förderung ist weg. Credits finanzieren neue Hardware; Daten ermöglichen Training und Forschung.','The grant is gone. Credits fund new hardware; data enables training and research.')},
 'prologue-mission':{speaker:'Mira',text:s=>localized(s,'Hilfst du mir, aus diesem Prototyp erst ein Startup und später eine selbstlernende KI-Firma zu bauen?','Will you help me turn this prototype into a startup and later a self-learning AI company?')},
 'tutorial-tap':{speaker:'Mira',text:s=>s.settings.language==='de'?`Gib ${s.aiName??'AURA'} einen Labor-Impuls. Er bringt aktuell ${tapCredits(s).toLocaleString('de-DE',{maximumFractionDigits:2})} Credits.`:`Give ${s.aiName??'AURA'} a lab impulse. It currently grants ${tapCredits(s).toLocaleString('en-US',{maximumFractionDigits:2})} credits.`},
 'tutorial-hardware':{speaker:'Mira',text:s=>localized(s,'Kaufe dein erstes Hardwareteil über den markierten Taschenrechner-Button.','Buy your first hardware unit using the highlighted calculator button.')},
 'tutorial-production':{speaker:'Mira',text:s=>localized(s,`Unsere Hardware erzeugt jetzt ${usersRate(s).toLocaleString('de-DE',{maximumFractionDigits:2})} Nutzer. Compute bestimmt die Kapazität; Nutzer erzeugen Credits und Daten.`,`Our hardware now produces ${usersRate(s).toLocaleString('en-US',{maximumFractionDigits:2})} users. Compute determines capacity; users generate credits and data.`)},
 'tutorial-credits':{speaker:'Mira',text:s=>localized(s,'Lass die Produktion laufen, bis das markierte Creditkonto 25 Credits zeigt. Taps und reguläre Produktion zählen.','Let production run until the highlighted credit balance reaches 25. Taps and regular production count.')},
 'tutorial-training':{speaker:'Mira',text:s=>s.settings.language==='de'?`Training verbessert das Modell. Starte Quality-Training; der aktuelle Creditpreis ist ${trainingCost(s,'quality').toLocaleString('de-DE')}.`:`Training improves the model. Start quality training; its current credit cost is ${trainingCost(s,'quality').toLocaleString('en-US')}.`},
 'tutorial-research':{speaker:'Mira',text:s=>s.settings.language==='de'?'Forschung kostet Daten und hat eine feste Laufzeit. Starte Datenerzeugung Stufe 1 über den markierten Forschungsauftrag.':'Research costs data and has a fixed duration. Start data generation level 1 using the highlighted research project.'},
 'tutorial-analysis':{speaker:'Mira',text:s=>s.settings.language==='de'?'Analysen sammeln Komponenten in einem separaten Slot. Starte eine kurze Hardwareanalyse oder beschaffe eine Komponente aus einer echten passiven Quelle.':'Analyses collect components in a separate slot. Start a short hardware analysis or obtain a component from a real passive source.'},
 'tutorial-components':{speaker:'Mira',text:s=>s.settings.language==='de'?'Öffne jetzt den Komponentenbestand und sieh dir die echten Analysefunde an.':'Now open the component inventory and inspect the actual analysis finds.'},
 'tutorial-crafting':{speaker:'Mira',text:s=>s.settings.language==='de'?'Crafting verarbeitet Materialien zu Ausrüstung. Stelle ein tatsächlich freigeschaltetes und bezahlbares Rezept fertig.':'Crafting turns materials into equipment. Complete a recipe that is genuinely unlocked and affordable.'},
 'tutorial-prestige':{speaker:'Mira',text:s=>localized(s,`Sobald mindestens 1 INT erreichbar ist, öffne den Prestige-Reiter. Aktuell sind ${newINT(s)} INT beanspruchbar.`,`Once at least 1 INT is available, open the Prestige tab. Currently ${newINT(s)} INT can be claimed.`)},
 'tutorial-complete':{speaker:'Mira',text:s=>s.settings.language==='de'?'Sehr gut. Das Garagenlabor ist bereit für den Weg vom KI-Prototyp zum Startup und zur AI-Company.':'Excellent. The garage lab is ready to grow from an AI prototype into a startup and an AI company.'},
 'first-lab':{speaker:'Mira',text:s=>localized(s,`Das Garagenlabor läuft. ${ai(s)} hat den ersten echten Credit-Impuls verarbeitet.`,`The garage lab is running. ${ai(s)} processed its first real credit impulse.`)},
 'first-ai':{speaker:'Mira',text:s=>localized(s,`${ai(s)} führt jetzt das erste echte Training aus. Aus dem Skript wird ein lernender Prototyp.`,`${ai(s)} is now running its first real training session. The script is becoming a learning prototype.`)},
 'first-analysis':{speaker:'Mira',text:s=>localized(s,`Die erste Analyse läuft. Ihr Auftrag endet um ${new Date(s.experiments.active?.endsAt??s.savedAt).toLocaleTimeString(s.settings.language==='de'?'de-DE':'en-US')}.`,`The first analysis is running. Its job ends at ${new Date(s.experiments.active?.endsAt??s.savedAt).toLocaleTimeString('en-US')}.`)},
 'first-item':{speaker:'Mira',text:s=>localized(s,`Unser erstes Item ist fertig. Die Sammlung enthält jetzt ${s.inventory.length} Item${s.inventory.length===1?'':'s'}.`,`Our first item is complete. The collection now contains ${s.inventory.length} item${s.inventory.length===1?'':'s'}.`)},
 'first-automation':{speaker:'Mira',text:s=>localized(s,'Die erste echte Automation ist aktiv. Ihre gespeicherten Einstellungen ersetzen keine Ressourcenprüfung.','The first real automation is active. Its saved settings never bypass resource checks.')},
 'first-hardware':{speaker:'Mira',text:s=>localized(s,`Erste Hardwareklasse online. ${s.hardware} Geräte liefern Compute für ${usersRate(s).toLocaleString('de-DE',{maximumFractionDigits:2})} Nutzer.`,`First hardware class online. ${s.hardware} devices provide compute for ${usersRate(s).toLocaleString('en-US',{maximumFractionDigits:2})} users.`)},
 'first-training':{speaker:'Mira',text:s=>localized(s,`Erstes Training abgeschlossen. ${ai(s)} steht jetzt bei Qualität ${s.qualityLevel} und Effizienz ${s.efficiencyLevel}.`,`First training complete. ${ai(s)} is now at quality ${s.qualityLevel} and efficiency ${s.efficiencyLevel}.`)},
 'first-research':{speaker:'Mira',text:s=>localized(s,`Das erste Forschungsprojekt läuft. ${s.researchLabs.filter(Boolean).length} Laborplatz ist belegt.`,`The first research project is running. ${s.researchLabs.filter(Boolean).length} lab slot is occupied.`)},
 'first-milestone':{speaker:'Mira',text:()=> 'Ein echter Hardware-Meilenstein. Große Stückzahlen verbessern nicht nur die Klasse selbst, sondern prägen die Leistung des ganzen Labors.'},
 'prestige-ready':{speaker:'Mira',text:s=>`${newINT(s)} INT wären jetzt erreichbar. Der Neustart geschieht nur, wenn du ihn im Prestige-Reiter selbst bestätigst.`},
 'first-prestige':{speaker:'Mira',text:s=>localized(s,`Der Neustart brachte ${s.telemetry.prestigeHistory.at(-1)?.intEarned??0} INT. Credits, Daten, Hardware und Modell wurden zurückgesetzt; Forschung, Sammlung und Crafting bleiben. INT kaufst du im Prestige-Baum für dauerhafte Knoten dieses Axiom-Zyklus.`,`The restart yielded ${s.telemetry.prestigeHistory.at(-1)?.intEarned??0} INT. Credits, data, hardware, and model levels reset; research, collection, and crafting remain. Spend INT on persistent nodes for this Axiom cycle.`)},
 'first-axiom':{speaker:'Mira',text:s=>localized(s,'Axiome sind die zweite Prestige-Ebene. Der normale INT- und Prestige-Fortschritt startet neu; Sammlung, Forschung und alle permanent gekauften Axiom-Upgrades bleiben erhalten.','Axioms are the second prestige layer. Normal INT and prestige progress starts over; collection, research, and every permanently purchased Axiom upgrade remain.')},
 'aura-signal-1':{speaker:'Mira',title:s=>localized(s,'Ein Signal im Rauschen','A Signal in the Noise'),text:s=>localized(s,'Da ist es: unser erstes lernendes Modell. Noch klein, noch voller Fehler — aber es verbessert sich.',`There it is: our first learning model. Still small, still full of errors — but it is improving.`)},
 'aura-signal-2':{speaker:'Mira',title:s=>localized(s,'Ein Signal im Rauschen','A Signal in the Noise'),text:s=>localized(s,`Hardware gibt ${ai(s)} Rechenleistung. Training macht daraus ein besseres Modell. Beides brauchen wir.`,`Hardware gives ${ai(s)} computing power. Training turns it into a better model. We need both.`)},
 'aura-customers-1':{speaker:'Mira',title:s=>localized(s,'Die ersten Kunden','The First Customers'),text:s=>localized(s,`Tausend Menschen nutzen ${ai(s)}. Unser Experiment hilft inzwischen jemandem außerhalb dieses Raums.`,`A thousand people are using ${ai(s)}. Our experiment is now helping someone outside this room.`)},
 'aura-customers-2':{speaker:'Mira',title:s=>localized(s,'Die ersten Kunden','The First Customers'),text:s=>localized(s,'Ihre Nutzung bringt Credits und Daten. Credits finanzieren Hardware; Daten ermöglichen Forschung und weitere Verbesserungen.','Their usage generates credits and data. Credits fund hardware; data enables research and further improvements.')},
 'aura-company-1':{speaker:'Mira',title:s=>localized(s,'Vom Labor zur Firma','From Lab to Company'),text:s=>localized(s,'Wir haben den ersten Neustart geschafft. Aus einem Versuch wird jetzt eine Firma.','We completed our first restart. An experiment is now becoming a company.')},
 'aura-company-2':{speaker:'Mira',title:s=>localized(s,'Vom Labor zur Firma','From Lab to Company'),text:s=>localized(s,'Die Erfahrung bleibt in unserer INT erhalten. Wir bauen neu auf — mit dem Wissen, was diesmal besser funktionieren kann.','The experience remains in our INT. We are rebuilding — with the knowledge of what can work better this time.')},
 'aura-equipment-1':{speaker:'Mira',title:s=>localized(s,'Mehr als eine Maschine','More Than a Machine'),text:s=>localized(s,`Jetzt bekommt ${ai(s)} seine erste eigene Ausrüstung. Die Materialien haben endlich eine Aufgabe.`,`Now ${ai(s)} has its first equipment of its own. The materials finally have a purpose.`)},
 'aura-equipment-2':{speaker:'Mira',title:s=>localized(s,'Mehr als eine Maschine','More Than a Machine'),text:s=>localized(s,'Mit wenigen Plätzen zählt die Kombination. Schau dir an, was ein Item verändert, bevor du dich entscheidest.','With only a few slots, the combination matters. Check what an item changes before you decide.')},
 'aura-infrastructure-1':{speaker:'Mira',title:s=>localized(s,'Unsere eigene Infrastruktur','Our Own Infrastructure'),text:s=>localized(s,'Ein eigenes Server-Rack. Ich glaube, wir müssen bald die Kaffeemaschine aus dem Technikraum retten.','Our own server rack. I think we may need to rescue the coffee machine from the server room soon.')},
 'aura-infrastructure-2':{speaker:'Mira',title:s=>localized(s,'Unsere eigene Infrastruktur','Our Own Infrastructure'),text:s=>localized(s,'Unsere Infrastruktur wächst. Das nächste Ziel ist nicht nur mehr Leistung, sondern ein System, dessen Teile zusammenarbeiten.','Our infrastructure is growing. The next goal is not just more power, but a system whose parts work together.')},
};
export const storyChapters=[
 {id:'aura-signal',pages:['aura-signal-1','aura-signal-2']},
 {id:'aura-customers',pages:['aura-customers-1','aura-customers-2']},
 {id:'aura-company',pages:['aura-company-1','aura-company-2']},
 {id:'aura-equipment',pages:['aura-equipment-1','aura-equipment-2']},
 {id:'aura-infrastructure',pages:['aura-infrastructure-1','aura-infrastructure-2']},
] as const;
const append=(s:GameState,id:string)=>{if(s.story.seen.includes(id)||s.story.open===id||s.story.queue.includes(id))return s;const story=s.story.open?{...s.story,queue:[...s.story.queue,id]}:{...s.story,open:id,seen:[...s.story.seen,id]};return{...s,story}};
const events=(s:GameState)=>[...s.telemetry.permanentEvents,...s.telemetry.recentEvents];
const totalTaps=(s:GameState)=>s.telemetry.archivedMetrics.taps+s.telemetry.metrics.reduce((sum,b)=>sum+b.taps,0);
const firstMilestoneCount=(s:GameState)=>Object.entries(s.hardwareCounts).reduce((sum,[id,count])=>sum+reachedMilestones(id as HardwareId,count).length,0);
const targets:Exclude<TutorialTarget,'name'|'prologue'|null>[]=['tap','hardware','production','credits','training','research','analysis','crafting','prestige'];
const hasEvent=(s:GameState,type:string)=>events(s).some(e=>e.type===type);
const fulfilled=(s:GameState,target:TutorialTarget)=>target==='tap'?totalTaps(s)>0:target==='hardware'?s.lifetime.hardwareBought>0:target==='production'?s.lifetime.hardwareBought>0&&usersRate(s)>0:target==='credits'?s.credits>=25:target==='training'?!!s.activeTraining||hasEvent(s,'training-start'):target==='research'?s.researchLabs.some(Boolean)||s.lifetime.researchStarted>0:target==='analysis'?!!s.experiments.active||hasEvent(s,'experiment-start')||s.lifetime.componentsEarned>0:target==='crafting'?!!s.crafting.active||s.crafting.queue.length>0||s.lifetime.itemsCrafted>0||s.inventory.length>0:target==='prestige'?newINT(s)>=1:false;
const nextTarget=(target:TutorialTarget)=>targets[targets.indexOf(target as typeof targets[number])+1]??null;
export function advanceTutorial(s:GameState):GameState{if(s.story.tutorial!=='active'||s.story.target==='name'||s.story.target==='prologue'||!s.story.target)return s;let next=s,target=s.story.target,guard=0;while(target&&guard++<targets.length&&fulfilled(next,target)){target=nextTarget(target);next={...next,story:{...next.story,target,tutorial:target?'active':'completed'}};next=append(next,target?`tutorial-${target}`:'tutorial-complete')}return next}
const chapterReached=(s:GameState,id:string)=>id==='aura-signal'?s.qualityLevel>=1:id==='aura-customers'?usersRate(s)>=1000:id==='aura-company'?s.prestigeCount>=1:id==='aura-equipment'?Object.values(s.equipped).some(Boolean):id==='aura-infrastructure'?s.hardwareCounts.server>=1:false;
const unlockChapter=(s:GameState,id:string,autoOpen=true)=>{if((s.story.chapters??[]).includes(id))return s;const chapter=storyChapters.find(x=>x.id===id);if(!chapter)return s;const story={...s.story,chapters:[...(s.story.chapters??[]),id],seen:[...new Set([...s.story.seen,...chapter.pages])]};let next:GameState={...s,story};if(autoOpen&&story.enabled!==false)next=append({...next,story:{...story,seen:story.seen.filter(page=>page!==chapter.pages[0])}},chapter.pages[0]);return next};
export function prepareStoryOnLoad(s:GameState):GameState{if(s.story.chapters!==undefined)return s;let next:GameState={...s,story:{...s.story,chapters:[],enabled:s.story.enabled!==false}};for(const chapter of storyChapters)if(chapterReached(next,chapter.id))next=unlockChapter(next,chapter.id,false);return next}
export function syncStory(before:GameState,after:GameState):GameState{let next=advanceTutorial(after);if(totalTaps(before)===0&&totalTaps(after)>0)next=append(next,'first-lab');if(after.hardware>before.hardware)next=append(next,'first-hardware');if(!before.activeTraining&&after.activeTraining)next=append(next,'first-ai');if(after.level>before.level)next=append(next,'first-training');if(before.lifetime.researchStarted===0&&after.lifetime.researchStarted>0)next=append(next,'first-research');if(!before.experiments.active&&after.experiments.active)next=append(next,'first-analysis');if(after.inventory.length>before.inventory.length)next=append(next,'first-item');if(!before.automation.enabled&&after.automation.enabled||!Object.values(before.hardwareAutoBuyers).some(Boolean)&&Object.values(after.hardwareAutoBuyers).some(Boolean))next=append(next,'first-automation');if(after.completedResearch.length>before.completedResearch.length||after.breakthroughs.length>before.breakthroughs.length)next=append(next,'first-research');if(firstMilestoneCount(after)>firstMilestoneCount(before))next=append(next,'first-milestone');if(newINT(before)<1&&newINT(after)>=1)next=append(next,'prestige-ready');if(after.prestigeCount>before.prestigeCount)next=append(next,'first-prestige');if(after.axiomResetCount>before.axiomResetCount)next=append(next,'first-axiom');for(const chapter of storyChapters)if(!chapterReached(before,chapter.id)&&chapterReached(after,chapter.id))next=unlockChapter(next,chapter.id);return next}
const showNext=(s:GameState,story:StoryState,id?:string)=>{const open=id??story.queue[0]??null,queue=id?story.queue.filter(q=>q!==id):story.queue.slice(open?1:0);return{...s,story:{...story,open,queue,seen:open&&!story.seen.includes(open)?[...story.seen,open]:story.seen}}};
export function chooseAiName(s:GameState,name:string):GameState{return s.aiName!==null?s:{...s,aiName:name,story:{...s.story,target:'prologue',open:'prologue-welcome',seen:[...new Set([...s.story.seen,'prologue-welcome'])]}}}
export function continueDialogue(s:GameState):GameState{const id=s.story.open;if(!id)return s;let story={...s.story,open:null};if(story.tutorial==='active'){const prologue=['prologue-welcome','prologue-aura','prologue-funding','prologue-mission'];const index=prologue.indexOf(id);if(index>=0)return showNext(s,story,prologue[index+1]??'tutorial-tap');if(id==='tutorial-tap'){story.target='tap';return advanceTutorial({...s,story})}if(id.startsWith('tutorial-'))return advanceTutorial({...s,story})}const chapter=storyChapters.find(x=>x.pages[0]===id);if(chapter)return showNext(s,story,chapter.pages[1]);return showNext(s,story)}
export function visitTutorialComponents(s:GameState){return advanceTutorial(s)}
export function skipTutorial(s:GameState):GameState{const story={...s.story,tutorial:'skipped' as const,open:null,queue:s.story.queue.filter(id=>!id.startsWith('prologue-')&&!id.startsWith('tutorial-'))};return showNext(s,story)}
export function resumeTutorial(s:GameState):GameState{if(s.story.tutorial==='active')return s;const target=s.story.target??'tap',open=`tutorial-${target}`,story={...s.story,tutorial:'active' as const,target,open};return{...s,story:{...story,seen:story.seen.includes(open)?story.seen:[...story.seen,open]}}}
export function skipCurrentDialogue(s:GameState){const tutorialDialogue=s.story.open?.startsWith('tutorial-')||s.story.open?.startsWith('prologue-');return s.story.tutorial==='active'&&tutorialDialogue?skipTutorial(s):showNext(s,{...s.story,open:null})}
export function reopenDialogue(s:GameState,id:string){return !dialogues[id]||!s.story.seen.includes(id)||s.story.open!==null?s:{...s,story:{...s.story,open:id}}}
export function reopenChapter(s:GameState,id:string){const chapter=storyChapters.find(x=>x.id===id);return !chapter||!(s.story.chapters??[]).includes(id)||s.story.open!==null?s:{...s,story:{...s.story,open:chapter.pages[0]}}}
export function toggleStory(s:GameState){const enabled=s.story.enabled===false;return{...s,story:{...s.story,enabled,open:!enabled&&s.story.open&&!s.story.open.startsWith('tutorial-')&&!s.story.open.startsWith('prologue-')?null:s.story.open,queue:enabled?s.story.queue:s.story.queue.filter(id=>id.startsWith('tutorial-')||id.startsWith('prologue-'))}}}
