import {describe,expect,it} from 'vitest';
import {type GameState,BALANCE,baseDataRateScientific,creditRate,dataMultiplierScientific,dataRateScientific,efficiency,exactEconomyValue,newGame,productionBreakdown,quality,registerTap,softcap,startTraining,trainingDataCost,trainingDataCostForLevelScientific,trainingDurationSeconds,trainingWork,usersRateScientific} from './economy';
import {ScientificNumber} from './scientificNumber';
import {advance} from './simulation';
import {restore,serialize} from './storage';

const withData=(amount:ScientificNumber|number)=>{const value=typeof amount==='number'?ScientificNumber.from(amount):amount,base=newGame(0);return{...base,data:value.toNumber(),exactEconomy:{...base.exactEconomy,data:value.toJSON()}}};
describe('data production',()=>{
 it('uses 0.1 × sqrt(users) and therefore grows sublinearly',()=>{for(const users of [1,100,10_000,1_000_000])expect(baseDataRateScientific(ScientificNumber.from(users)).toNumber()).toBeCloseTo(.1*Math.sqrt(users),12);expect(baseDataRateScientific(ScientificNumber.from(1e12)).divide(baseDataRateScientific(ScientificNumber.from(1e6))).toNumber()).toBeCloseTo(1000);});
 it('starts at multiplier one, flattens, and remains below five',()=>{expect(dataMultiplierScientific(ScientificNumber.zero()).toNumber()).toBe(1);for(const bonus of [.1,1,10,1e12]){const multiplier=dataMultiplierScientific(ScientificNumber.from(bonus)).toNumber();expect(multiplier).toBeGreaterThanOrEqual(1);expect(multiplier).toBeLessThan(5);}});
 it('keeps large user values in scientific arithmetic',()=>{expect(baseDataRateScientific(ScientificNumber.fromParts(1,400)).toJSON()).toEqual({m:1,e:199});const fresh=newGame(0),s={...fresh,hardware:1,hardwareCounts:{...fresh.hardwareCounts,calculator:1},discovered:['calculator'] as GameState['discovered']};expect(dataRateScientific(s).compare(ScientificNumber.zero())).toBeGreaterThan(0);expect(usersRateScientific(s).compare(ScientificNumber.zero())).toBeGreaterThan(0);});
});

describe('fixed model training',()=>{
 it('uses independent data prices for quality and efficiency',()=>{const state={...withData(1e12),qualityLevel:4,efficiencyLevel:1};expect(trainingDataCost(state,'quality')).toBe(Math.ceil(15*1.75**4));expect(trainingDataCost(state,'efficiency')).toBe(Math.ceil(15*1.75));const qualityRun=startTraining(state,'quality');expect(trainingDataCost(qualityRun,'efficiency')).toBe(trainingDataCost(state,'efficiency'));});
 it('rejects missing data, subtracts exactly once, and protects double clicks',()=>{const cost=trainingDataCostForLevelScientific(1),poor=withData(cost.subtract(ScientificNumber.from(1)));expect(startTraining(poor,'quality')).toBe(poor);const ready=withData(cost),started=startTraining(ready,'quality');expect(exactEconomyValue(started,'data').isZero()).toBe(true);expect(startTraining(started,'efficiency')).toBe(started);expect(started.credits).toBe(ready.credits);expect(started.exactEconomy.credits).toEqual(ready.exactEconomy.credits);});
 it('uses the duration formula and the 72-hour cap',()=>{for(const level of [1,5,10,20])expect(trainingDurationSeconds(level)).toBeCloseTo(90*1.35**(level-1),10);expect(trainingDurationSeconds(100)).toBe(BALANCE.trainingDurationCapSeconds);});
 it('is not accelerated by compute, taps, items, breakthroughs, or timed boosts',()=>{const base={...withData(1e6),hardware:1e12,breakthroughs:['graph' as const],trainingBoostUntil:1e12,nodes:['feedback'],hardwareCounts:{...newGame(0).hardwareCounts,gpu:1000}},started=startTraining(base,'quality'),tapped=registerTap(started,0);expect(tapped.training).toBe(0);expect(advance(tapped,30,true).state.training).toBeCloseTo(30);expect(advance(started,30,false).state.training).toBeCloseTo(30);});
 it('completes once online, offline, and after reload',()=>{for(const active of [true,false]){const started=startTraining(withData(100),'quality'),partial=advance(started,45,active).state,loaded=restore(serialize(partial),45_000).state,done=advance(loaded,45,active).state;expect(done.qualityLevel).toBe(1);expect(done.activeTraining).toBeNull();expect(done.lifetime.trainingCompleted).toBe(1);expect(advance(done,90,active).state.lifetime.trainingCompleted).toBe(1);}});
 it('keeps existing quality and efficiency effects and production decomposition',()=>{expect(quality(1)).toBeGreaterThan(quality(0));expect(efficiency(1)).toBeGreaterThan(efficiency(0));expect(softcap(3.25,1)).toBe(2.5);const state={...newGame(0),hardware:4,hardwareCounts:{...newGame(0).hardwareCounts,calculator:0,sbc:0,pc:1,gpu:3},qualityLevel:6,efficiencyLevel:5},parts=productionBreakdown(state);expect(parts.rawCompute).toBe(3100);expect(parts.passive).toBeCloseTo(creditRate(state.hardware,state.level,state));});
 it('partitions elapsed training time identically',()=>{const started=startTraining(withData(100),'efficiency'),whole=advance(started,60).state,split=advance(advance(started,25).state,35).state;expect(split.training).toBeCloseTo(whole.training,12);expect(trainingWork(started,'efficiency')).toBe(90);});
});
