import {BALANCE,hardwareCost,newINT,repeatableResearchDataCost,trainingDataCost,type GameState,type ItemTypeId} from './economy';
import {analysisBlockReason} from './experiments';import {craftAffordability} from './inventory';import type{TutorialTarget}from'./story';
export type TutorialGuide={targetId:string;tab:'workshop'|'research'|'inventory'|'prestige';subtab?:'research'|'analysis';title:string;explanation:string;requirement:string|null;show:string;skip:string};
const missingRecipe=(s:GameState,type:ItemTypeId,de:boolean)=>{const quote=craftAffordability(s,type),parts:string[]=[];if(!quote.unlocked)return de?'Bauplan noch nicht freigeschaltet. Schließe zuerst eine Hardwareanalyse ab.':'Blueprint not unlocked. Complete a hardware analysis first.';for(const [id,n] of Object.entries(quote.missingComponents))if(n)parts.push(`${n} ${BALANCE.components[id as keyof typeof BALANCE.components].name}`);if(quote.data.missing)parts.push(`${Math.ceil(quote.data.missing)} ${de?'Daten':'data'}`);return parts.length?(de?`Noch benötigt: ${parts.join(' · ')}.`:`Still needed: ${parts.join(' · ')}.`):null};
const firstRecipe=(s:GameState)=>((Object.keys(BALANCE.itemRecipes) as ItemTypeId[]).find(type=>craftAffordability(s,type).unlocked)??'quantum-chip');
export function tutorialGuide(s:GameState):TutorialGuide|null{const target=s.story.target as TutorialTarget,de=s.settings.language==='de',common={show:de?'Ziel zeigen':'Show target',skip:de?'Führung beenden':'End guide'};
 if(target==='tap')return{...common,targetId:'tutorial-tap',tab:'workshop',title:de?'2 · Erster Impuls':'2 · First impulse',explanation:de?'Der markierte Labor-Impuls ist eine echte Credit-Aktion.':'The highlighted lab impulse is a real credit action.',requirement:null};
 if(target==='hardware')return{...common,targetId:'tutorial-buy-calculator',tab:'workshop',title:de?'3 · Erste Hardware':'3 · First hardware',explanation:de?'Kaufe genau ein echtes Hardwareteil.':'Buy one real hardware unit.',requirement:s.credits<hardwareCost('calculator',s.hardwareCounts.calculator,s)?(de?'Sammle zuerst genug Credits.':'Collect enough credits first.'):null};
 if(target==='production')return{...common,targetId:'tutorial-production',tab:'workshop',title:de?'4 · Nutzer und Compute':'4 · Users and compute',explanation:de?'Compute bestimmt die Nutzerkapazität; Nutzer erzeugen Credits und Daten.':'Compute determines user capacity; users generate credits and data.',requirement:null};
 if(target==='credits')return{...common,targetId:'tutorial-credits',tab:'workshop',title:de?'5 · Credits sammeln':'5 · Collect credits',explanation:de?'Warte auf reguläre Produktion oder nutze echte Taps bis 25 Credits.':'Wait for regular production or use real taps until you have 25 credits.',requirement:s.credits<25?(de?`Noch ${Math.ceil(25-s.credits)} Credits.`:`${Math.ceil(25-s.credits)} credits remaining.`):null};
 if(target==='training')return{...common,targetId:'tutorial-quality-training',tab:'workshop',title:de?'6 · Training starten':'6 · Start training',explanation:de?'Starte das markierte Quality-Training. Der echte Start zählt.':'Start the highlighted quality training. The real start counts.',requirement:s.activeTraining?(de?'Ein Training läuft bereits.':'Training is already active.'):s.data<trainingDataCost(s,'quality')?(de?'Sammle zuerst die angezeigten Daten.':'Collect the displayed data first.'):null};
 if(target==='research')return{...common,targetId:'tutorial-data-generation',tab:'research',subtab:'research',title:de?'7 · Forschung starten':'7 · Start research',explanation:de?'Starte Datenerzeugung Stufe 1; die feste Laufzeit bleibt unverändert.':'Start Data Generation level 1; its fixed duration remains unchanged.',requirement:!s.discovered.includes('sbc')?(de?'Kaufe den Einplatinencomputer regulär gegen Credits.':'Buy the single-board computer normally with Credits.'):s.data<repeatableResearchDataCost('dataGeneration',1)?(de?'Sammle die angezeigten Daten.':'Collect the displayed data.'):null};
 if(target==='analysis')return{...common,targetId:'tutorial-hardware-analysis',tab:'research',subtab:'analysis',title:de?'8 · Analyse starten':'8 · Start analysis',explanation:de?'Starte eine kurze Hardwareanalyse; alternativ zählt eine echte passive Komponentenbeschaffung.':'Start a short hardware analysis; a real passive component find also counts.',requirement:s.experiments.active?(de?'Eine Analyse läuft bereits.':'An analysis is already running.'):(analysisBlockReason(s,'hardware','short',de?'de':'en')??null)};
 if(target==='crafting'){const recipe=firstRecipe(s);return{...common,targetId:`tutorial-recipe-${recipe}`,tab:'inventory',title:de?'9 · Erstes Item':'9 · First item',explanation:de?'Starte einen regulären Item-Auftrag oder erhalte ein echtes Item.':'Start a regular item job or obtain a real item.',requirement:s.crafting.active?.kind==='item'?(de?'Herstellung läuft.':'Crafting is active.'):missingRecipe(s,recipe,de)}}
 if(target==='prestige')return{...common,targetId:'tutorial-prestige-action',tab:'prestige',title:de?'10 · Prestige vorbereiten':'10 · Prepare prestige',explanation:de?'Öffne die Vorschau, sobald mindestens 1 INT wirklich beanspruchbar ist.':'Open the preview once at least 1 INT is genuinely claimable.',requirement:newINT(s)<1?(de?'Noch kein INT beanspruchbar.':'No INT is claimable yet.'):null};return null}
export const tutorialTargetIds=['tutorial-tap','tutorial-buy-calculator','tutorial-production','tutorial-credits','tutorial-quality-training','tutorial-data-generation','tutorial-hardware-analysis','tutorial-recipe-quantum-chip','tutorial-prestige-action'];
