import {BALANCE,hardwareCost,repeatableResearchDataCost,trainingCost,trainingDataCost,type GameState,type ItemTypeId} from './economy';
import {analysisBlockReason} from './experiments';
import {craftAffordability} from './inventory';
import type {TutorialTarget} from './story';

export type TutorialGuide={targetId:string;tab:'workshop'|'research'|'inventory';subtab?:'research'|'analysis';title:string;explanation:string;requirement:string|null;show:string;skip:string};
const missingRecipe=(s:GameState,type:ItemTypeId,de:boolean)=>{const quote=craftAffordability(s,type),parts:string[]=[];for(const [id,n] of Object.entries(quote.missingComponents))if(n)parts.push(`${n} ${BALANCE.components[id as keyof typeof BALANCE.components].name}`);for(const [id,n] of Object.entries(quote.missingModules))if(n)parts.push(`${n} ${BALANCE.modules[id as keyof typeof BALANCE.modules].name}`);if(quote.data.missing)parts.push(`${Math.ceil(quote.data.missing)} ${de?'Daten':'data'}`);if(quote.missingBlueprints)parts.push(`${quote.missingBlueprints} ${de?'Bauplanfragmente':'blueprint fragments'}`);return parts.length?(de?`Noch benötigt: ${parts.join(' · ')}.`:`Still needed: ${parts.join(' · ')}.`):null};
const firstRecipe=(s:GameState)=>((Object.keys(BALANCE.itemRecipes) as ItemTypeId[]).find(type=>{const q=craftAffordability(s,type);return !q.data.missing&&!q.missingBlueprints&&!Object.keys(q.missingComponents).length&&!Object.keys(q.missingModules).length})??'quantum-chip');
export function tutorialGuide(s:GameState):TutorialGuide|null{
 const target=s.story.target as TutorialTarget,de=s.settings.language==='de',common={show:de?'Zeig mir wo':'Show me where',skip:de?'Führung beenden':'End guide'};
 if(target==='tap')return{...common,targetId:'tutorial-tap',tab:'workshop',title:de?'1 · Labor-Impuls':'1 · Lab impulse',explanation:de?'Ein Impuls bringt sofort die angezeigten Credits.':'An impulse immediately grants the displayed credits.',requirement:null};
 if(target==='calculator')return{...common,targetId:'tutorial-buy-calculator',tab:'workshop',title:de?'2 · Taschenrechner':'2 · Calculator',explanation:de?'Hardware erzeugt Compute; Nutzer erzeugen daraus Credits und Daten.':'Hardware produces compute; users turn it into credits and data.',requirement:s.credits<hardwareCost('calculator',s.hardwareCounts.calculator,s)?(de?`${Math.ceil(hardwareCost('calculator',s.hardwareCounts.calculator,s)-s.credits)} Credits fehlen.`:`Missing ${Math.ceil(hardwareCost('calculator',s.hardwareCounts.calculator,s)-s.credits)} credits.`):null};
 if(target==='quality')return{...common,targetId:'tutorial-quality-training',tab:'workshop',title:de?'3 · Quality-Training':'3 · Quality training',explanation:de?'Training verbessert das Modell. Starte gezielt den Quality-Lauf.':'Training improves the model. Start the quality run.',requirement:s.activeTraining?(de?'Ein Training läuft bereits. Warte auf den Abschluss.':'A training run is already active. Wait for it to finish.'):s.credits<trainingCost(s,'quality')||s.data<trainingDataCost(s,'quality')?(de?`Benötigt ${Math.ceil(trainingCost(s,'quality'))} Credits und ${Math.ceil(trainingDataCost(s,'quality'))} Daten.`:`Requires ${Math.ceil(trainingCost(s,'quality'))} credits and ${Math.ceil(trainingDataCost(s,'quality'))} data.`):null};
 if(target==='research')return{...common,targetId:'tutorial-data-generation',tab:'research',subtab:'research',title:de?'4 · Datenerzeugung':'4 · Data generation',explanation:de?'Forschung kostet Daten und hat eine feste Laufzeit. Der Schritt zählt erst nach Abschluss von Stufe 1.':'Research costs data and has a fixed duration. This step counts only after level 1 completes.',requirement:!s.discovered.includes('sbc')?(de?'Voraussetzung: 10 Taschenrechner entdecken den Einplatinencomputer.':'Requirement: 10 calculators discover the single-board computer.'):s.researchLabs.some(l=>l?.id==='dataGeneration')?(de?'Datenerzeugung läuft. Du kannst normal weiterspielen.':'Data generation is running. You can keep playing normally.'):s.data<repeatableResearchDataCost('dataGeneration',1)?(de?`${Math.ceil(repeatableResearchDataCost('dataGeneration',1)-s.data)} Daten fehlen.`:`Missing ${Math.ceil(repeatableResearchDataCost('dataGeneration',1)-s.data)} data.`):null};
 if(target==='analysis')return{...common,targetId:'tutorial-hardware-analysis',tab:'research',subtab:'analysis',title:de?'5 · Hardwareanalyse':'5 · Hardware analysis',explanation:de?'Analysen sammeln Komponenten in einem separaten Slot. Starte die kurze Hardwareanalyse; erst ihr Abschluss zählt.':'Analyses collect components in a separate slot. Start the short hardware analysis; only completion counts.',requirement:s.experiments.active?(de?`Analyse läuft noch ${Math.ceil(Math.max(0,s.experiments.active.endsAt-s.savedAt)/1000)} s.`:`Analysis has ${Math.ceil(Math.max(0,s.experiments.active.endsAt-s.savedAt)/1000)} s remaining.`):(analysisBlockReason(s,'hardware','short')??null)};
 if(target==='components')return{...common,targetId:'tutorial-components',tab:'inventory',title:de?'6 · Komponentenbestand':'6 · Component inventory',explanation:de?'Öffne den Bestand. Die gefundenen Materialien bleiben vollständig verfügbar.':'Open the inventory. The materials you found remain fully available.',requirement:null};
 if(target==='craft'){const recipe=firstRecipe(s);return{...common,targetId:`tutorial-recipe-${recipe}`,tab:'inventory',title:de?'7 · Ausrüstung herstellen':'7 · Craft equipment',explanation:de?'Crafting verarbeitet Materialien zu Ausrüstung. Nur ein real bezahlter, abgeschlossener Item-Auftrag zählt.':'Crafting turns materials into equipment. Only a genuinely paid and completed item job counts.',requirement:s.crafting.active?.kind==='item'?(de?'Herstellung läuft; der Schritt endet nach Fertigstellung.':'Crafting is running; the step completes when it finishes.'):missingRecipe(s,recipe,de)}}
 if(target==='equip')return{...common,targetId:'tutorial-equipment',tab:'workshop',title:de?'8 · Item ausrüsten':'8 · Equip an item',explanation:de?'Prestige öffnet den ersten Ausrüstungsplatz. Rüste danach dein erstes Item aus.':'Prestige opens the first equipment slot. Equip your first item afterwards.',requirement:s.prestigeCount<1?(de?'Voraussetzung: erster Prestige. Spiele bis mindestens 1 INT erreichbar ist.':'Requirement: first prestige. Play until at least 1 INT is available.'):!s.inventory.length?(de?'Voraussetzung: ein hergestelltes oder gefundenes Item.':'Requirement: a crafted or found item.'):null};
 return null;
}

export const tutorialTargetIds=['tutorial-tap','tutorial-buy-calculator','tutorial-quality-training','tutorial-data-generation','tutorial-hardware-analysis','tutorial-components','tutorial-recipe-quantum-chip','tutorial-equipment'];
