import {describe,expect,it} from 'vitest';import {newGame,registerTap} from './economy';import {addEvent} from './telemetry';import {advanceTutorial,chooseAiName,resumeTutorial,skipTutorial,syncStory} from './story';import {tutorialGuide,tutorialTargetIds} from './tutorialGuide';
const at=(target:any)=>({...chooseAiName(newGame(0),'Nova'),story:{...chooseAiName(newGame(0),'Nova').story,open:null,target}});
describe('Mira guided campaign',()=>{
 it('maps all nine post-name actions to stable visible targets',()=>{const targets=['tap','hardware','production','credits','training','research','analysis','crafting','prestige'] as const,ids=['tutorial-tap','tutorial-buy-calculator','tutorial-production','tutorial-credits','tutorial-quality-training','tutorial-data-generation','tutorial-hardware-analysis','tutorial-recipe-quantum-chip','tutorial-prestige-action'];targets.forEach((target,index)=>expect(tutorialGuide(at(target))?.targetId).toBe(ids[index]));expect(tutorialTargetIds).toEqual(ids)});
 it('uses the real action order without synthetic completion',()=>{let state=at('tap');expect(advanceTutorial(state).story.target).toBe('tap');const tapped=syncStory(state,registerTap(state,0));expect(tapped.story.target).toBe('hardware');const bought={...tapped,lifetime:{...tapped.lifetime,hardwareBought:1,calculatorsBought:1}};expect(syncStory(tapped,bought).story.target).toBe('credits')});
 it('counts starts for training, research, and analysis but not merely opening their panels',()=>{let state=at('training');expect(advanceTutorial(state).story.target).toBe('training');state={...state,activeTraining:{track:'quality' as const,workRequired:10,creditCost:0}};expect(advanceTutorial(state).story.target).toBe('research');let research=at('research');research={...research,researchLabs:[{id:'dataGeneration' as const,level:1,startedAt:0,endsAt:10,durationSeconds:10,dataCost:1},null,null,null]};expect(advanceTutorial(research).story.target).toBe('analysis');const analysis=addEvent(at('analysis'),'experiment-start',0,{type:'hardware',length:'short'});expect(advanceTutorial(analysis).story.target).toBe('crafting')});
 it('recognizes real passive components, item jobs, and claimable prestige',()=>{expect(advanceTutorial({...at('analysis'),lifetime:{...at('analysis').lifetime,componentsEarned:1}}).story.target).toBe('crafting');const craft=at('crafting'),job={id:'x',kind:'item' as const,recipeId:'quantum-chip' as const,quantity:1,completed:0,durationPerUnit:1,startedAt:0,endsAt:1,ingredients:{components:{},modules:{},data:0,blueprints:0},result:{kind:'item' as const,id:'quantum-chip' as const,rarity:'common' as const}};expect(advanceTutorial({...craft,crafting:{active:job,queue:[]}}).story.target).toBe('prestige')});
 it('explains live lock reasons',()=>{expect(tutorialGuide(at('research'))?.requirement).toContain('10 Taschenrechner');expect(tutorialGuide(at('crafting'))?.requirement).toContain('Noch benötigt');expect(tutorialGuide(at('prestige'))?.requirement).toContain('Noch kein INT')});
 it('persists, skips, resumes, and restarts a completed guide without rewards',()=>{const state=at('analysis'),copy=JSON.parse(JSON.stringify(state)),skipped=skipTutorial(copy),resumed=resumeTutorial(skipped),completed={...state,story:{...state.story,tutorial:'completed' as const,target:null}},restarted=resumeTutorial(completed);expect(resumed.story.target).toBe('analysis');expect(resumed.story.open).toBe('tutorial-analysis');expect(restarted.story.target).toBe('tap');expect(restarted.story.open).toBe('tutorial-tap');expect(restarted.credits).toBe(completed.credits)});
 it('queues simultaneous events instead of overlapping dialogues',()=>{const state=at('hardware'),after={...state,lifetime:{...state.lifetime,hardwareBought:1},activeTraining:{track:'quality' as const,workRequired:1,creditCost:0}};const once=syncStory(state,after);expect(once.story.open).not.toBeNull();expect(new Set([once.story.open,...once.story.queue]).size).toBe(1+once.story.queue.length)});
});
