import {describe,expect,it} from 'vitest';
import {addEvent} from './telemetry';
import {newGame} from './economy';
import {advanceTutorial,resumeTutorial,skipTutorial,syncStory,visitTutorialComponents} from './story';
import {tutorialGuide,tutorialTargetIds} from './tutorialGuide';

const at=(target:any)=>({...newGame(0),story:{...newGame(0).story,open:null,target}});
describe('Mira guided tutorial',()=>{
 it('maps every fixed step to a stable tab and target',()=>{const expected=['workshop','workshop','workshop','research','research','inventory','inventory','workshop'];(['tap','calculator','quality','research','analysis','components','craft','equip'] as const).forEach((target,index)=>{const guide=tutorialGuide(at(target));expect(guide?.tab).toBe(expected[index]);expect(guide?.targetId).toBe(tutorialTargetIds[index])})});
 it('advances only from real actions and completions',()=>{let before=at('calculator'),opened={...before};expect(syncStory(before,opened).story.target).toBe('calculator');const bought={...before,lifetime:{...before.lifetime,calculatorsBought:1}};expect(syncStory(before,bought).story.target).toBe('quality');before=at('research');const started={...before,researchLabs:[{id:'dataGeneration' as const,level:1,startedAt:0,endsAt:10,durationSeconds:10,dataCost:1},null,null,null]};expect(syncStory(before,started).story.target).toBe('research');expect(syncStory(before,{...started,researchLevels:{...started.researchLevels,dataGeneration:1}}).story.target).toBe('analysis')});
 it('requires a completed short hardware analysis and completed item craft',()=>{let state=at('analysis');const started=addEvent(state,'experiment-start',0,{type:'hardware',length:'short'});expect(advanceTutorial(started).story.target).toBe('analysis');const wrong=addEvent(state,'experiment-complete',1,{type:'architecture',length:'short'});expect(advanceTutorial(wrong).story.target).toBe('analysis');const done=addEvent(state,'experiment-complete',1,{type:'hardware',length:'short'});expect(advanceTutorial(done).story.target).toBe('components');state=at('craft');expect(advanceTutorial({...state,crafting:{...state.crafting,active:{id:'x',kind:'item',recipeId:'quantum-chip',quantity:1,completed:0,durationPerUnit:1,startedAt:0,endsAt:1,ingredients:{components:{},modules:{},data:0,blueprints:0},result:{kind:'item',id:'quantum-chip',rarity:'common'}}}}).story.target).toBe('craft');expect(advanceTutorial({...state,lifetime:{...state.lifetime,itemsCrafted:1}}).story.target).toBe('equip')});
 it('does not complete component inventory merely by calculating its guide',()=>{const state=at('components');expect(tutorialGuide(state)?.targetId).toBe('tutorial-components');expect(advanceTutorial(state).story.target).toBe('components');expect(visitTutorialComponents(state).story.target).toBe('craft')});
 it('explains locked and unaffordable targets from live state',()=>{const research=tutorialGuide(at('research'));expect(research?.requirement).toContain('10 Taschenrechner');const craft=tutorialGuide(at('craft'));expect(craft?.requirement).toContain('Noch benötigt');const equip=tutorialGuide(at('equip'));expect(equip?.requirement).toContain('erster Prestige')});
 it('preserves the step through reload-shaped copies and supports skip/resume without rewards',()=>{const state=at('analysis'),copy=JSON.parse(JSON.stringify(state)),skipped=skipTutorial(copy),resumed=resumeTutorial(skipped);expect(copy.story.target).toBe('analysis');expect(skipped.story.target).toBe('analysis');expect(skipped.story.tutorial).toBe('skipped');expect(resumed.story.tutorial).toBe('active');expect(resumed.story.open).toBe('tutorial-analysis');expect(resumed.credits).toBe(state.credits);expect(resumed.onboarding).toEqual(state.onboarding)});
 it('does not flood the dialogue queue when synchronized repeatedly',()=>{const state=at('calculator'),done={...state,lifetime:{...state.lifetime,calculatorsBought:1}};const once=syncStory(state,done),twice=syncStory(once,once);expect(twice.story.seen.filter(id=>id==='tutorial-quality')).toHaveLength(1);expect(twice.story.queue.filter(id=>id==='tutorial-quality')).toHaveLength(0)});
});
